---
sidebar: sidebar 
permalink: concept_cs_event_rate_checker.html 
summary: 'Utilisez l"outil de vérification du taux d"événements SVM pour mesurer les taux d"événements NFS/SMB et déterminer la taille optimale de l"agent avant de déployer les collecteurs de données Workload Security.' 
keywords: event, checker, rate, sizing, cloud secure 
---
= Vérificateur de taux d'événements : Guide de dimensionnement des agents
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Déterminez la taille optimale des machines Agent en mesurant les débits d'événements NFS et SMB générés par vos SVM avant de déployer les collecteurs de données. Le script Event Rate Checker vous aide à comprendre les limites de capacité (maximum 50 collecteurs de données par Agent) et garantit que votre infrastructure Agent peut gérer le volume d'événements attendu pour une détection fiable des menaces.



== Exigences:

* IP de cluster
* Nom d'utilisateur et mot de passe de l'administrateur du cluster



NOTE: Lors de l'exécution de ce script, aucun collecteur de données ONTAP SVM ne doit être en cours d'exécution pour le SVM pour lequel le taux d'événements est déterminé.

Mesures:

. Installez l'agent en suivant les instructions de CloudSecure.
. Une fois l'agent installé, exécutez le script _server_data_rate_checker.sh_ en tant qu'utilisateur sudo :
+
 /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
. Ce script nécessite que _sshpass_ soit installé sur la machine Linux.  Il existe deux façons de l'installer :
+
.. Exécutez la commande suivante :
+
 linux_prompt> yum install sshpass
.. Si cela ne fonctionne pas, téléchargez _sshpass_ sur la machine Linux à partir du Web et exécutez la commande suivante :
+
 linux_prompt> rpm -i sshpass


. Fournissez les valeurs correctes lorsque vous y êtes invité.  Voir ci-dessous pour un exemple.
. L'exécution du script prendra environ 5 minutes.
. Une fois l'exécution terminée, le script imprimera le taux d'événements à partir du SVM.  Vous pouvez vérifier le taux d'événements par SVM dans la sortie de la console :
+
 “Svm svm_rate is generating 100 events/sec”.


Chaque collecteur de données Ontap SVM peut être associé à un seul SVM, ce qui signifie que chaque collecteur de données pourra recevoir le nombre d'événements générés par un seul SVM.

Gardez à l’esprit les points suivants :

A) Utilisez ce tableau comme guide général de dimensionnement.  Vous pouvez augmenter le nombre de cœurs et/ou de mémoire pour augmenter le nombre de collecteurs de données pris en charge, jusqu'à un maximum de 50 collecteurs de données :

|===


| Configuration de la machine agent | Nombre de collecteurs de données SVM | Taux maximal d'événements que la machine agent peut gérer 


| 4 cœurs, 16 Go | 10 collecteurs de données | 20 000 événements/sec 


| 4 cœurs, 32 Go | 20 collecteurs de données | 20 000 événements/sec 
|===
B) Pour calculer le nombre total d'événements, additionnez les événements générés pour tous les SVM de cet agent.

C) Si le script n'est pas exécuté pendant les heures de pointe ou si le trafic de pointe est difficile à prévoir, conservez une marge de taux d'événements de 30 %.

B + C doit être inférieur à A, sinon la machine Agent ne parviendra pas à surveiller.

En d’autres termes, le nombre de collecteurs de données qui peuvent être ajoutés à une seule machine agent doit être conforme à la formule ci-dessous :

 Sum of all Event rate of all Data Source Collectors + Buffer Event rate of 30% < 20000 events/second
Voir lelink:concept_cs_agent_requirements.html["Exigences relatives aux agents"] page pour les prérequis et exigences supplémentaires.



== Exemple

Disons que nous avons trois SVMS générant des taux d’événements de 100, 200 et 300 événements par seconde, respectivement.

Nous appliquons la formule :

....
 (100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec
780 events/second is < 20000 events/second, so the 3 SVMs can be monitored via one agent box.
....
La sortie de la console est disponible sur la machine Agent dans le nom de fichier __fpolicy_stat_<SVM Name>.log__ dans le répertoire de travail actuel.

Le script peut donner des résultats erronés dans les cas suivants :

* Des informations d'identification, une adresse IP ou un nom SVM incorrects sont fournis.
* Une fpolicy déjà existante avec le même nom, le même numéro de séquence, etc. donnera une erreur.
* Le script s'arrête brusquement pendant son exécution.


Un exemple d’exécution de script est présenté ci-dessous :

 [root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
....
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Getting event rate for NFS and SMB events.
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2
....
....
-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip):
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 SMB events/sec and 100 NFS events/sec
Overall svm svm_rate is generating 200 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm audit_svm is generating 200 SMB events/sec and 100 NFS events/sec
Overall svm audit_svm is generating 300 events/sec
....
 [root@ci-cs-data agent]#


== Dépannage

|===


| Question | Répondre 


| Si j'exécute ce script sur un SVM déjà configuré pour Workload Security, utilise-t-il simplement la configuration fpolicy existante sur le SVM ou en configure-t-il un temporaire et exécute-t-il le processus ? | Le vérificateur de taux d'événements peut fonctionner correctement même pour un SVM déjà configuré pour la sécurité de la charge de travail.  Il ne devrait y avoir aucun impact. 


| Puis-je augmenter le nombre de SVM sur lesquels le script peut être exécuté ? | Oui. Modifiez simplement le script et modifiez le nombre maximal de SVM de 5 à n'importe quel nombre souhaité. 


| Si j'augmente le nombre de SVM, cela augmentera-t-il le temps d'exécution du script ? | Non. Le script s'exécutera pendant 5 minutes maximum, même si le nombre de SVM est augmenté. 


| Puis-je augmenter le nombre de SVM sur lesquels le script peut être exécuté ? | Oui. Vous devez modifier le script et modifier le nombre maximal de SVM de 5 à n'importe quel nombre souhaité. 


| Si j'augmente le nombre de SVM, cela augmentera-t-il le temps d'exécution du script ? | Non. Le script s'exécutera pendant 5 minutes maximum, même si le nombre de SVM augmente. 


| Que se passe-t-il si j’exécute le vérificateur de taux d’événements avec un agent existant ? | L'exécution du vérificateur de taux d'événements sur un agent déjà existant peut entraîner une augmentation de la latence sur le SVM.  Cette augmentation sera de nature temporaire pendant l'exécution du vérificateur de taux d'événements. 
|===