---
sidebar: sidebar 
permalink: concept_cs_api.html 
keywords: api, access, token, swagger 
summary: 'La sécurité des charges de travail intègre une API puissante pour l"intégration à d"autres applications telles que les CMDB.' 
---
= API de sécurité du workload
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'API de sécurité des charges de travail permet aux clients NetApp et aux éditeurs de logiciels indépendants d'intégrer la sécurité des charges de travail à d'autres applications, comme les CMDB ou d'autres systèmes de gestion des tickets.

Conditions requises pour l'accès à l'API :

* Un modèle de token d'accès API est utilisé pour accorder l'accès.
* La gestion des tokens API est effectuée par les utilisateurs de la sécurité de la charge de travail dotés du rôle d'administrateur.




== Documentation API (swagger)

Pour obtenir les dernières informations sur l'API, connectez-vous à la sécurité de la charge de travail et accédez à *Admin > API Access*. Cliquez sur le lien *API Documentation*. La documentation API est basée sur swagger, qui fournit une brève description et des informations d'utilisation de l'API et vous permet de l'essayer dans votre environnement.


NOTE: Si vous appelez l'API Forensics Activity, utilisez l'API cloudsecure_Forensics.Activities.*v2*. Si vous effectuez plusieurs appels vers cette API, assurez-vous que les appels se produisent séquentiellement et non en parallèle. Plusieurs appels parallèles peuvent entraîner la temporisation de l'API.



== Jetons d'accès à l'API

Avant d'utiliser l'API de sécurité de la charge de travail, vous devez créer un ou plusieurs jetons d'accès *API*. Les jetons d'accès accordent des autorisations de lecture. Vous pouvez également définir l'expiration de chaque jeton d'accès.

Pour créer un token d'accès :

* Cliquez sur *Admin > accès API*
* Cliquez sur *+jeton d'accès API*
* Saisissez *Nom de token*
* Spécifiez *expiration du token*



NOTE: Votre jeton ne sera disponible que pour la copie dans le presse-papiers et l'enregistrement pendant le processus de création. Les tokens ne peuvent pas être récupérés après leur création. Il est donc fortement recommandé de les copier et de les enregistrer dans un emplacement sécurisé. Vous serez invité à cliquer sur le bouton Copier le token d'accès à l'API avant de pouvoir fermer l'écran de création du jeton.

Vous pouvez désactiver, activer et révoquer des jetons. Les tokens désactivés peuvent être activés.

Les jetons accordent un accès général aux API du point de vue du client, et gèrent l'accès aux API dans le cadre de leur propre environnement.

L'application reçoit un token d'accès après l'authentification et l'autorisation de l'accès, puis transmet le token d'accès en tant qu'identifiant lorsqu'il appelle l'API cible. Le jeton transmis informe l'API que le porteur du jeton a été autorisé à accéder à l'API et à effectuer des actions spécifiques en fonction de l'étendue accordée lors de l'autorisation.

L'en-tête HTTP où le token d'accès est transmis est *X-CloudInsights-ApiKey:*

Par exemple, utilisez les éléments suivants pour récupérer des actifs de stockage :

 curl https://<tenant_host_name>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
Où _<API_Access_Token>_ est le jeton que vous avez enregistré lors de la création de la clé d'accès à l'API.

Vous trouverez des informations détaillées dans le lien _API Documentation_ sous *Admin > API Access*.



== Script pour extraire les données via l'API

Les agents de sécurité de la charge de travail incluent un script d'exportation qui facilite les appels parallèles vers l'API v2 en divisant la plage de temps demandée en lots plus petits.

Le script se trouve à l'adresse _/opt/NetApp/cloudsecure/agent/export-script_. Un fichier README dans le même répertoire fournit des instructions d'utilisation.

Voici un exemple de commande pour appeler le script :

[source]
----
python3 data-export.py --tenant_url <tenant id>.cs01.cloudinsights.netapp.com --access_key %ACCESS_KEY% --path_filter "<dir path>" --user_name "<user>" --from_time "01-08-2024 00:00:00" --to_time "31-08-2024 23:59:59" --iteration_interval 12 --num_workers 3
----
Paramètres clés `--iteration_interval 12` : -: fractionne la plage de temps demandée en intervalles de 12 heures. - `--num_workers 3`: Fetches ces intervalles en parallèle à l'aide de 3 threads.
