---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: Les techniques de recherche avancées peuvent vous aider à localiser les actifs que vous recherchez. 
keywords: asset page, objects, search, advanced, alerts 
---
= Conseils et astuces pour rechercher des actifs et des alertes
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Plusieurs techniques de recherche peuvent être utilisées pour rechercher des données ou des objets dans votre environnement surveillé.

* *Recherche générique*
+
Vous pouvez effectuer une recherche avec plusieurs caractères génériques à l'aide du caractère *.  Par exemple, _applic*n_ renverrait _application_.

* *Phrases utilisées dans la recherche*
+
Une phrase est un groupe de mots entourés de guillemets doubles ; par exemple, « VNX LUN 5 ».  Vous pouvez utiliser des guillemets doubles pour rechercher des documents contenant des espaces dans leurs noms ou leurs attributs.

* *Opérateurs booléens*
+
En utilisant les opérateurs booléens OU, ET et NON, vous pouvez combiner plusieurs termes pour former une requête plus complexe.

+
OU

+
L'opérateur OR est l'opérateur de conjonction par défaut.

+
S'il n'y a pas d'opérateur booléen entre deux termes, l'opérateur OU est utilisé.

+
L'opérateur OR relie deux termes et trouve un document correspondant si l'un des termes existe dans un document.

+
Par exemple, _storage OR netapp_ recherche les documents qui contiennent _storage_ ou _netapp_.

+
Des notes élevées sont attribuées aux documents qui correspondent à la plupart des termes.

+
ET

+
Vous pouvez utiliser l'opérateur AND pour rechercher des documents dans lesquels les deux termes de recherche existent dans un seul document.  Par exemple, _storage AND netapp_ recherche les documents qui contiennent à la fois _storage_ et _netapp_.

+
Vous pouvez utiliser le symbole *&&* à la place du mot AND.

+
PAS

+
Lorsque vous utilisez l'opérateur NOT, tous les documents contenant le terme après NOT sont exclus des résultats de la recherche.  Par exemple, _storage NOT netapp_ recherche les documents qui contiennent uniquement _storage_ et non _netapp_.

+
Vous pouvez utiliser le symbole *!* à la place du mot NOT.



La recherche n'est pas sensible à la casse.



== Rechercher à l'aide de termes indexés

Les recherches qui correspondent à davantage de termes indexés génèrent des scores plus élevés.

La chaîne de recherche est divisée en termes de recherche distincts par un espace.  Par exemple, la chaîne de recherche « storage aurora netapp » est divisée en trois mots-clés : « storage », « aurora » et « netapp ».  La recherche est effectuée en utilisant les trois termes.  Les documents qui correspondent à la plupart de ces termes auront le score le plus élevé.  Plus vous fournissez d'informations, meilleurs seront les résultats de recherche.  Par exemple, vous pouvez rechercher un stockage par son nom et son modèle.

L'interface utilisateur affiche les résultats de la recherche par catégories, avec les trois premiers résultats par catégorie.  Si vous n’avez pas trouvé l’objet que vous attendiez, vous pouvez inclure plus de termes dans la chaîne de recherche pour améliorer les résultats de la recherche.

Le tableau suivant fournit une liste de termes indexés qui peuvent être ajoutés à la chaîne de recherche.

|===
| Catégorie | Termes indexés 


| Stockage | modèle de fournisseur de nom de « stockage » 


| Pool de stockage | nom du pool de stockage nom du stockage adresses IP du stockage numéro de série du stockage fournisseur de stockage modèle de stockage noms de tous les volumes internes associés noms de tous les disques associés 


| Volume interne | "internalvolume" nom nom du stockage adresses IP du stockage numéro de série du stockage fournisseur de stockage modèle de stockage nom du pool de stockage noms de tous les partages associés noms de toutes les applications associées 


| Volume | nom de « volume » nom de l'étiquette noms de tous les volumes internes nom du pool de stockage nom du stockage adresses IP du stockage numéro de série du stockage fournisseur de stockage modèle de stockage 


| Nœud de stockage | "storagenode" nom nom du stockage adresses IP du stockage numéro de série du stockage fournisseur de stockage modèle de stockage 


| Hôte | nom d'« hôte » adresses IP noms de toutes les applications associées 


| Magasin de données | nom du « datastore » nom du centre virtuel noms IP de tous les volumes noms de tous les volumes internes 


| Machines virtuelles | nom de « machine virtuelle » nom DNS adresses IP nom de l'hôte adresses IP de l'hôte noms de tous les magasins de données noms de toutes les applications associées 


| Commutateurs (réguliers et NPV) | "switch" adresse IP nom wwn numéro de série modèle identifiant de domaine nom de la structure wwn de la structure 


| Application | « application » nom locataire secteur d'activité unité commerciale projet 


| Ruban adhésif | "bande" adresse IP nom numéro de série fournisseur 


| Port | nom WWN « port » 


| Tissu | nom wwn « tissu » 


| Machine virtuelle de stockage (SVM) | UUID du nom « storagevirtualmachine » 
|===