---
sidebar: sidebar 
permalink: concept_cs_api.html 
keywords: api, access, token, swagger 
summary: 'Accédez aux données de sécurité des charges de travail via une API REST avec authentification sécurisée par jeton pour l"intégration avec les CMDB, les systèmes de gestion des tickets et autres applications d"entreprise.' 
---
= API de sécurité de la charge de travail
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'API Workload Security permet aux clients NetApp et aux fournisseurs de logiciels indépendants (ISV) d'intégrer Workload Security à d'autres applications, telles que les CMDB ou d'autres systèmes de billetterie.

Conditions requises pour l'accès à l'API :

* Un modèle de jeton d'accès API est utilisé pour accorder l'accès.
* La gestion des jetons API est effectuée par les utilisateurs de Workload Security avec le rôle d'administrateur.




== Documentation de l'API (Swagger)

Les dernières informations sur l'API sont disponibles en vous connectant à Workload Security et en accédant à *Admin > Accès API*.  Cliquez sur le lien *Documentation API*.  La documentation de l'API est basée sur Swagger, qui fournit une brève description et des informations d'utilisation de l'API et vous permet de l'essayer sur votre locataire.


NOTE: Si vous appelez l'API Forensics Activity, utilisez l'API cloudsecure_forensics.activities.*v2*.  Si vous effectuez plusieurs appels à cette API, assurez-vous que les appels se produisent de manière séquentielle et non en parallèle.  Plusieurs appels parallèles peuvent entraîner l’expiration du délai d’attente de l’API.



== Jetons d'accès API

Avant d’utiliser l’API Workload Security, vous devez créer un ou plusieurs *jetons d’accès API*.  Les jetons d’accès accordent des autorisations de lecture.  Vous pouvez également définir l’expiration de chaque jeton d’accès.

Pour créer un jeton d’accès :

* Cliquez sur *Admin > Accès API*
* Cliquez sur *+Jeton d'accès API*
* Entrez *Nom du jeton*
* Spécifiez *Expiration du jeton*



NOTE: Votre jeton ne sera disponible que pour la copie dans le presse-papiers et l'enregistrement pendant le processus de création.  Les jetons ne peuvent pas être récupérés après leur création, il est donc fortement recommandé de copier le jeton et de l'enregistrer dans un endroit sûr.  Vous serez invité à cliquer sur le bouton Copier le jeton d’accès API avant de pouvoir fermer l’écran de création de jeton.

Vous pouvez désactiver, activer et révoquer les jetons.  Les jetons désactivés peuvent être activés.

Les jetons accordent un accès général aux API du point de vue du client, en gérant l'accès aux API dans le cadre de leur propre locataire.

L'application reçoit un jeton d'accès après qu'un utilisateur s'est authentifié et a autorisé l'accès avec succès, puis transmet le jeton d'accès comme identifiant lorsqu'il appelle l'API cible.  Le jeton transmis informe l'API que le porteur du jeton a été autorisé à accéder à l'API et à effectuer des actions spécifiques en fonction de la portée qui a été accordée lors de l'autorisation.

L'en-tête HTTP où le jeton d'accès est transmis est *X-CloudInsights-ApiKey:*

Par exemple, utilisez ce qui suit pour récupérer les ressources de stockage :

 curl https://<Workload Security tenant>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
Où _<API_Access_Token>_ est le jeton que vous avez enregistré lors de la création de la clé d'accès API et _<Workload Security Tenant>_ est l'URL du locataire de votre environnement Workload Security.

Des informations détaillées peuvent être trouvées dans le lien _Documentation API_ sous *Admin > Accès API*.



== Script pour extraire des données via l'API

Les agents Workload Security incluent un script d'exportation pour faciliter les appels parallèles à l'API v2 en divisant la plage horaire demandée en lots plus petits.

Le script se trouve dans _/opt/netapp/cloudsecure/agent/export-script_.  Un fichier README dans le même répertoire fournit des instructions d'utilisation.

Voici un exemple de commande pour appeler le script :

[source]
----
python3 data-export.py --tenant_url <Workload Security tenant> --access_key %ACCESS_KEY% --path_filter "<dir path>" --user_name "<user>" --from_time "01-08-2024 00:00:00" --to_time "31-08-2024 23:59:59" --iteration_interval 12 --num_workers 3
----
Paramètres clés : - `--iteration_interval 12` : Divise la plage horaire demandée en intervalles de 12 heures.  - `--num_workers 3` : Récupère ces intervalles en parallèle à l'aide de 3 threads.
