---
sidebar: sidebar 
permalink: concept_asset_user_data_section.html 
summary: La section Données utilisateur d’une page d’actif vous permet d’attribuer des annotations ou des applications à l’actif actuel. 
keywords: asset page, user data, applications, annotations 
---
= Section Données utilisateur
:hardbreaks:
:allow-uri-read: 


[role="lead"]
La section Données utilisateur d'une page d'actif affiche et vous permet de modifier toutes les données définies par l'utilisateur telles que les applications et les annotations.



== Utilisation de la section Données utilisateur pour attribuer ou modifier des applications

Vous pouvez affecter des applications exécutées sur votre locataire à certaines ressources (hôte, machines virtuelles, volumes, volumes internes, qtrees et hyperviseurs).  La section Données utilisateur vous permet d'ajouter, de modifier ou de supprimer les applications attribuées à un actif.  Pour tous ces types d’actifs, à l’exception des volumes, vous pouvez attribuer plusieurs applications.

.Étapes
. Localisez une page de ressource en effectuant l’une des opérations suivantes :
+
.. Recherchez une liste d’actifs, puis sélectionnez-en un dans la liste.
.. Sur un tableau de bord, recherchez le nom d’un actif et cliquez dessus.
.. Effectuez une recherche et choisissez un actif parmi les résultats.
+
La page des ressources s'affiche.  La section Données utilisateur de la page affiche les applications ou annotations actuellement attribuées.





Pour modifier l'application attribuée, ou pour attribuer une ou plusieurs applications supplémentaires, déroulez la liste *Application* et sélectionnez la ou les applications que vous souhaitez attribuer à l'actif.  Vous pouvez taper pour rechercher une application ou en sélectionner une dans la liste.

Pour supprimer une application, déroulez la liste des applications et décochez l'application.



== Utilisation de la section Données utilisateur pour attribuer ou modifier des annotations

Lors de la personnalisation de Data Infrastructure Insights pour suivre les données en fonction des besoins de votre entreprise, vous pouvez définir des notes spécialisées appelées annotations et les attribuer à vos ressources.  La section Données utilisateur d'une page d'actif affiche les annotations attribuées à un actif et vous permet également de modifier les annotations attribuées à cet actif.

.Étapes
. Pour ajouter une annotation à l'actif, dans la section Données utilisateur de la page de l'actif, cliquez sur *+Annotation*.
. Sélectionnez une annotation dans la liste.
. Cliquez sur Valeur et effectuez l’une des opérations suivantes, selon le type d’annotation que vous avez sélectionné :
+
.. Si le type d’annotation est liste, date ou booléen, sélectionnez une valeur dans la liste.
.. Si le type d’annotation est du texte, saisissez une valeur.


. Cliquez sur Enregistrer.


L'annotation est attribuée à l'actif.  Vous pouvez ensuite filtrer les ressources par annotation à l'aide d'une requête.

Si vous souhaitez modifier la valeur de l'annotation après l'avoir attribuée, déroulez la liste des annotations et entrez une valeur différente.

Si l'annotation est de type liste pour laquelle l'option _Ajouter de nouvelles valeurs à la volée_ est sélectionnée, vous pouvez saisir pour ajouter une nouvelle valeur en plus de sélectionner une valeur existante.
