---
sidebar: sidebar 
permalink: concept_telegraf_display_options.html 
keywords: telegraf, data, display, 
summary: 'Options d"affichage des données Telegraf' 
---
= Transformer les métriques
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights fournit différentes options de *transformation* pour certaines métriques dans les widgets (en particulier, les métriques appelées « Personnalisées » ou métriques d'intégration, telles que celles de Kubernetes, ONTAP Advanced Data, des plugins Telegraf, etc.), vous permettant d'afficher les données de plusieurs manières.  Lorsque vous ajoutez des métriques transformables à un widget, une liste déroulante vous propose les choix de transformation suivants :

Aucun : les données sont affichées telles quelles, sans aucune manipulation.

Taux : Valeur actuelle divisée par la plage de temps depuis l'observation précédente.

Cumulatif : L'accumulation de la somme des valeurs précédentes et de la valeur actuelle.

Delta : La différence entre la valeur d'observation précédente et la valeur actuelle.

Taux Delta : Valeur Delta divisée par la plage de temps depuis l'observation précédente.

Taux cumulé : valeur cumulée divisée par la plage de temps depuis l'observation précédente.

Notez que la transformation des métriques ne modifie pas les données sous-jacentes elles-mêmes, mais uniquement la manière dont ces données sont affichées.
