---
sidebar: sidebar 
permalink: concept_about_applications.html 
keywords: applications, asset, cost 
summary: Comprendre les applications utilisées dans l’environnement de votre entreprise vous aide à suivre l’utilisation et les coûts des actifs. 
---
= Suivi de l'utilisation des actifs par application
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Comprendre les applications utilisées dans l’environnement de votre entreprise vous aide à suivre l’utilisation et le coût des actifs.

Avant de pouvoir suivre les données associées aux applications exécutées sur votre locataire, vous devez d’abord définir ces applications et les associer aux ressources appropriées.  Vous pouvez associer des applications aux ressources suivantes : hôtes, machines virtuelles, volumes, volumes internes, qtrees, partages et hyperviseurs.

Cette rubrique fournit un exemple de suivi de l’utilisation des machines virtuelles que l’équipe marketing utilise pour sa messagerie Exchange.

Vous souhaiterez peut-être créer un tableau similaire au suivant pour identifier les applications utilisées sur votre locataire et noter le groupe ou l'unité commerciale utilisant chaque application.

[cols="5*"]
|===


| Locataire | Secteur d'activité | Unité commerciale | Projet | Applications 


| NetApp | Stockage de données | Légal | Brevets | Oracle Identity Manager, Oracle On Demand, PatentWiz 


| NetApp | Stockage de données | Commercialisation | Événements de vente | Exchange, base de données partagée Oracle, planificateur d'événements BlastOff 
|===
Le tableau montre que l’équipe marketing utilise l’application Exchange.  Nous souhaitons suivre leur utilisation de la machine virtuelle pour Exchange, afin de pouvoir prédire quand nous devrons ajouter plus de stockage.  Nous pouvons associer l'application Exchange à toutes les machines virtuelles de Marketing :

. Créer une application nommée _Exchange_
. Accédez à *Requêtes > +Nouvelle requête* pour créer une nouvelle requête pour les machines virtuelles (ou sélectionnez une requête de machine virtuelle existante, le cas échéant).
+
En supposant que toutes les machines virtuelles de l'équipe marketing aient un nom contenant la chaîne « *mkt* », créez votre requête pour filtrer le nom de la machine virtuelle pour « mkt ».

. Sélectionnez les machines virtuelles.
. Associez les machines virtuelles à l'application _Exchange_ à l'aide de *Actions en masse > Ajouter des applications*.
. Sélectionnez l'application souhaitée et cliquez sur *Enregistrer*.
. Une fois terminé, *Enregistrez* la requête.

