---
sidebar: sidebar 
permalink: cs_intro.html 
keywords: CloudSecure, Cloud Secure 
summary: 'Protégez vos données grâce à la détection des menaces internes, à la visibilité centralisée sur les environnements hybrides et à l"apprentissage automatique avancé de Storage Workload Security pour la détection des anomalies et la conformité.' 
---
= À propos de la sécurité des charges de travail de stockage
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights Storage Workload Security (anciennement Cloud Secure) aide à protéger vos données grâce à des informations exploitables sur les menaces internes.  Il offre une visibilité et un contrôle centralisés de tous les accès aux données de l'entreprise dans les environnements de cloud hybride pour garantir que les objectifs de sécurité et de conformité sont atteints.



== Visibilité

Bénéficiez d'une visibilité et d'un contrôle centralisés de l'accès des utilisateurs à vos données d'entreprise critiques stockées sur site ou dans le cloud.

Remplacez les outils et les processus manuels qui ne parviennent pas à fournir une visibilité rapide et précise sur l’accès et le contrôle des données.  Workload Security fonctionne de manière unique sur les systèmes de stockage cloud et sur site pour vous fournir des alertes en temps réel sur le comportement malveillant des utilisateurs.



== Protection

Protégez les données de l’organisation contre toute utilisation abusive par des utilisateurs malveillants ou compromis grâce à l’apprentissage automatique avancé et à la détection des anomalies.

Vous alerte de tout accès anormal aux données grâce à l'apprentissage automatique avancé et à la détection des anomalies du comportement des utilisateurs.



== Conformité

Assurez la conformité de l'entreprise en auditant l'accès des utilisateurs à vos données d'entreprise critiques stockées sur site ou dans le cloud.
