---
sidebar: sidebar 
permalink: cs_notifications_email.html 
summary: 'Ajout d"adresses e-mail pour les notifications d"alertes de sécurité de charge de travail.' 
keywords: email, notifications, alerts, warnings, attacks 
---
= Configuration des notifications par e-mail pour les alertes, les avertissements et l'état de santé de l'agent/collecteur de sources de données
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Pour configurer les destinataires des alertes de sécurité de la charge de travail, cliquez sur *Admin > Notifications* et saisissez une adresse e-mail dans la ou les sections appropriées pour chaque destinataire.



== Alertes et avertissements d'attaque potentielle

Pour envoyer des notifications d'alerte d'attaque potentielle, saisissez les adresses e-mail des destinataires dans la section _Envoyer des alertes d'attaque potentielle_.  Des notifications par courrier électronique sont envoyées à la liste des destinataires de l'alerte pour chaque action sur l'alerte.

Pour envoyer des notifications d'avertissement, saisissez les adresses e-mail des destinataires dans la section Envoyer des alertes d'avertissement.



== Surveillance de la santé des agents et des collecteurs de données

Vous pouvez surveiller la santé des agents et des sources de données via des notifications.

Afin de recevoir des notifications dans le cas où un agent ou un collecteur de sources de données ne fonctionne pas, saisissez les adresses e-mail des destinataires dans la section _Alertes de santé de la collecte de données_.

Gardez à l’esprit les points suivants :

* Les alertes de santé ne seront envoyées qu'après que l'agent/collecteur aura cessé de signaler pendant au moins une heure.
* Une seule notification par e-mail est envoyée aux destinataires prévus au cours d'une période donnée de 24 heures, même si l'agent ou le collecteur de données est déconnecté pendant une durée plus longue.
* En cas de défaillance d'un Agent, une seule alerte sera envoyée (pas une par collecteur).  L'e-mail comprendra une liste de tous les SVM concernés.
* L'échec de la collecte d'Active Directory est signalé comme un avertissement ; il n'a aucun impact sur la détection des ransomwares.
* La liste de configuration de mise en route inclut désormais une nouvelle phase _Configurer les notifications par e-mail_.




== Notifications de mise à niveau de l'agent récepteur et du collecteur de données

* Saisissez les identifiants de messagerie dans les « Alertes de santé de collecte de données ».
* La case à cocher « Activer les notifications de mise à niveau » devient activée.
* Les notifications par e-mail de mise à niveau de l'agent et du collecteur de données sont envoyées aux identifiants de messagerie un jour avant la mise à niveau prévue.




== Dépannage

|===
| *Problème:* | *Essayez ceci :* 


| Les identifiants de messagerie sont présents dans les « Alertes de santé du collecteur de données », mais je ne reçois pas de notifications. | Les e-mails de notification sont envoyés depuis le domaine NetApp Data Infrastructure Insights , c'est-à-dire depuis _accounts@service.cloudinsights.netapp.com_.  Certaines entreprises bloquent les e-mails entrants s'ils proviennent d'un domaine externe.  Assurez-vous que les notifications externes des domaines NetApp Data Infrastructure Insights sont sur liste blanche. 
|===