---
sidebar: sidebar 
permalink: forensic_alert_detail.html 
keywords: alert, Critical, Warning, Low, alert detail Synopsis, Time range, Start time, End time, user 
summary: 'détails de l"alerte' 
---
= Détails de l'alerte
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Cliquer sur le synopsis d’une alerte ouvre la page fournissant des informations détaillées sur l’utilisateur et l’alerte qu’il a déclenchée.



== La page Détails de l'alerte affiche l'utilisateur

Les détails de l'alerte fournissent des informations sur l'alerte sélectionnée dans la page Alertes.

* La gravité de l'alerte
* L'utilisateur qui a déclenché l'alerte et le type d'alerte :
+
** Accès anormal par l'utilisateur
** Accès anormal par la communauté
** Accès anormal par utilisateur dans la communauté
** L'utilisateur a rejoint de nombreuses communautés


* Date et heure de détection de l'alerte
* Les mesures prises
+
** En quarantaine
** Autre
** Autre


* Le statut de l'alerte
+
** Nouveau
** En cours
** Rejeté
** Résolu


* Changement du taux d'activité de l'utilisateur
+
** Activités typiques par heure
** Activités par heure au moment où l'alerte a été déclenchée.
** Pourcentage de changement de taux qui a provoqué l'alerte.


* Un graphique montrant le taux d’activité moyen historique et le taux d’activité ayant entraîné l’alerte.




=== Utilisateur associé

* Nom d'utilisateur et titre
* Département
* E-mail avec un lien vers l'adresse e-mail
* Directeur
* Téléphone
* Pays




=== Activité

Affiche l'activité de l'utilisateur au cours des 7 derniers jours et le dernier emplacement à partir duquel l'utilisateur a accédé.

* Activités:
+
** Lire
** Autre
** Créer


* Nombre total d'alertes au cours des sept derniers jours.
* Nombre total d'activités au cours des 7 derniers jours.


Cliquez sur *Afficher les détails de l'activité* pour accéder àlink:forensic_activity_history["Historique des activités"] de l'utilisateur examiné.
