---
sidebar: sidebar 
permalink: forensic_user_overview.html 
keywords: Forensic, user, user, activity 
summary: 'détails de l"utilisateur médico-légal' 
---
= Présentation de l'utilisateur forensique
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les informations relatives à chaque utilisateur sont fournies dans la vue d'ensemble de l'utilisateur.  Utilisez ces vues pour comprendre les caractéristiques des utilisateurs, les entités associées et les activités récentes.



== Profil utilisateur

Les informations du profil utilisateur incluent les coordonnées et l’emplacement de l’utilisateur.  Le profil fournit les informations suivantes :

* Nom de l'utilisateur
* Adresse e-mail de l'utilisateur
* Gestionnaire des utilisateurs
* Contact téléphonique de l'utilisateur
* Localisation de l'utilisateur




== Comportement de l'utilisateur

Les informations sur le comportement de l’utilisateur identifient les activités et opérations récentes effectuées par l’utilisateur.  Ces informations comprennent :

* Activité récente
+
** Emplacement du dernier accès
** Graphique d'activité
** Alertes




* Opérations des sept derniers jours
+
** Nombre d'opérations






== Intervalle de rafraîchissement

La liste des utilisateurs est actualisée toutes les 12 heures.



== Politique de conservation

Si elle n'est pas actualisée à nouveau, la liste des utilisateurs est conservée pendant 13 mois.  Après 13 mois, les données seront supprimées.  Si votre environnement Workload Security est supprimé, toutes les données associées à l'environnement sont supprimées.
