---
sidebar: sidebar 
permalink: index.html 
summary: Bienvenue sur le portail de documentation de Data Infrastructure Insights. 
keywords:  
---
= Documentation sur Data Infrastructure Insights
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp Data Infrastructure Insights (anciennement Cloud Insights) est un outil de surveillance de l'infrastructure cloud qui vous offre une visibilité sur l'ensemble de votre infrastructure. Avec Data Infrastructure Insights, vous pouvez surveiller, dépanner et optimiser toutes vos ressources, y compris vos clouds publics et vos centres de données privés.



== Que peut m’apporter Data Infrastructure Insights ?

Data Infrastructure Insights fournit une surveillance multicloud hybride, vous offrant une observabilité complète de l'infrastructure et des charges de travail.

* Collecteurs de données pour infrastructures et charges de travail hétérogènes, y compris Kubernetes
* Collecteur Telegraf ouvert et API ouvertes pour une intégration facile
* Alertes et notifications complètes
* L'apprentissage automatique pour des informations intelligentes
* Optimiser l'utilisation des ressources
* Tableaux de bord intégrés ou personnalisables avec des filtres avancés pour minimiser le bruit d'affichage afin de répondre aux questions
* Découvrez l'état de santé de vos opérations de stockage ONTAP 
* Protégez votre actif commercial le plus précieux – les données – contre les attaques de rançongiciel ou de destruction de données


'''


== Commencer

* Comment puis-jelink:task_cloud_insights_onboarding_1.html["*commencer*"] avec Data Infrastructure Insights?
* Je suis inscrit.  Et maintenant, que dois-je faire ?link:task_getting_started_with_cloud_insights.html["Acquisition de données"] link:concept_user_roles.html["Configuration des utilisateurs"]
* Génial!  Et ensuite ?link:task_defining_annotations.html["Préparation des ressources : annotation"] link:concept_querying_assets.html["Trouver les ressources souhaitées : interrogation"] link:concept_dashboards_overview.html["Voir les données que vous souhaitez : les tableaux de bord"] link:task_create_monitor.html["Surveillance et alertes"] link:task_cs_getting_started.html["Sécurisation des données"]
* C'est du super truc !  Je suis prêt àlink:concept_subscribing_to_cloud_insights.html["*s'abonner*"] .

