---
sidebar: sidebar 
permalink: insights_overview.html 
keywords: insight, greedy, degraded, impacted, impacting, impactful, impact, resources, consuming, workload, ttf, time to full, k8s, kubernetes, namespace 
summary: Les informations vous donnent un aperçu de l’utilisation des ressources et des tendances. 
---
= Connaissances
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Les informations vous permettent d'examiner des éléments tels que l'utilisation des ressources et la manière dont elle affecte les autres ressources, ou des analyses de temps de traitement complet.

Un certain nombre d’informations sont disponibles.  Accédez à *Tableaux de bord > Insights* pour commencer à vous plonger dans le sujet. Vous pouvez afficher les Insights actifs (Insights en cours d'exécution) sur l'onglet principal ou les Insights inactifs sur l'onglet _Insights inactifs_.  Les informations inactives sont celles qui étaient auparavant actives mais qui ne se produisent plus.



== Types d'informations



=== Ressources partagées sous pression

Les charges de travail à fort impact peuvent réduire les performances d’autres charges de travail dans une ressource partagée.  Cela met la ressource partagée sous pression.  Data Infrastructure Insights fournit des outils pour vous aider à étudier la saturation des ressources et son impact sur votre locataire.link:insights_shared_resources_under_stress.html["En savoir plus"]



=== Les espaces de noms Kubernetes manquent d'espace

L'aperçu des espaces de noms Kubernetes manquant d'espace vous donne un aperçu des charges de travail sur vos espaces de noms Kubernetes qui risquent de manquer d'espace, avec une estimation du nombre de jours restants avant que chaque espace ne soit plein.link:insights_k8s_namespaces_running_out_of_space.html["En savoir plus"]



=== Récupérez le stockage à froid ONTAP

_Reclaim ONTAP Cold Storage_ Insight fournit des données sur la capacité de réfrigération, les économies potentielles de coûts/d'énergie et les éléments d'action recommandés pour les volumes sur les systèmes ONTAP .link:insights_reclaim_ontap_cold_storage.html["En savoir plus"]


NOTE: Il s'agit d'une fonctionnalité _Aperçu_ et elle peut changer au fil du temps à mesure que des améliorations sont apportées. link:/concept_preview_features.html["Apprendre encore plus"] à propos des fonctionnalités de Data Infrastructure Insights Preview.
