---
sidebar: sidebar 
permalink: reference_schemas.html 
summary: 'Diagrammes et tables de schéma d"entrepôt de données à utiliser avec les rapports' 
keywords: dwh, data warehouse, schema, reporting 
---
= Schémas Data Infrastructure Insights pour la création de rapports
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ces tableaux de schémas sont fournis ici à titre de référence pour Data Infrastructure Insights Reporting.


NOTE: La fonctionnalité de reporting est disponible dans Data Infrastructure Insightslink:concept_subscribing_to_cloud_insights.html["Édition Premium"] .

link:schema/reporting_schema_capacity.html["Tables de schéma - Capacité"^] link:schema/reporting_schema_capacity_efficiency.html["Tables de schéma - Efficacité de capacité"^] link:schema/reporting_schema_fs_util.html["Tables de schéma - Utilisation du système de fichiers"^] link:schema/reporting_schema_inventory.html["Tables de schéma - Inventaire"^] link:schema/reporting_schema_performance.html["Tables de schéma - Performance"^] link:schema/reporting_schema_ports.html["Tables de schéma - Ports"^]
