---
sidebar: sidebar 
permalink: reporting_querying_database.html 
summary: Utilisez les API Data Infrastructure Insights pour interroger directement la base de données de rapports. 
keywords: reporting, cognos, data warehouse, dwh, API 
---
= Accéder à la base de données de rapports via l'API
:hardbreaks:
:allow-uri-read: 


[role="lead"]
L'API puissante de Data Infrastructure Insights permet aux utilisateurs d'interroger directement la base de données Data Infrastructure Insights Reporting, sans passer par l'environnement Cognos Reporting.


NOTE: Cette documentation fait référence à la fonctionnalité de création de rapports Data Infrastructure Insights , disponible dans Data Infrastructure Insights Premium Edition.



== Odata

L'API de reporting Data Infrastructure Insights suit lalink:https://www.odata.org/["OData v4"] (Open Data Protocol) norme pour l'interrogation de la base de données Reporting.  Pour plus d'informations ou pour en savoir plus, consultezlink:https://www.odata.org/getting-started/basic-tutorial/["ce tutoriel"] sur OData.

Toutes les requêtes commenceront par l'URL _\https://< Data Infrastructure Insights URL>/rest/v1/dwh-management/odata_



== Générer une clé API

En savoir plus surlink:API_Overview.html["API d' Data Infrastructure Insights"] .

Pour générer une clé API, procédez comme suit :

* Connectez-vous à votre environnement Data Infrastructure Insights et sélectionnez *Admin > Accès API*.
* Cliquez sur « + Jeton d’accès API ».
* Entrez un nom et une description.
* Pour le type, choisissez _Data Warehouse_.
* Définissez les autorisations en lecture/écriture.
* Définissez une date d'expiration pour vos souhaits.
* Cliquez sur « Enregistrer », puis *copiez la clé et enregistrez-la* dans un endroit sûr.  Vous ne pourrez pas accéder à la clé complète ultérieurement.


Les clés API sont utiles pour<<synchronous-or-asynchronous,_Sync_ ou _Async_>> .



== Requête directe des tables

Avec la clé API en place, les requêtes directes sur la base de données de rapports sont désormais possibles.  Les URL longues peuvent être simplifiées en \https://.../odata/ à des fins d'affichage plutôt qu'en \https://< Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/ complet

Essayez des requêtes simples comme

* \https://< URL des Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_custom
* \https://< URL des Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_inventory
* \https://< URL des Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_inventory/storage
* \https://< URL des Data Infrastructure Insights >/rest/v1/dwh-management/odata/dwh_inventory/disk
* \https://.../odata/dwh_custom/requêtes_personnalisées




== Exemples d'API REST

L'URL pour tous les appels est _\https://< Data Infrastructure Insights URL>/rest/v1/dwh-management/odata_.

* GET /{schema}/** - Récupère les données de la base de données de rapports.


Format : _\https://< URL Data Infrastructure Insights >/rest/v1/dwh-management/odata/<nom_schéma>/<requête>_

Exemple:

 https://<domain>/rest/v1/dwh-management/odata/dwh_inventory/fabric?$count=true&$orderby=name
Résultat:

....
{
   "@odata.context": "$metadata#fabric",
   "@odata.count": 2,
   "value": [
       {
           "id": 851,
           "identifier": "10:00:50:EB:1A:40:3B:44",
           "wwn": "10:00:50:EB:1A:40:3B:44",
           "name": "10:00:50:EB:1A:40:3B:44",
           "vsanEnabled": "0",
           "vsanId": null,
           "zoningEnabled": "0",
           "url": "https://<domain>/web/#/assets/fabrics/941716"
       },
       {
           "id": 852,
           "identifier": "10:00:50:EB:1A:40:44:0C",
           "wwn": "10:00:50:EB:1A:40:44:0C",
           "name": "10:00:50:EB:1A:40:44:0C",
           "vsanEnabled": "0",
           "vsanId": null,
           "zoningEnabled": "0",
           "url": "https://<domain>/web/#/assets/fabrics/941836"
        }
    ]
}
....


== Conseils utiles

Gardez les points suivants à l’esprit lorsque vous travaillez avec des requêtes d’API de création de rapports.

* La charge utile de la requête doit être une chaîne JSON valide
* La charge utile de la requête doit être contenue dans une seule ligne
* Les guillemets doubles doivent être échappés, c'est-à-dire \"
* Les onglets sont pris en charge en tant que \t
* Évitez les commentaires
* Les noms de table en minuscules sont pris en charge


En plus:

* 2 en-têtes sont requis :
+
** Nom « X-CloudInsights-ApiKey »
** Valeur d'attribut « <apikey> »




Votre clé API sera spécifique à votre environnement Data Infrastructure Insights .



== Synchrone ou asynchrone ?

Par défaut, une commande API fonctionnera en mode _synchrone_, ce qui signifie que vous envoyez la requête et la réponse est renvoyée immédiatement.  Cependant, il arrive parfois qu'une requête prenne beaucoup de temps à s'exécuter, ce qui peut entraîner l'expiration de la requête.  Pour contourner ce problème, vous pouvez exécuter une requête de manière _asynchrone_.  En mode asynchrone, la requête renverra une URL via laquelle l'exécution pourra être surveillée.  L'URL renverra le résultat lorsqu'il sera prêt.

Pour exécuter une requête en mode asynchrone, ajoutez l'en-tête `*Prefer: respond-async*` à la demande.  Une fois l'exécution réussie, la réponse contiendra les en-têtes suivants :

....
Status Code: 202 (which means ACCEPTED)
preference-applied: respond-async
location: https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/asyncStatus/<token>
....
L'interrogation de l'URL d'emplacement renverra les mêmes en-têtes si la réponse n'est pas encore prête, ou renverra le statut 200 si la réponse est prête.  Le contenu de la réponse sera de type texte et contiendra l'état http de la requête d'origine et certaines métadonnées, suivis des résultats de la requête d'origine.

....
HTTP/1.1 200 OK
 OData-Version: 4.0
 Content-Type: application/json;odata.metadata=minimal
 oDataResponseSizeCounted: true

 { <JSON_RESPONSE> }
....
Pour voir une liste de toutes les requêtes asynchrones et lesquelles d’entre elles sont prêtes, utilisez la commande suivante :

 GET https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/asyncList
La réponse a le format suivant :

....
{
   "queries" : [
       {
           "Query": "https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/heavy_left_join3?$count=true",
           "Location": "https://<Data Infrastructure Insights URL>/rest/v1/dwh-management/odata/dwh_custom/asyncStatus/<token>",
           "Finished": false
       }
   ]
}
....