---
sidebar: sidebar 
permalink: task_dc_brocade_bna.html 
keywords: data collector, Brocade, BNA 
summary: Configuration du collecteur Brocade BNA. 
---
= Collecteur de données Brocade Network Advisor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise le collecteur de données Brocade Network Advisor pour acquérir des données d'inventaire et de performances à partir des commutateurs Brocade .



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données Brocade Network Advisor.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Changer | Changer 


| Port | Port 


| Tissu virtuel, tissu physique | Tissu 


| Commutateur logique | Commutateur logique 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

Les éléments suivants sont requis pour configurer ce collecteur de données :

* L'unité d'acquisition Data Infrastructure Insights initiera des connexions au port TCP 443 sur le serveur BNA.  Le serveur BNA doit exécuter la version 14.2.1 ou supérieure.
* Adresse IP du serveur Brocade Network Advisor
* Nom d'utilisateur et mot de passe d'un compte administrateur
* Exigence de port : HTTP/HTTPS 443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP du serveur Brocade Network Advisor | Adresse IP du serveur Network Advisor 


| Nom d'utilisateur | Nom d'utilisateur pour le commutateur 


| Nom d'utilisateur | Nom d'utilisateur administrateur 


| Mot de passe | Mot de passe administrateur 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Type de connexion | HTTPS (port par défaut 443) ou HTTP (port par défaut 80) 


| Remplacer le port de connexion | Si vide, utilisez le port par défaut dans le champ Type de connexion, sinon entrez le port de connexion à utiliser 


| Mot de passe | Mot de passe pour le commutateur 


| Intervalle d'interrogation de l'inventaire (min) | La valeur par défaut est 40 


| Rapport sur la passerelle d'accès | Cochez cette case pour inclure les appareils en mode passerelle d'accès 


| Intervalle d'interrogation des performances (sec) | La valeur par défaut est 1800 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Recevez un message indiquant que plusieurs nœuds sont connectés au port Access Gateway ou que le collecteur de données ne parvient pas à détecter le périphérique Access Gateway. | Vérifiez que le périphérique NPV fonctionne correctement et que tous les WWN connectés sont attendus.  N'acquérez pas directement le dispositif NPV.  Au lieu de cela, l’acquisition du commutateur de structure principal collectera les données du périphérique NPV. 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
