---
sidebar: sidebar 
permalink: task_cs_add_collector_ontap.html 
keywords: data collector, ONTAP, SVM 
summary: Ajout de collecteurs de données 
---
= Configuration du collecteur de données NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
La sécurité de la charge de travail utilise des collecteurs de données pour collecter les données d'accès des fichiers et des utilisateurs à partir de terminaux. Les données sont fournies à la charge de travail Security à des fins d'analyse.

.Avant de commencer
Vous avez besoin des informations suivantes pour configurer ce collecteur de données :

* Un agent doit être configuré pour collecter des données
* Adresse IP de gestion SVM
* Un nom d'utilisateur pour accéder au SVM
* Mot de passe pour accéder à la SVM


.Étapes de configuration
. Connectez-vous en tant qu'administrateur ou responsable de compte à votre environnement de sécurité de la charge de travail.
. Cliquez sur *observabilité > Collectors > +Data Collectors*
+
Le système affiche les collecteurs de données disponibles.

. Cliquez sur *+surveillance* dans la vignette NetApp ONTAP.
+
Le système affiche la page de configuration Add Data Collector : ONTAP SVM.

. Entrez un nom unique pour le collecteur
. Sélectionnez l'agent qui va collecter les données
. Entrer l'adresse IP de gestion SVM
. Entrer le nom d'utilisateur pour accéder au SVM
. Entrer le mot de passe pour accéder à la SVM
. Cliquez sur *+Ajouter un collecteur*


.Une fois que vous avez terminé
* Cliquez sur *Workload Security > Collectors* pour vérifier l'état du collecteur que vous avez configuré.
+
Il y a normalement un délai avant l'affichage de l'état du collecteur.


