---
sidebar: sidebar 
permalink: task_view_queries.html 
summary: 'Consultez et gérez vos requêtes enregistrées grâce à des options d"affichage personnalisables, notamment le filtrage, le tri et l"agencement des colonnes, pour une organisation et un accès efficaces aux requêtes.' 
keywords: query, queries, viewing 
---
= Consultation des requêtes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Accédez à vos requêtes enregistrées et gérez-les via l'interface de requêtes, où vous pouvez filtrer, trier et personnaliser l'affichage pour organiser et localiser efficacement les requêtes dont vous avez besoin pour la surveillance et l'analyse des actifs.

.Étapes
. Connectez-vous à votre locataire Data Infrastructure Insights .
. Cliquez sur *Explorer* et sélectionnez *All metric queries*. Vous pouvez modifier l'affichage des requêtes en procédant comme suit :
. Vous pouvez saisir du texte dans la zone de filtre pour rechercher et afficher des requêtes spécifiques.
. Vous pouvez modifier l'ordre de tri des colonnes dans le tableau des requêtes en ordre croissant (flèche vers le haut) ou décroissant (flèche vers le bas) en cliquant sur la flèche dans l'en-tête de la colonne.
. Pour redimensionner une colonne, passez la souris sur l'en-tête de la colonne jusqu'à ce qu'une barre bleue apparaisse.  Placez la souris sur la barre et faites-la glisser vers la droite ou vers la gauche.
. Pour déplacer une colonne, cliquez sur l'en-tête de la colonne et faites-le glisser vers la droite ou vers la gauche.


Lorsque vous faites défiler les résultats de la requête, sachez que les résultats peuvent changer à mesure que Data Infrastructure Insights interroge automatiquement vos collecteurs de données.  Cela peut entraîner l'absence de certains éléments ou l'affichage de certains éléments dans le désordre, selon la façon dont ils sont triés.
