---
sidebar: sidebar 
permalink: task_dc_ms_azure.html 
keywords: data collector, azure, 
summary: Configuration du collecteur de données de calcul Azure 
---
= Configuration du collecteur de données de calcul Azure
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise le collecteur de données de calcul Azure pour acquérir des données d'inventaire et de performance à partir des instances de calcul Azure.



== De formation

Vous avez besoin des informations suivantes pour configurer ce collecteur de données.

* Port requis : 443 HTTPS
* URI de redirection Azure OAuth 2.0 (login.microsoftonline.com)
* IP REST Azure Management (management.azure.com)
* IP Azure Resource Manager (management.core.windows.net)
* Identifiant d'application principale (client) du service Azure (rôle du lecteur requis)
* Clé d'authentification principale du service Azure (mot de passe utilisateur)
* Vous devez configurer un compte Azure pour la découverte Data Infrastructure Insights.
+
Une fois le compte correctement configuré et que vous enregistrez l'application dans Azure, vous disposez des identifiants requis pour découvrir l'instance Azure avec Data Infrastructure Insights. Le lien suivant explique comment configurer le compte pour la découverte. https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]





== Configuration

Entrez les données dans les champs du collecteur de données conformément au tableau ci-dessous :

[cols="2*"]
|===
| Champ | Description 


| Identifiant d'application principale (client) du service Azure (rôle du lecteur requis) | ID de connexion à Azure. Nécessite un accès au rôle Reader. 


| ID locataire Azure | ID locataire Microsoft 


| Clé d'authentification principale du service Azure | Clé d'authentification de connexion 


| J'ai bien compris que Microsoft me facture pour les demandes d'API | Vérifiez que vous avez bien compris que Microsoft vous facture des demandes d'API formulées par l'interrogation Insight. 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation des stocks (min) | La valeur par défaut est 60 


| Choisissez exclure ou inclure pour appliquer le filtrage des VM par balises | Indiquez s'il faut inclure ou exclure des VM par des étiquettes lors de la collecte de données. Si l'option "inclure" est sélectionnée, le champ clé d'étiquette ne peut pas être vide. 


| Clés de balise et valeurs sur lesquelles filtrer les machines virtuelles | Cliquez sur *+ Filter Tag* pour choisir les VM (et les disques associés) à inclure/exclure en filtrant les clés et les valeurs qui correspondent aux clés et aux valeurs des balises de la VM. La clé d'étiquette est requise, la valeur d'étiquette est facultative. Lorsque la valeur de balise est vide, la machine virtuelle est filtrée tant qu'elle correspond à la clé de balise. 


| Intervalle d'interrogation des performances (s) | La valeur par défaut est 300 
|===


== Dépannage

Vous trouverez des informations supplémentaires sur ce Data Collector sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
