---
sidebar: sidebar 
permalink: task_dc_hds_hcp.html 
keywords: data collector, Hitachi HDS, HCP 
summary: Configuration du collecteur de données HDS. 
---
= Collecteur de données Hitachi HCP
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Ce collecteur de données prend en charge Hitachi Content Platform (HCP) à l'aide de l'API de gestion HCP.


NOTE: Hitachi Content Platform est mesuré à un taux différent du To brut au taux d'unité gérée.  Chaque 40 To de capacité HCP non formatée est facturé 1link:concept_subscribing_to_cloud_insights.html#pricing["Unité gérée (UG)"] .



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données Hitachi HCP.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Cluster HCP | Stockage 


| Locataire | Piscine de stockage 


|  | Espace de noms 


| Volume interne | Nœud 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences en matière d'inventaire

Vous devez disposer des éléments suivants pour collecter des données d’inventaire :

* Adresse IP du serveur HCP
* Nom d'utilisateur et mot de passe en lecture seule pour le logiciel HCP et les privilèges des pairs




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Hôte HCP | Adresse IP ou nom de domaine complet de l'hôte HCP 


| Port HCP | La valeur par défaut est 9090 


| ID utilisateur HCP | Nom d'utilisateur pour l'hôte HCP. 


| Mot de passe HCP | Mot de passe utilisé pour l'hôte HCP. 


| Type d'authentification HCP | Choisissez HCP_LOCAL ou ACTIVE_DIRECTORY 
|===


== Configuration avancée

|===


| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire.  La valeur par défaut est 60. 


| Intervalle d'interrogation des performances (sec) | Intervalle entre les sondages de performance.  La valeur par défaut est 900. 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
