---
sidebar: sidebar 
permalink: task_device_resolution_preferences.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution, FC, Identify 
summary:  
---
= Options de paramétrage dans l'onglet Préférences
:hardbreaks:
:allow-uri-read: 


[role="lead"]
L'onglet des préférences de résolution de périphérique vous permet de créer une planification de résolution automatique, de spécifier les fournisseurs de stockage et de bande à inclure ou à exclure de l'identification et de définir les options de recherche DNS.



== Planification de résolution automatique

Un programme de résolution automatique peut spécifier quand la résolution automatique du périphérique est exécutée :

|===


| Option | Description 


| Chaque | Utilisez cette option pour exécuter la résolution automatique du périphérique à des intervalles de jours, d'heures ou de minutes. 


| Tous les jours | Utilisez cette option pour exécuter la résolution automatique de l'appareil quotidiennement à une heure précise. 


| Manuellement | Utilisez cette option pour exécuter uniquement la résolution automatique du périphérique manuellement. 


| À chaque changement d'environnement | Utilisez cette option pour exécuter la résolution automatique du périphérique chaque fois qu'un changement se produit dans l'environnement. 
|===
Si vous spécifiez _Manuellement_, la résolution automatique nocturne du périphérique est désactivée.



== Options de traitement DNS

Les options de traitement DNS vous permettent de sélectionner les fonctionnalités suivantes :

* Lorsque le traitement des résultats de recherche DNS est activé, vous pouvez ajouter une liste de noms DNS à ajouter aux périphériques résolus.
* Vous pouvez sélectionner Résolution automatique des IP : pour activer la résolution automatique de l'hôte pour les initiateurs iSCSI et les hôtes accédant aux partages NFS à l'aide de la recherche DNS.  Si cela n'est pas spécifié, seule la résolution basée sur FC est effectuée.
* Vous pouvez choisir d'autoriser les traits de soulignement dans les noms d'hôtes et d'utiliser un alias « connecté à » au lieu de l'alias de port standard dans les résultats.




=== Inclure ou exclure des fournisseurs spécifiques de stockage et de bandes

Vous pouvez inclure ou exclure des fournisseurs de stockage et de bande spécifiques pour une résolution automatique.  Vous souhaiterez peut-être exclure des fournisseurs spécifiques si vous savez, par exemple, qu'un hôte spécifique deviendra un hôte hérité et devra être exclu de votre nouvel environnement.  Vous pouvez également rajouter des fournisseurs que vous avez précédemment exclus mais que vous ne souhaitez plus exclure.


NOTE: Les règles de résolution de périphérique pour la bande fonctionnent uniquement pour les WWN où le fournisseur de ce WWN est défini sur _Inclus en tant que bande uniquement_ dans les préférences des fournisseurs.

Voir aussi :link:concept_device_resolution_regex_examples.html["Exemples d'expressions régulières"]
