---
sidebar: sidebar 
permalink: task_dc_emc_vnxe.html 
keywords: data collector, VNXe, EMC 
summary: Configuration du collecteur de données VNXe. 
---
= Configuration du collecteur de données EMC VNXe
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le collecteur de données DELL EMC VNXe fournit une prise en charge de l'inventaire pour les baies de stockage unifiées VNXe.  Data Infrastructure Insights prend actuellement en charge les protocoles iSCSI et NAS.



== Exigences

* Le collecteur de données VNXe est basé sur CLI ; vous devez installer Unisphere pour VNXe CLI (uemcli.exe) sur l'unité d'acquisition où réside votre collecteur de données VNXe.
* uemcli.exe utilise HTTPS comme protocole de transport, l'unité d'acquisition devra donc pouvoir initier des connexions HTTPS au VNXe.
* Adresse IP ou nom de domaine complet de l'appareil VNXe
* Vous devez disposer d'au moins un utilisateur en lecture seule pour pouvoir utiliser le collecteur de données.
* Adresse IP du serveur d'activation des solutions de gestion.
* HTTPS sur le port 443 est requis
* Le collecteur de données EMC VNXe fournit une prise en charge NAS et iSCSI pour l'inventaire ; les volumes Fibre Channel seront découverts, mais Data Infrastructure Insights ne génère pas de rapport sur le mappage FC, le masquage ou les ports de stockage.




== Terminologie

Data Infrastructure Insights acquiert les informations d’inventaire suivantes auprès du collecteur de données VNXe.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque | Disque 


| Baie de stockage | Stockage 


| Processeur | Nœud de stockage 


| Piscine de stockage | Piscine de stockage 


| Informations générales sur les blocs iSCSI, VMware VMFS | Partager 


| Système de réplication à distance | Synchronisation 


| Nœud iSCSI | Nœud cible iSCSI 


| Initiateur iSCSI | Initiateur cible iSCSI 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour cette source de données.



== Configuration

[cols="2*"]
|===
| Champ | Description 


| Stockage VNXe | Adresse IP ou nom de domaine complet de l'appareil VNXe 


| Nom d'utilisateur | Nom d'utilisateur pour le périphérique VNXe 


| Mot de passe | Mot de passe pour l'appareil VNXe 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire.  La valeur par défaut est de 40 minutes 


| Port CLI | Port utilisé pour la CLI VNXe 


| Intervalle d'interrogation des performances (sec) | La valeur par défaut est 300. 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| « Échec de l'exécution de l'utilitaire externe » avec le message d'erreur « Impossible de trouver l'exécutable Unisphere uemcli » | * Vérifiez l'adresse IP, le nom d'utilisateur et le mot de passe corrects. * Confirmez que Unisphere CLI est installé sur l'unité d'acquisition Data Infrastructure Insights. * Confirmez que le répertoire d'installation d'Unisphere CLI est correct dans la configuration de la source de données. * Confirmez que l'adresse IP du VNXe est correcte dans la configuration de la source de données.  À partir de l'unité d'acquisition Data Infrastructure Insights , ouvrez un CMD et accédez au répertoire d'installation configuré : ${INSTALLDIR.  Essayez d'établir une connexion avec le périphérique VNXe en tapant : uemcli -d <Votre IP> -u <Votre ID> /sys/general show 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
