---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: Collecteur de données IBM TotalStorage DS4000 
---
= Collecteur de données IBM TotalStorage DS4000
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Ce collecteur de données acquiert les informations d'inventaire et de performances du système de stockage IBM DS4000. Il existe deux configurations possibles (firmware 6.x et firmware 7.x+), et elles ont toutes les deux les mêmes valeurs.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes à partir du collecteur de données IBM DS4000. Pour chaque type d'actif acquis, la terminologie la plus utilisée pour ce bien est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme informations exploitables sur l'infrastructure de données 


| Disque | Disque 


| Groupe de volumes | Groupe de disques 


| Baie de stockage | Stockage 


| Contrôleur | Nœud de stockage 


| Groupe de volumes | Pool de stockage 


| Volumétrie | Volumétrie 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

* Adresse IP de chaque baie DS5 ou FAStT
* Validation des accès en envoyant une commande ping à l'adresse IP des deux contrôleurs de la baie
* Exigences relatives aux ports : 2463




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Liste des adresses IP de contrôleur de matrice SANtricity séparées par une virgule | Adresses IP et/ou noms de domaine complets pour les contrôleurs de matrice 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation des stocks (min) | La valeur par défaut est 30 minutes 


| Intervalle d'interrogation des performances jusqu'à 3600 secondes | La valeur par défaut est 300 secondes 
|===


== Dépannage

Vous trouverez des informations supplémentaires sur ce Data Collector sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
