---
sidebar: sidebar 
permalink: task_dc_dell_xc_series.html 
keywords: data collector, Dell, EMC, xc 
summary: Configuration du collecteur de données Dell EMC série XC. 
---
= Collecteur de données Dell EMC série XC
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise ce collecteur de données pour découvrir les informations d’inventaire et de performances des baies de stockage Dell EMC série XC.



== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP externe de Prism | Adresse IP du serveur XC 


| Nom d'utilisateur | Nom d'utilisateur pour le serveur XC 


| Mot de passe | Mot de passe utilisé pour le serveur XC 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port utilisé pour la communication TCP avec le serveur XC 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 60 minutes. 


| Intervalle de sondage des performances (min) | Intervalle entre les sondages de performance. La valeur par défaut est de 300 secondes. 
|===


== Dépannage

Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
