---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: Configuration du collecteur de données IBM Cleversafe. 
---
= Collecteur de données IBM Cleversafe
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Data Infrastructure Insights utilise ce collecteur de données pour détecter les données d'inventaire et de performance des systèmes de stockage IBM Cleversafe.


NOTE: IBM Cleversafe est mesuré à un taux de TB brut différent de celui de l'unité gérée. Chaque 40 To de capacité non formatée IBM Cleversafe est chargée comme 1 link:concept_subscribing_to_cloud_insights.html#pricing["Unité gérée (UM)"].



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes à partir du collecteur de données IBM Cleversafe. Pour chaque type de ressource acquis par Data Infrastructure Insights, la terminologie la plus courante est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme informations exploitables sur l'infrastructure de données 


| Pool de stockage | Pool de stockage 


| Conteneur | Volume interne 


| Conteneur | Partage de fichiers 


| Partage NFS | Partagez 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

* L'adresse IP des services de données externes pour le cluster
* Nom d'utilisateur et mot de passe administrateur
* Orifice 9440




== Configuration

[cols="2*"]
|===
| Champ | Description 


| IP Manager ou nom d'hôte | Adresse IP ou nom d'hôte du nœud de gestion 


| Nom d'utilisateur | Nom d'utilisateur du compte utilisateur avec le rôle super utilisateur ou administrateur système 


| Mot de passe | Mot de passe du compte utilisateur avec le rôle super utilisateur ou administrateur système 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation des stocks (min) | Intervalle entre les sondages d'inventaire. 


| Délai d'expiration de la connexion HTTP (sec) | Délai d'attente HTTP en secondes. 
|===


== Dépannage

Vous trouverez des informations supplémentaires sur ce Data Collector sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
