---
sidebar: sidebar 
permalink: task_dc_hds_commandsuite.html 
keywords: data collector, Hitachi Vantara Command Suite, Hitachi 
summary: Configuration du collecteur de données du gestionnaire de périphériques HDS Command Suite. 
---
= Collecteur de données Hitachi Vantara Command Suite
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le collecteur de données Hitachi Vantara Command Suite prend en charge le serveur HiCommand Device Manager.  Data Infrastructure Insights communique avec le serveur HiCommand Device Manager à l'aide de l'API HiCommand standard.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes à partir du collecteur de données Hitachi Vantara Command Suite.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| PDEV | Disque 


| Journal Pool | Groupe de disques 


| Baie de stockage | Stockage 


| Contrôleur de port | Nœud de stockage 


| Groupe de matrices, pool HDS | Piscine de stockage 


| Unité logique, LDEV | Volume 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



=== Stockage

Les conditions suivantes s'appliquent aux objets ou références que vous pourriez trouver sur les pages de destination des ressources de stockage HDS.  Bon nombre de ces termes s’appliquent également à d’autres collecteurs de données.

* Nom – provient directement de l'attribut « nom » du gestionnaire de périphériques HDS HiCommand via l'appel d'API XML GetStorageArray
* Modèle - provient directement de l'attribut « arrayType » du gestionnaire de périphériques HDS HiCommand via l'appel d'API XML GetStorageArray
* Fournisseur – HDS
* Famille - provient directement de l'attribut « arrayFamily » du gestionnaire de périphériques HDS HiCommand via l'appel d'API XML GetStorageArray
* IP – il s’agit de l’adresse IP de gestion de la baie, et non d’une liste exhaustive de toutes les adresses IP de la baie
* Capacité brute – une valeur de base 2 représentant la somme de la capacité totale de tous les disques de ce système, quel que soit le rôle du disque.




=== Piscine de stockage

Les termes suivants s'appliquent aux objets ou références que vous pourriez trouver sur les pages de destination des ressources du pool de stockage HDS.  Bon nombre de ces termes s’appliquent également à d’autres collecteurs de données.

* Type : La valeur ici sera l’une des suivantes :
+
** RÉSERVÉ – si ce pool est dédié à des fins autres que les volumes de données, c'est-à-dire la journalisation, les instantanés
** Provisionnement léger – s'il s'agit d'un pool HDP
** Groupe de raid – vous ne les verrez probablement pas pour plusieurs raisons :
+
Data Infrastructure Insights adopte une position ferme pour éviter à tout prix le double comptage des capacités.  Sur HDS, il faut généralement créer des groupes Raid à partir de disques, créer des volumes de pool sur ces groupes Raid et construire des pools (souvent HDP, mais qui peuvent être à usage spécial) à partir de ces volumes de pool.  Si Data Infrastructure Insights signalait à la fois les groupes Raid sous-jacents tels quels, ainsi que les pools, la somme de leur capacité brute dépasserait largement la somme des disques.

+
Au lieu de cela, le collecteur de données HDS Command Suite de Data Infrastructure Insights réduit arbitrairement la taille des groupes Raid en fonction de la capacité des volumes de pool.  Cela peut entraîner le fait que Data Infrastructure Insights ne signale pas du tout le groupe Raid.  De plus, tous les groupes de raid résultants sont signalés de manière à ne pas être visibles dans l'interface Web de Data Infrastructure Insights , mais ils sont transférés dans l'entrepôt de données de Data Infrastructure Insights (DWH).  Le but de ces décisions est d'éviter l'encombrement de l'interface utilisateur pour des éléments qui ne s'intéressent pas à la plupart des utilisateurs. Si votre baie HDS dispose de groupes Raid avec 50 Mo d'espace libre, vous ne pouvez probablement pas utiliser cet espace libre pour obtenir un résultat significatif.



* Nœud - N/A, car les pools HDS ne sont liés à aucun nœud spécifique
* Redondance - le niveau RAID du pool.  Plusieurs valeurs possibles pour un pool HDP composé de plusieurs types RAID
* Capacité % - le pourcentage utilisé du pool pour l'utilisation des données, avec les Go utilisés et la taille totale en Go logiques du pool
* Capacité surengagée - une valeur dérivée, indiquant que « la capacité logique de ce pool est sursouscrite de ce pourcentage en raison de la somme des volumes logiques dépassant la capacité logique du pool de ce pourcentage »
* Instantané - affiche la capacité réservée à l'utilisation des instantanés sur ce pool




=== Nœud de stockage

Les conditions suivantes s'appliquent aux objets ou références que vous pourriez trouver sur les pages de destination des ressources des nœuds de stockage HDS.  Bon nombre de ces termes s’appliquent également à d’autres collecteurs de données.

* Nom – Le nom du directeur frontal (FED) ou de l’adaptateur de canal sur les baies monolithiques, ou le nom du contrôleur sur une baie modulaire.  Une baie HDS donnée aura 2 nœuds de stockage ou plus
* Volumes – Le tableau des volumes affichera tout volume mappé à n’importe quel port appartenant à ce nœud de stockage




== Exigences en matière d'inventaire

Vous devez disposer des éléments suivants pour collecter des données d’inventaire :

* Adresse IP du serveur HiCommand Device Manager
* Nom d'utilisateur et mot de passe en lecture seule pour le logiciel HiCommand Device Manager et privilèges homologues
* Exigences de port : 2001 (http) ou 2443 (https)
* Connectez-vous au logiciel HiCommand Device Manager à l'aide du nom d'utilisateur et du mot de passe
* Vérifier l'accès à HiCommand Device Manager \http://<HiCommand_Device_Manager_IP>:2001/service/StorageManager




== Exigences de performance

Les exigences suivantes doivent être respectées pour collecter des données de performance :

* Performances HDS USP, USP V et VSP
+
** Performance Monitor doit être sous licence.
** Le commutateur de surveillance doit être activé.
** L'outil d'exportation (Export.exe) doit être copié dans l'AU Data Infrastructure Insights .
** La version de l’outil d’exportation doit correspondre à la version du microcode du tableau cible.


* Performances AMS :
+
** NetApp recommande fortement de créer un compte de service dédié sur les baies AMS pour que Data Infrastructure Insights puisse l'utiliser pour récupérer les données de performances.  Storage Navigator n'autorise qu'une seule connexion simultanée à un compte utilisateur sur la baie.  Le fait que Data Infrastructure Insights utilise le même compte utilisateur que les scripts de gestion ou HiCommand peut empêcher Data Infrastructure Insights, les scripts de gestion ou HiCommand de communiquer avec la baie en raison de la limite de connexion d'un seul compte utilisateur simultané.
** Performance Monitor doit être sous licence.
** L'utilitaire CLI Storage Navigator Modular 2 (SNM2) doit être installé sur l'AU Data Infrastructure Insights .






== Configuration

[cols="2*"]
|===
| Champ | Description 


| Serveur HiCommand | Adresse IP ou nom de domaine complet du serveur HiCommand Device Manager 


| Nom d'utilisateur | Nom d'utilisateur pour le serveur HiCommand Device Manager. 


| Mot de passe | Mot de passe utilisé pour le serveur HiCommand Device Manager. 


| Appareils - Stockages VSP G1000 (R800), VSP (R700), HUS VM (HM700) et USP | Liste des périphériques pour les stockages VSP G1000 (R800), VSP (R700), HUS VM (HM700) et USP.  Chaque stockage nécessite : * IP de la baie : adresse IP du stockage * Nom d'utilisateur : nom d'utilisateur pour le stockage * Mot de passe : mot de passe pour le stockage * Dossier contenant les fichiers JAR de l'utilitaire d'exportation 


| SNM2Devices - Stockages WMS/SMS/AMS | Liste des périphériques pour les stockages WMS/SMS/AMS.  Chaque stockage nécessite : * IP de la baie : adresse IP du stockage * Chemin d'accès CLI du navigateur de stockage : chemin d'accès CLI SNM2 * Authentification de compte valide : sélectionnez cette option pour choisir une authentification de compte valide * Nom d'utilisateur : nom d'utilisateur pour le stockage * Mot de passe : mot de passe pour le stockage 


| Choisissez Tuning Manager pour les performances | Remplacer les autres options de performances 


| Gestionnaire de réglage hôte | Adresse IP ou nom de domaine complet du gestionnaire de réglage 


| Remplacer le port du gestionnaire de réglage | Si vide, utilisez le port par défaut dans le champ Choisir le gestionnaire de réglage pour les performances, sinon entrez le port à utiliser 


| Nom d'utilisateur du gestionnaire de réglages | Nom d'utilisateur pour Tuning Manager 


| Mot de passe du gestionnaire de réglages | Mot de passe pour Tuning Manager 
|===
Remarque : dans HDS USP, USP V et VSP, n’importe quel disque peut appartenir à plusieurs groupes de baies.



== Configuration avancée

|===


| Champ | Description 


| Type de connexion | HTTPS ou HTTP, affiche également le port par défaut 


| Port du serveur HiCommand | Port utilisé pour le gestionnaire de périphériques HiCommand 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire.  La valeur par défaut est 40. 


| Choisissez « Exclure » ou « Inclure » pour spécifier une liste | Indiquez si vous souhaitez inclure ou exclure la liste de tableaux ci-dessous lors de la collecte de données. 


| Liste des appareils de filtrage | Liste séparée par des virgules des numéros de série des appareils à inclure ou à exclure 


| Intervalle d'interrogation des performances (sec) | Intervalle entre les sondages de performance.  La valeur par défaut est 300. 


| Délai d'expiration de l'exportation en secondes | Délai d'expiration de l'utilitaire d'exportation.  La valeur par défaut est 300. 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Erreur : l'utilisateur ne dispose pas de suffisamment d'autorisations | Utilisez un autre compte d'utilisateur disposant de plus de privilèges ou augmentez les privilèges du compte d'utilisateur configuré dans le collecteur de données 


| Erreur : la liste des stockages est vide.  Soit les appareils ne sont pas configurés, soit l'utilisateur ne dispose pas des autorisations suffisantes | * Utilisez DeviceManager pour vérifier si les périphériques sont configurés.  * Utilisez un autre compte utilisateur disposant de plus de privilèges ou augmentez les privilèges du compte utilisateur 


| Erreur : la matrice de stockage HDS n'a pas été actualisée pendant quelques jours | Recherchez pourquoi ce tableau n’est pas actualisé dans HDS HiCommand. 
|===


=== Performances

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Erreur : * Erreur lors de l'exécution de l'utilitaire d'exportation * Erreur lors de l'exécution de la commande externe | * Confirmez que l'utilitaire d'exportation est installé sur l'unité d'acquisition Data Infrastructure Insights * Confirmez que l'emplacement de l'utilitaire d'exportation est correct dans la configuration du collecteur de données * Confirmez que l'adresse IP de la baie USP/R600 est correcte dans la configuration du collecteur de données * Confirmez que le nom d'utilisateur et le mot de passe sont corrects dans la configuration du collecteur de données * Confirmez que la version de l'utilitaire d'exportation est compatible avec la version du microcode de la baie de stockage * À partir de l'unité d'acquisition Data Infrastructure Insights , ouvrez une invite de commande et procédez comme suit : - Modifiez le répertoire vers le répertoire d'installation configuré - Essayez d'établir une connexion avec la baie de stockage configurée en exécutant le fichier de commandes runWin.bat 


| Erreur : la connexion à l'outil d'exportation a échoué pour l'adresse IP cible | * Confirmer que le nom d'utilisateur/mot de passe est correct * Créer un identifiant utilisateur principalement pour ce collecteur de données HDS * Confirmer qu'aucun autre collecteur de données n'est configuré pour acquérir ce tableau 


| Erreur : les outils d'exportation ont enregistré « Impossible d'obtenir la plage horaire pour la surveillance ». | * Confirmez que la surveillance des performances est activée sur la baie.  * Essayez d'appeler les outils d'exportation en dehors de Data Infrastructure Insights pour confirmer que le problème se situe en dehors de Data Infrastructure Insights. 


| Erreur : * Erreur de configuration : la baie de stockage n'est pas prise en charge par l'utilitaire d'exportation * Erreur de configuration : la baie de stockage n'est pas prise en charge par l'interface de ligne de commande modulaire Storage Navigator | * Configurez uniquement les baies de stockage prises en charge.  * Utilisez « Filtrer la liste des périphériques » pour exclure les baies de stockage non prises en charge. 


| Erreur : * Erreur lors de l'exécution de la commande externe * Erreur de configuration : la baie de stockage n'est pas signalée par l'inventaire * Erreur de configuration : le dossier d'exportation ne contient pas de fichiers JAR | * Vérifiez l’emplacement de l’utilitaire d’exportation.  * Vérifiez si la baie de stockage en question est configurée sur le serveur HiCommand. * Définissez l'intervalle d'interrogation des performances comme un multiple de 60 secondes. 


| Erreur : * Erreur du navigateur de stockage CLI * Erreur lors de l'exécution de la commande auperform * Erreur lors de l'exécution de la commande externe | * Confirmez que l'interface de ligne de commande modulaire Storage Navigator est installée sur l'unité d'acquisition Data Infrastructure Insights. * Confirmez que l'emplacement de l'interface de ligne de commande modulaire Storage Navigator est correct dans la configuration du collecteur de données. * Confirmez que l'adresse IP de la baie WMS/SMS/SMS est correcte dans la configuration du collecteur de données. * Confirmez que la version de l'interface de ligne de commande modulaire Storage Navigator est compatible avec la version du microcode de la baie de stockage configurée dans le collecteur de données. * Depuis l'unité d'acquisition Data Infrastructure Insights , ouvrez une invite de commande et procédez comme suit : - Modifiez le répertoire vers le répertoire d'installation configuré. - Essayez d'établir une connexion avec la baie de stockage configurée en exécutant la commande suivante : « auunitref.exe ». 


| Erreur : Erreur de configuration : la baie de stockage n'est pas signalée par l'inventaire | Vérifiez si la baie de stockage en question est configurée sur le serveur HiCommand 


| Erreur : * Aucune baie n'est enregistrée avec l'interface de ligne de commande Storage Navigator Modular 2 * La baie n'est pas enregistrée avec l'interface de ligne de commande Storage Navigator Modular 2 * Erreur de configuration : Baie de stockage non enregistrée avec l'interface de ligne de commande StorageNavigator Modular | * Ouvrez l'invite de commande et changez de répertoire pour le chemin configuré * Exécutez la commande « set=STONAVM_HOME=. »  * Exécutez la commande « auunitref » * Confirmez que la sortie de la commande contient les détails de la baie avec l'IP * Si la sortie ne contient pas les détails de la baie, enregistrez la baie avec Storage Navigator CLI : - Ouvrez l'invite de commande et changez de répertoire pour le chemin configuré - Exécutez la commande « set=STONAVM_HOME=. »  - Exécutez la commande « auunitaddauto -ip <ip> ».  Remplacez <ip> par l'IP correcte. 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
