---
sidebar: sidebar 
permalink: task_identify_inactive_devices.html 
keywords: inactive, device, remove, removing, identify, identifying 
summary: L’identification des appareils inactifs vous permet de choisir de les supprimer ou de les attribuer à un rôle actif. 
---
= Identifier les appareils inactifs
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Identifier les actifs dont vous disposez et qui les utilise est essentiel pour « ajuster la taille » et libérer l’infrastructure inutilisée.  Vous pouvez facilement réaffecter ou désactiver les ressources sous-utilisées et éviter les achats inutiles.

Utilisez les étapes suivantes pour identifier les actifs inactifs.

.Étapes
* Accédez à *Observabilité > Explorer -> +Nouvelle requête de métrique*.
* Sélectionnez _Stockage_ dans la liste déroulante.
* Cliquez sur l’engrenage et ajoutez _isActive_ comme colonne.
+
Les lignes affichant une coche sont actives.  « X » indique les appareils inactifs.



Pour supprimer les appareils inactifs, sélectionnez simplement les appareils à supprimer et dans la liste déroulante *Actions en masse*, sélectionnez _Supprimer les appareils inactifs_.
