---
sidebar: sidebar 
permalink: task_cs_user_management.html 
keywords: Workload Security, User, Login, account, cloud secure 
summary: Sécurité de la charge de travail Les comptes utilisateurs sont gérés via la gestion des utilisateurs de Data Infrastructure Insights 
---
= Gestion des utilisateurs
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Les comptes d’utilisateurs de Workload Security sont gérés via Data Infrastructure Insights.

Data Infrastructure Insights propose quatre niveaux de compte utilisateur : propriétaire du compte, administrateur, utilisateur et invité.  À chaque compte sont attribués des niveaux d’autorisation spécifiques.  Un compte utilisateur disposant de privilèges d'administrateur peut créer ou modifier des utilisateurs et attribuer à chaque utilisateur l'un des rôles de sécurité de la charge de travail suivants :

|===


| Rôle | Accès à la sécurité de la charge de travail 


| Administrateur | Peut exécuter toutes les fonctions de sécurité de la charge de travail, y compris celles pour les alertes, l'analyse médico-légale, les collecteurs de données, les politiques de réponse automatisées et les API pour la sécurité de la charge de travail.  Un administrateur peut également inviter d’autres utilisateurs, mais ne peut attribuer que des rôles de sécurité de la charge de travail. 


| Utilisateur | Peut afficher et gérer les alertes et consulter les analyses médico-légales.  Le rôle utilisateur peut modifier l’état de l’alerte, ajouter une note, prendre des instantanés manuellement et restreindre l’accès utilisateur. 


| Invité | Peut afficher les alertes et les analyses médico-légales.  Le rôle d'invité ne peut pas modifier l'état de l'alerte, ajouter une note, prendre des instantanés manuellement ou restreindre l'accès des utilisateurs. 
|===
.Étapes
. Connectez-vous à Workload Security
. Dans le menu, cliquez sur *Admin > Gestion des utilisateurs*
+
Vous serez redirigé vers la page de gestion des utilisateurs de Data Infrastructure Insights.

. Sélectionnez le rôle souhaité pour chaque utilisateur.


Lors de l'ajout d'un nouvel utilisateur, sélectionnez simplement le rôle souhaité (généralement Utilisateur ou Invité).

Vous trouverez plus d'informations sur les comptes d'utilisateurs et les rôles dans Data Infrastructure Insights.link:https://docs.netapp.com/us-en/cloudinsights/concept_user_roles.html["Rôle de l'utilisateur"] documentation.
