---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: Configuration DU collecteur de données DELL EMC RecoverPoint. 
---
= Collecteur de données Dell EMC RecoverPoint
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
L'utilisation principale du collecteur de données EMC RecoverPoint consiste à découvrir les relations de réplication volume-volume que l'appliance de stockage RecoverPoint facilite. Ce collecteur découvre également l'appliance RecoverPoint elle-même. Veuillez noter que Dell/EMC vend une solution de sauvegarde VMware pour VM--« RecoverPoint for VM »--non prise en charge par ce collecteur

Pour la configuration, le collecteur de données nécessite l'adresse IP des processeurs de stockage ainsi qu'un nom d'utilisateur et un mot de passe en lecture seule.

Le collecteur de données EMC RecoverPoint rassemble les relations de réplication volume-volume que RecoverPoint coordonne sur les autres matrices de stockage. Data Infrastructure Insights affiche une baie de stockage pour chaque cluster RecoverPoint et collecte les données d'inventaire pour les nœuds et les ports de stockage sur ce cluster. Aucune donnée de volume ou de pool de stockage n'est collectée.



== De formation

Les informations suivantes sont requises pour configurer ce collecteur de données :

* Adresse IP ou nom de domaine complet du processeur de stockage
* Nom d'utilisateur et mot de passe en lecture seule
* Accès à l'API REST via le port 443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse de RecoverPoint | Adresse IP ou nom de domaine complet du cluster RecoverPoint 


| Nom d'utilisateur | Nom d'utilisateur du cluster RecoverPoint 


| Mot de passe | Mot de passe utilisé pour le cluster RecoverPoint 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port TCP utilisé pour se connecter au cluster RecoverPoint 


| Intervalle d'interrogation des stocks (minutes) | Intervalle entre les sondages d'inventaire. La valeur par défaut est 20 minutes. 


| Clusters exclus | Liste séparée par des virgules d'ID ou de noms de cluster à exclure lors de l'interrogation. 
|===


== Dépannage

Vous trouverez des informations supplémentaires sur ce Data Collector sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
