---
sidebar: sidebar 
permalink: task_dc_proxmox_ve.html 
keywords: data collector, Proxmox Virtual Environment, PVE 
summary: 'Configuration du collecteur de données de l"environnement virtuel Proxmox.' 
---
= Collecteur de données Proxmox Virtual Environment
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le collecteur DII Proxmox Virtual Environment collecte les données d'inventaire et de performance des machines virtuelles PVE (à l'exclusion des conteneurs LXC) et des hôtes/hyperviseurs. Ce collecteur, basé sur une API REST HTTPS, doit communiquer avec l'API REST Proxmox fournie par le service/démon pveproxy, qui écoute sur le port TCP 8006.

Ce collecteur de données utilise l'authentification par utilisateur + jeton. Vous devrez créer un compte de service sur chaque cluster Proxmox, attribuer les autorisations appropriées à l'utilisateur, puis générer un jeton d'API avec ces mêmes droits. Veuillez noter que le jeton d'un utilisateur Proxmox donné ne possède PAS nécessairement les mêmes droits/autorisations que l'utilisateur. DII aura généralement besoin de droits globaux d'Audit/Monitor : si vous créez un compte de service via l'interface utilisateur Proxmox, pour PathPermision commencez à « / », définissez Propagate sur « Oui » et déverrouillez au minimum Datastore Audit, Mapping Audit, Pool Audit, SDN Audit, Sys Audit, VM Audit, VM Monitor. Une fois l'utilisateur créé, vous pouvez alors créer un jeton d'accès pour celui-ci. Il est fortement recommandé de créer le jeton avec une expiration de 0 afin de garantir que le jeton n'expire jamais.



[[terminology]]
== Terminologie

Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour l’actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="50,50"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque | Disque virtuel 


| Hôte | Hôte 


| Machine virtuelle | Machine virtuelle 


| Stockage | Magasin de données 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



[[configuration]]
== Configuration

[cols="50,50"]
|===
| Champ | Description 


| Nom d'hôte ou adresse IP | Nom d’hôte ou adresse IP du système de stockage 


| ID du jeton API | Jeton API requis pour l'accès 


| Secret du jeton API | Secret associé au jeton ci-dessus 
|===


[[advanced-configuration]]
== Configuration avancée

[cols="50,50"]
|===
| Champ | Description 


| Port de communication HTTPS | Port utilisé pour la communication HTTPS (par défaut 8006) 


| Intervalle d'interrogation de l'inventaire (min) | La valeur par défaut est de 20 minutes. 
|===


[[troubleshooting]]
== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
