---
sidebar: sidebar 
permalink: task_business_entity_annotations.html 
keywords: annotations, business entity 
summary: 'Les annotations d"entités commerciales peuvent être utilisées pour la surveillance et la création de rapports sur les actifs de votre hiérarchie commerciale.' 
---
= Annotations d'entités commerciales
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Créez et gérez des entités commerciales pour votre environnement d'entreprise à l'aide du type d'annotation *Entité commerciale*.



== Création d'une entité commerciale

Pour créer une entité commerciale, procédez comme suit :

. Cliquez sur *Gérer > Annotations* et cliquez sur le lien _Entité commerciale_.
+
La liste des entités commerciales actuellement définies s'affiche.

. Cliquez sur *+ Entité commerciale*.
. Saisissez des valeurs pour les champs *Locataire*, *Secteur d'activité*, *Unité commerciale* et *Projet*.
+
Vous pouvez laisser n’importe quel champ vide s’il ne s’applique pas à votre entité commerciale.

. Si vous avez déjà saisi une valeur pour un champ, vous pouvez sélectionner cette valeur dans la liste déroulante.  Vous n'avez pas besoin de le saisir à nouveau.



NOTE: Les valeurs sélectionnées doivent constituer une entité commerciale totale unique.  Par exemple, si vous disposez déjà d’une entité commerciale avec les valeurs _A / B / C / D_ dans cet ordre, vous ne pouvez pas créer une autre entité commerciale avec ces valeurs dans cet ordre.  Vous pouvez toutefois créer une entité commerciale avec ces valeurs dans un ordre différent.



== Application d'une entité métier à un objet

Le moyen le plus simple d’appliquer une entité commerciale à un ou plusieurs objets est d’utiliser une requête.

. Cliquez sur *Requêtes > +Nouvelle requête* et sélectionnez le type d’objet souhaité.  Vous pouvez appliquer des filtres pour affiner davantage les résultats.
. Cliquez sur la case à cocher pour sélectionner le ou les objets pour lesquels vous souhaitez appliquer l'entité commerciale.
. Cliquez sur *Actions en masse* et sélectionnez *Ajouter une annotation*.
. Choisissez l’annotation _Entité commerciale_ et sélectionnez la valeur d’entité commerciale souhaitée dans la liste.
. Cliquez sur *Enregistrer* pour appliquer l’entité commerciale aux objets.


Vous pouvez également appliquer une entité commerciale à un objet individuel en accédant à la page de destination des ressources de l'objet et en cliquant sur *+Annotation) dans la section Données utilisateur.

Vous pouvez également configurer unlink:task_create_annotation_rules.html["Règle d'annotation"] pour appliquer des entités commerciales à des objets.


NOTE: Un objet ne peut avoir qu’une seule entité commerciale associée.



== Suppression d'une entité commerciale d'un objet

Pour supprimer une entité commerciale d'un ou plusieurs objets, recherchez et sélectionnez le ou les objets, cliquez sur *Actions en masse* et sélectionnez _Supprimer l'annotation_.  Sélectionnez l’annotation Entité commerciale et cliquez sur *Supprimer*.
