---
sidebar: sidebar 
permalink: task_dc_infinidat_infinibox.html 
keywords: data collector, infinidat, InfiniBox 
summary: Configuration du collecteur de données Infinidat InfiniBox. 
---
= Collecteur de données Infinidat InfiniBox
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le collecteur de données Infinidat InfiniBox (HTTP) est utilisé pour collecter des informations d'inventaire à partir du système de stockage Infinidat InfiniBox.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données Infinidat InfiniBox.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Piscine de stockage | Piscine de stockage 


| Nœud | Contrôleur 


| Système de fichiers | Volume interne 


| Système de fichiers | Partage de fichiers 


| Exportations du système de fichiers | Partager 
|===


== Exigences

Les exigences suivantes doivent être respectées lors de la configuration de ce collecteur de données.

* Adresse IP ou FQDN du nœud de gestion InfiniBox
* Identifiant et mot de passe de l'administrateur
* Port 443 via l'API REST




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Hôte InfiniBox | Adresse IP ou nom de domaine complet du nœud de gestion InfiniBox 


| Nom d'utilisateur | Nom d'utilisateur pour le nœud de gestion InfiniBox 


| Mot de passe | Mot de passe pour le nœud de gestion InfiniBox 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port TCP utilisé pour se connecter au serveur InfiniBox.  La valeur par défaut est 443. 


| Intervalle d'interrogation de l'inventaire | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 60 minutes. 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
