---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: Configuration du collecteur de données IBM PowerVM. 
---
= Configuration du collecteur de données IBM PowerVM
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le collecteur de données IBM PowerVM (SSH) est utilisé pour collecter des informations sur les partitions virtuelles exécutées sur des instances matérielles IBM POWER gérées par une console de gestion du matériel (HMC).



== Terminologie

Data Infrastructure Insights acquiert des informations d'inventaire à partir des partitions virtuelles exécutées sur les instances matérielles IBM POWER.  Pour chaque type d’actif acquis, la terminologie la plus courante utilisée pour l’actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| disque dur | Disque virtuel 


| Système géré | Hôte 


| LPAR, serveur VIO | Machine virtuelle 


| Groupe de volumes | Magasin de données 


| Volume physique | LUN 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

Les exigences suivantes doivent être remplies pour configurer et utiliser ce collecteur de données :

* Adresse IP de la console de gestion du matériel (HMC)
* Nom d'utilisateur et mot de passe permettant d'accéder à la console de gestion du matériel (HMC) via SSH
* Exigence de port SSH-22
* Afficher les autorisations sur tous les systèmes de gestion et les domaines de sécurité des partitions logiques
+
L'utilisateur doit également disposer de l'autorisation d'affichage sur les configurations HMC et de la possibilité de collecter des informations VPD pour le groupe de sécurité de la console HMC.  L'utilisateur doit également être autorisé à accéder à la commande Virtual IO Server sous le groupe de sécurité Partition logique.  Il est recommandé de commencer par le rôle d’un opérateur, puis de supprimer tous les rôles.  Les utilisateurs en lecture seule sur la console HMC ne disposent pas des privilèges nécessaires pour exécuter des commandes proxy sur les hôtes AIX.

* La meilleure pratique d'IBM consiste à faire surveiller les périphériques par deux ou plusieurs HMC.  Sachez que cela peut amener OnCommand Insight à signaler des périphériques dupliqués. Il est donc fortement recommandé d'ajouter des périphériques redondants à la liste « Exclure les périphériques » dans la configuration avancée de ce collecteur de données.




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP de la console de gestion du matériel (HMC) | Adresse IP ou nom de domaine complet de la console de gestion du matériel PowerVM 


| Utilisateur HMC | Nom d'utilisateur pour la console de gestion du matériel 


| Mot de passe | Mot de passe utilisé pour la console de gestion du matériel 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 20 minutes. 


| Port SSH | Port utilisé pour SSH vers PowerVM 


| Mot de passe | Mot de passe utilisé pour la console de gestion du matériel 


| Nombre de tentatives | Nombre de tentatives de ré-inventaire 


| Exclure les appareils | Liste séparée par des virgules des identifiants d'appareils ou des noms d'affichage à exclure 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
