---
sidebar: sidebar 
permalink: task_dc_na_solidfire.html 
summary: Configurer le collecteur de données NetApp SolidFire 
keywords: data collector, queries, create 
---
= Collecteur de données NetApp SolidFire All-Flash Array
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le collecteur de données NetApp SolidFire All-Flash Array prend en charge l'inventaire et la collecte des performances à partir des configurations SolidFire iSCSI et Fibre Channel.

Le collecteur de données SolidFire utilise l'API REST SolidFire .  L'unité d'acquisition où réside le collecteur de données doit pouvoir initier des connexions HTTPS au port TCP 443 sur l'adresse IP de gestion du cluster SolidFire .  Le collecteur de données a besoin d’informations d’identification capables d’effectuer des requêtes API REST sur le cluster SolidFire .



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes à partir du collecteur de données NetApp SolidFire All-Flash Array.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Conduire | Disque 


| Cluster | Stockage 


| Nœud | Nœud de stockage 


| Volume | Volume 


| Port Fibre Channel | Port 


| Groupe d'accès aux volumes, attribution de LUN | Carte des volumes 


| Session iSCSI | Masque de volume 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

Les exigences suivantes sont requises pour la configuration de ce collecteur de données :

* Adresse IP virtuelle de gestion
* Nom d'utilisateur et informations d'identification en lecture seule
* Port 443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP virtuelle de gestion (MVIP) | Gestion de l'adresse IP virtuelle du cluster SolidFire 


| Nom d'utilisateur | Nom utilisé pour se connecter au cluster SolidFire 


| Mot de passe | Mot de passe utilisé pour se connecter au cluster SolidFire 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Type de connexion | Choisissez le type de connexion 


| Port de communication | Port utilisé pour l'API NetApp 


| Intervalle d'interrogation d'inventaire (min) | La valeur par défaut est de 20 minutes 


| Intervalle d'interrogation des performances (sec) | La valeur par défaut est de 300 secondes 
|===


== Dépannage

Lorsque SolidFire signale une erreur, celle-ci s'affiche dans Data Infrastructure Insights comme suit :

_Un message d'erreur a été reçu d'un périphérique SolidFire lors de la tentative de récupération de données.  L'appel était <méthode> (<parameterString> ).  Le message d'erreur de l'appareil était (consultez le manuel de l'appareil) : <message>_

Où:

* La <méthode> est une méthode HTTP, telle que GET ou PUT.
* Le <parameterString> est une liste séparée par des virgules de paramètres qui ont été inclus dans l'appel REST.
* Le <message> est le message d'erreur renvoyé par l'appareil.


Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
