---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: Configuration du collecteur de données NetApp StorageGRID 
keywords: data collector, queries, create, storagegrid 
---
= Collecteur de données NetApp StorageGRID
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Le collecteur de données NetApp StorageGRID prend en charge l'inventaire et la collecte des performances à partir des configurations StorageGRID.


NOTE: StorageGRID est mesuré en To brut différent du taux unitaire géré. Toutes les 40 To de capacité StorageGRID non formatée sont facturés comme 1 link:concept_subscribing_to_cloud_insights.html#pricing["Unité gérée (UM)"].



== Terminologie

Les informations d'inventaire suivantes sont acquises depuis le collecteur NetApp StorageGRID. Pour chaque type d'actif acquis, la terminologie la plus utilisée pour ce bien est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme informations exploitables sur l'infrastructure de données 


| StorageGRID | Stockage 


| Nœud | Nœud 


| Locataire | Pool de stockage 


| Godet | Volume interne 
|===


== De formation

La configuration de cette source de données est requise pour :

* Adresse IP de l'hôte StorageGRID
* Nom d'utilisateur et mot de passe pour un utilisateur auquel les rôles de requête métrique et d'accès au locataire ont été attribués
* Orifice 443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP de l'hôte StorageGRID | Adresse IP virtuelle de gestion de l'appliance StorageGRID 


| Nom d'utilisateur | Nom utilisé pour se connecter à l'appliance StorageGRID 


| Mot de passe | Mot de passe utilisé pour se connecter à l'appliance StorageGRID 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation des stocks (min) | La valeur par défaut est 60 minutes 


| Intervalle d'interrogation des performances (s) | La valeur par défaut est 900 secondes 
|===


== Authentification unique (SSO)

Les link:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"]versions de micrologiciel ont les versions d'API correspondantes ; l'API 3.0 et les versions plus récentes prennent en charge la connexion SSO (Single Sign-on).

|===


| Version du micrologiciel | Version API | Prise en charge d'un SSO 


| 11,1 | 2 | Non 


| 11,2 | 3,0 | Oui 


| 11,5 | 3,3 | Oui 
|===


== Dépannage

Vous trouverez des informations supplémentaires sur ce Data Collector sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
