---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, PowerFlex EMC, DELL 
summary: Configuration du collecteur de données DELL EMC ScaleIO/PowerFlex. 
---
= Collecteur de données DELL EMC ScaleIO / PowerFlex
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le collecteur de données ScaleIO/PowerFlex collecte les informations d'inventaire à partir du stockage ScaleIO et PowerFlex. Pour la configuration, ce collecteur de données nécessite l'adresse de la passerelle ScaleIO/PowerFlex ainsi qu'un nom d'utilisateur et un mot de passe administrateur.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes à partir du collecteur de données ScaleIO/PowerFlex. Pour chaque type de ressource acquis par Data Infrastructure Insights, la terminologie la plus courante est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme informations exploitables sur l'infrastructure de données 


| Cluster MDM (Meta Data Manager) | Stockage 


| SDS (ScaleIO/serveur de données PowerFlex) | Nœud de stockage 


| Pool de stockage | Pool de stockage 


| Volumétrie | Volumétrie 


| Périphérique | Disque 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

* Accès en lecture seule au compte utilisateur Admin
* Port requis : port HTTPS 443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Passerelle(s) ScaleIO/PowerFlex | Adresses IP ou FQDN des passerelles ScaleIO/PowerFlex, séparées par une virgule (,) ou un point-virgule (;) 


| Nom d'utilisateur | Nom d'utilisateur Admin utilisé pour se connecter au périphérique ScaleIO/PowerFlex 


| Mot de passe | Mot de passe utilisé pour se connecter au périphérique ScaleIO/PowerFlex 
|===


== Configuration avancée

Cochez la case Inventaire pour activer la collecte de stock.

[cols="2*"]
|===
| Champ | Description 


| Port HTTPS | 443 


| Intervalle d'interrogation des stocks (min) | La valeur par défaut est 60. 


| Délai de connexion (s) | La valeur par défaut est 60. 
|===


== Dépannage

Des informations supplémentaires sont disponibles sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
