---
sidebar: sidebar 
permalink: task_modify_delete_query.html 
summary: Modifier ou supprimer une requête 
keywords: query, queries, modify, edit, delete, remove 
---
= Modifier ou supprimer une requête
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Vous pouvez modifier les critères associés à une requête lorsque vous souhaitez modifier les critères de recherche des actifs que vous interrogez.



== Modifier une requête

.Étapes
. Cliquez sur *Explorer* et sélectionnez *Toutes les requêtes de métriques*.
+
La page Requêtes s'affiche.

. Cliquez sur le nom de la requête
. Pour ajouter un critère à la requête, cliquez sur l’icône Colonnes et sélectionnez une métrique ou un attribut dans la liste.


Une fois que vous avez effectué toutes les modifications nécessaires, effectuez l’une des opérations suivantes :

* Cliquez sur le bouton *Enregistrer* pour enregistrer la requête avec le nom utilisé initialement.
* Cliquez sur le menu déroulant à côté du bouton *Enregistrer* et sélectionnez *Enregistrer sous* pour enregistrer la requête sous un autre nom.  Cela n’écrase pas la requête d’origine.
* Cliquez sur le menu déroulant à côté du bouton *Enregistrer* et sélectionnez *Renommer* pour modifier le nom de la requête que vous aviez utilisé initialement.  Cela écrase la requête d'origine.
* Cliquez sur le menu déroulant à côté du bouton *Enregistrer* et sélectionnez *Annuler les modifications* pour rétablir la requête aux dernières modifications enregistrées.




== Suppression d'une requête

Pour supprimer une requête, cliquez sur *Requêtes* et sélectionnez *Afficher toutes les requêtes*, puis effectuez l'une des opérations suivantes :

. Cliquez sur le menu « trois points » à droite de la requête et cliquez sur *Supprimer*.
. Cliquez sur le nom de la requête et sélectionnez *Supprimer* dans le menu déroulant *Enregistrer*.

