---
sidebar: sidebar 
permalink: task_cs_add_collector_ontap.html 
keywords: data collector, ONTAP, SVM 
summary: Ajout de collecteurs de données 
---
= Configuration du collecteur de données NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Workload Security utilise des collecteurs de données pour collecter les données d'accès aux fichiers et aux utilisateurs à partir des appareils.  Les données sont fournies à Workload Security pour analyse.

.Avant de commencer
Vous avez besoin des informations suivantes pour configurer ce collecteur de données :

* Un agent doit être configuré pour collecter des données
* L'adresse IP de gestion SVM
* Un nom d'utilisateur pour accéder au SVM
* Le mot de passe pour accéder au SVM


.Étapes de configuration
. Connectez-vous en tant qu’administrateur ou propriétaire de compte à votre environnement Workload Security.
. Cliquez sur *Observabilité > Collecteurs > +Collecteurs de données*
+
Le système affiche les collecteurs de données disponibles.

. Cliquez sur *+Surveiller* dans la mosaïque NetApp ONTAP .
+
Le système affiche la page de configuration Ajouter un collecteur de données : Ontap SVM.

. Entrez un nom unique pour le collecteur
. Sélectionnez l'agent qui collectera les données
. Entrez l'adresse IP de gestion SVM
. Entrez le nom d'utilisateur pour accéder au SVM
. Entrez le mot de passe pour accéder au SVM
. Cliquez sur *+Ajouter un collectionneur*


.Après avoir terminé
* Cliquez sur *Sécurité de la charge de travail > Collecteurs* pour vérifier l’état du collecteur que vous avez configuré.
+
Il y a normalement un délai avant que l'état du collecteur ne soit affiché.


