---
sidebar: sidebar 
permalink: task_dc_qumulo_rest.html 
keywords: data collector, qumulo, rest 
summary: Configuration du collecteur de données REST Qumulo. 
---
= Collecteur de données REST Qumulo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights utilise ce collecteur pour acquérir des données d'inventaire et de performance à partir du stockage Qumulo.



== Terminologie

Data Infrastructure Insights acquiert les informations d’inventaire suivantes auprès de ce collecteur de données.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Conduire | Disque 


| Cluster | Stockage 


| Nœud | Nœud de stockage 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

Vous avez besoin des informations suivantes pour configurer ce collecteur de données :

* Un compte utilisateur et un mot de passe.  Ce compte n'a PAS besoin d'être administrateur/root, mais vous DEVEZ accorder un nombre substantiel de privilèges en lecture seule à votre compte de service - voir le tableau ci-dessous
* Adresse IP / Nom de domaine pleinement qualifié du cluster Qumulo
* Accès HTTPS au port 8000




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP de Qumulo | L'adresse IP ou le nom de domaine complet (FQDN) du stockage Qumulo 


| Nom d'utilisateur | Nom d'utilisateur pour le Qumulo 


| Mot de passe | Mot de passe utilisé pour le Qumulo 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port HTTPS | La valeur par défaut est de 8000. 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les interrogations d'inventaire. La valeur par défaut est 30. 


| Intervalle de sondage des performances (min) | Intervalle entre les relevés de performance. La valeur par défaut est de 5. 
|===


== Dépannage

Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
