---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, PowerFlex EMC, DELL 
summary: Configuration du collecteur de données DELL EMC ScaleIO/PowerFlex. 
---
= Collecteur de données DELL EMC ScaleIO / PowerFlex
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le collecteur de données ScaleIO/PowerFlex collecte les informations d'inventaire à partir du stockage ScaleIO et PowerFlex.  Pour la configuration, ce collecteur de données nécessite l'adresse de la passerelle ScaleIO/PowerFlex ainsi qu'un nom d'utilisateur et un mot de passe administrateur.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données ScaleIO/PowerFlex.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Cluster MDM (gestionnaire de métadonnées) | Stockage 


| SDS (serveur de données ScaleIO/PowerFlex) | Nœud de stockage 


| Piscine de stockage | Piscine de stockage 


| Volume | Volume 


| Appareil | Disque 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

* Accès en lecture seule au compte utilisateur Admin
* Exigence de port : port HTTPS 443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Passerelle(s) ScaleIO/PowerFlex | Adresses IP ou FQDN des passerelles ScaleIO/PowerFlex, séparées par une virgule (,) ou un point-virgule (;) 


| Nom d'utilisateur | Nom d'utilisateur administrateur utilisé pour se connecter au périphérique ScaleIO/PowerFlex 


| Mot de passe | Mot de passe utilisé pour se connecter à l'appareil ScaleIO/PowerFlex 
|===


== Configuration avancée

Cliquez sur la case à cocher Inventaire pour activer la collecte d’inventaire.

[cols="2*"]
|===
| Champ | Description 


| Port HTTPS | 443 


| Intervalle d'interrogation de l'inventaire (min) | La valeur par défaut est 60. 


| Délai d'expiration de la connexion (sec) | La valeur par défaut est 60. 
|===


== Dépannage

Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
