---
sidebar: sidebar 
permalink: task_cloud_insights_onboarding_1.html 
summary: Inscription à Data Infrastructure Insights et création de votre locataire. 
keywords: onboarding, new user 
---
= Data Infrastructure Insights
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant de pouvoir commencer à travailler avec Data Infrastructure Insights, vous devez vous inscrire sur le portail * NetApp Console*.  Si vous disposez déjà d'une connexion à la NetApp Console , vous pouvez démarrer un essai gratuit de Data Infrastructure Insights en quelques étapes rapides.



== Création de votre compte NetApp Console

Pour démarrer avec les services cloud de NetApp, accédez àlink:https://console.netapp.com/["* NetApp Console*"^] et cliquez sur *Commencer*.

* Si vous n'êtes pas encore inscrit, sélectionnez *S'inscrire*
* Saisissez une adresse e-mail professionnelle valide et choisissez un mot de passe.
* Entrez le nom de votre entreprise et votre nom complet.
* Acceptez les termes et conditions et sélectionnez *Continuer*.
* La console vous guidera tout au long du processus de démarrage.




=== Que faire si j’ai déjà une connexion à la NetApp Console ?

Une fois que vous avez un compte NetApp Console , choisissez simplement *Connexion* sur lelink:https://console.netapp.com/["* NetApp Console*"^] page du portail.

Entrez votre adresse email et votre mot de passe.  Vous serez ensuite redirigé vers la page des offres cloud de NetApp.

Accédez à *Analyse et contrôle > Observabilité* pour en savoir plus sur Data Infrastructure Insights et/ou demander une démonstration.



== Démarrez votre essai gratuit de Data Infrastructure Insights

Si c'est la première fois que vous vous connectez à Data Infrastructure Insights, découvrez tout ce que Data Infrastructure Insights a à offrir, et lorsque vous serez _prêt à commencer_, cliquez sur *Demander un essai* et remplissez vos informations.

Dans le cadre de la configuration de votre locataire d'essai, vous choisirez la région dans laquelle héberger votre locataire, et si vous souhaitez que votre locataire soit hébergé sur AWS ou Azure.

Une fois la création de votre locataire terminée, utilisez vos informations d'identification de console pour vous connecter et démarrer votre essai gratuit de 30 jours de Data Infrastructure Insights. Au cours de cet essai, vous pouvez découvrir les fonctionnalités offertes par Data Infrastructure Insights .

Pendant l'essai gratuit, vous pouvezlink:concept_subscribing_to_cloud_insights.html["démarrez votre abonnement"] à Data Infrastructure Insights à tout moment.  Lorsque vous êtes abonné, vous pouvez utiliser les fonctionnalités de Data Infrastructure Insights en fonction de votre abonnement actuel.



== Sign in et c'est parti

Une fois votre locataire créé, vous pouvez à tout moment vous connecter au portail NetApp BlueXP et accéder à link:https://services.cloud.netapp.com["Services cloud"] page et sélectionnez *Accéder à Data Infrastructure Insights*.

Vous pouvez également ouvrir un navigateur directement sur l'URL de votre locataire Data Infrastructure Insights , par exemple :

 \https://<tenant-prefix>.c01.cloudinsights.netapp.com/
L'URL sera également incluse dans l'e-mail d'invitation de chaque utilisateur pour un accès et une mise en favoris simples.  Si l'utilisateur n'est pas déjà connecté à la console, il sera invité à se connecter.


NOTE: Les nouveaux utilisateurs doivent toujours s'inscrire pour accéder à la console avant de pouvoir accéder à l'URL de leur locataire.

La première fois que vous vous connectez à un nouveau locataire, vous serez guidé dans la configurationlink:task_getting_started_with_cloud_insights.html["*commence à collecter des données*"] .



== Déconnexion

Pour vous déconnecter de Data Infrastructure Insights, cliquez sur votre *Nom d'utilisateur* et sélectionnez *Déconnexion*.  Vous serez redirigé vers l’écran de connexion de la console.


NOTE: La déconnexion de Data Infrastructure Insights vous déconnecte de la console.  Vous serez également déconnecté des autres services NetApp Cloud qui utilisent la connexion à la console.



=== Délai d'inactivité

Par défaut, la console déconnecte un utilisateur s'il n'y a aucune activité pendant six heures (360 minutes).  Quelle que soit l’activité, les utilisateurs seront déconnectés après sept jours.
