---
sidebar: sidebar 
permalink: task_dc_ms_hyperv.html 
keywords: data collector, Microsoft, Hyper-V 
summary: Configuration du collecteur de données Microsoft Hyper-V. 
---
= Collecteur de données Microsoft Hyper-V.
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Le collecteur de données Microsoft Hyper-V acquiert les données d'inventaire et de performances de l'environnement informatique de serveur virtualisé. Ce collecteur de données peut découvrir un hôte Hyper-V autonome ou un cluster entier. Il peut en créer un par hôte ou cluster autonome.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes à partir de Microsoft Hyper-V (WMI). Pour chaque type de ressource acquis par Data Infrastructure Insights, la terminologie la plus courante est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme informations exploitables sur l'infrastructure de données 


| Disque dur virtuel | Disque virtuel 


| Hôte | Hôte 


| Ordinateur virtuel | Ordinateur virtuel 


| CSV (Cluster Shared volumes), Volume de partitions | Datastore 


| Périphérique SCSI Internet, LUN SCSI Multi Path | LUN 


| Port Fibre Channel | Port 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

Les éléments suivants sont nécessaires pour configurer ce collecteur de données :

* Hyper-V requiert l'ouverture du port 5985 pour la collecte de données et l'accès/la gestion à distance.
* Adresse IP ou FQDN du cluster ou de l'hyperviseur autonome. L'utilisation du nom d'hôte ou de l'adresse IP flottante du cluster constitue probablement l'approche la plus fiable au lieu de pointer le collecteur vers un seul nœud spécifique d'un cluster.
* Compte utilisateur de niveau administrateur qui fonctionne sur tous les hyperviseurs du cluster.
* WinRM doit être activé et être à l'écoute de tous les hyperviseurs
* Configuration requise du port : le port 135 via les ports WMI et TCP dynamique a été attribué à 1024-65535 pour Windows 2003 et versions antérieures et à 49152-65535 pour Windows 2008.
* La résolution DNS doit réussir, même si le collecteur de données est pointé à une seule adresse IP
* Chaque hyperviseur Hyper-V doit avoir la fonction de mesure des ressources activée pour chaque machine virtuelle, sur chaque hôte. Ainsi, chaque hyperviseur peut disposer de plus de données pour que Data Infrastructure Insights soit disponible sur chaque invité. Si ce paramètre n'est pas défini, moins de mesures de performance sont acquises pour chaque client. Pour plus d'informations sur la mesure des ressources, consultez la documentation Microsoft :
+
link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Présentation de la mesure des ressources Hyper-V"]

+
link:https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["Activer-VMResourceMetering"]




NOTE: Le collecteur de données Hyper-V nécessite une unité d'acquisition Windows.



== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP du cluster ou nom de domaine complet du cluster flottant | L'adresse IP ou le nom de domaine complet du cluster ou un hyperviseur autonome non mis en cluster 


| Nom d'utilisateur | Nom d'utilisateur administrateur de l'hyperviseur 


| Mot de passe | Mot de passe de l'hyperviseur 


| Suffixe de domaine DNS | Le suffixe de nom d'hôte associé au nom d'hôte simple pour afficher le nom de domaine complet d'un hyperviseur 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation des stocks (min) | La valeur par défaut est 20 minutes. 
|===


== Dépannage

Vous trouverez des informations supplémentaires sur ce Data Collector sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
