---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: 'Suivez les données à l"aide d"annotations.' 
---
= Définition des annotations
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lors de la personnalisation de Data Infrastructure Insights pour suivre les données en fonction des besoins de votre entreprise, vous pouvez définir des notes spécialisées, appelées annotations, et les attribuer à vos ressources.

Vous pouvez attribuer des annotations aux actifs avec des informations telles que la fin de vie de l'actif, le centre de données, l'emplacement du bâtiment, le niveau de stockage ou le niveau de service du volume.

L’utilisation d’annotations pour vous aider à surveiller votre environnement comprend les tâches de haut niveau suivantes :

* Création ou modification de définitions pour tous les types d'annotations.
* Affichage des pages d'actifs et association de chaque actif à une ou plusieurs annotations.
+
Par exemple, si un actif est loué et que le bail expire dans les deux mois, vous souhaiterez peut-être appliquer une annotation de fin de vie à l'actif.  Cela permet d’empêcher d’autres personnes d’utiliser cet actif pendant une période prolongée.

* Création de règles pour appliquer automatiquement des annotations à plusieurs ressources du même type.
* Filtrer les ressources par leurs annotations.




== Types d'annotations par défaut

Data Infrastructure Insights fournit certains types d’annotations par défaut.  Ces annotations peuvent être utilisées pour filtrer ou regrouper des données.

Vous pouvez associer des ressources à des types d’annotation par défaut tels que les suivants :

* Cycle de vie des actifs, comme l'anniversaire, le coucher du soleil ou la fin de vie
* Informations de localisation sur un appareil, telles qu'un centre de données, un bâtiment ou un étage
* Classification des actifs, par exemple par qualité (niveaux), par appareils connectés (niveau de commutation) ou par niveau de service
* Statut, tel que chaud (utilisation élevée)


Le tableau suivant répertorie les types d’annotations fournis par Data Infrastructure Insights.

[cols="30,53, 16"]
|===


| Types d'annotations | Description | Type 


| Alias | Nom convivial pour une ressource | Texte 


| Groupe de ressources informatiques | Affectation de groupe utilisée par le collecteur de données des systèmes de fichiers hôte et VM | Liste 


| Centre de données | Localisation physique | Liste 


| Chaud | Appareils soumis à une utilisation intensive de manière régulière ou au seuil de capacité | Booléen 


| Remarque | Commentaires associés à une ressource | Test 


| Niveau de service | Un ensemble de niveaux de service pris en charge que vous pouvez attribuer aux ressources.  Fournit une liste d'options ordonnées pour les volumes internes, qtree et les volumes.  Modifiez les niveaux de service pour définir des politiques de performances pour différents niveaux. | Liste 


| Coucher de soleil | Seuil défini après lequel aucune nouvelle allocation ne peut être effectuée sur ce périphérique.  Utile pour les migrations planifiées et autres modifications de réseau en attente. | Date 


| Niveau de commutation | Options prédéfinies pour la configuration des catégories pour les commutateurs.  En règle générale, ces désignations restent valables pendant toute la durée de vie de l'appareil, même si vous pouvez les modifier.  Disponible uniquement pour les commutateurs. | Liste 


| Étage | Peut être utilisé pour définir différents niveaux de service au sein de votre environnement.  Les niveaux peuvent définir le type de niveau, comme la vitesse nécessaire (par exemple, or ou argent).  Cette fonctionnalité est disponible uniquement sur les volumes internes, les qtrees, les baies de stockage, les pools de stockage et les volumes. | Liste 


| Gravité de la violation | Rang (par exemple, majeur) d'une violation (par exemple, ports hôtes manquants ou redondance manquante), dans une hiérarchie de l'importance la plus élevée à la plus faible. | Liste 
|===

NOTE: Alias, Centre de données, Chaud, Niveau de service, Coucher de soleil, Niveau de commutateur, Niveau et Gravité de la violation sont des annotations au niveau du système, que vous ne pouvez pas supprimer ou renommer ; vous ne pouvez modifier que leurs valeurs attribuées.



== Créer des annotations personnalisées

À l’aide d’annotations, vous pouvez ajouter des données personnalisées spécifiques à votre entreprise qui correspondent aux besoins de votre entreprise aux actifs.  Bien que Data Infrastructure Insights fournisse un ensemble d'annotations par défaut, vous souhaiterez peut-être afficher les données d'autres manières.  Les données des annotations personnalisées complètent les données de l'appareil déjà collectées, telles que le fabricant de stockage, les volumes numériques et les statistiques de performances.  Les données que vous ajoutez à l’aide d’annotations ne sont pas découvertes par Data Infrastructure Insights.

.Étapes
. Dans le menu Data Infrastructure Insights , cliquez sur *Gérer > Annotations*.
+
La page Annotations affiche la liste des annotations.

. Cliquez sur *+Ajouter*
. Saisissez un *Nom* et une *Description* de l'annotation.
+
Vous pouvez saisir jusqu'à 255 caractères dans ces champs.

. Cliquez sur *Type*, puis sélectionnez l’une des options suivantes qui représente le type de données autorisées dans cette annotation :


.Types d'annotations
* Booléen : Crée une liste déroulante avec les options « oui » et « non ». Par exemple, l'annotation « Rattaché directement » est booléenne.
* Date : cela crée un champ qui contient une date. Par exemple, si l’annotation est une date, sélectionnez cette option.
* Liste : crée l’un des éléments suivants :
+
** Une liste déroulante fixe
+
Lorsque d’autres attribuent ce type d’annotation sur un appareil, ils ne peuvent pas ajouter plus de valeurs à la liste.

** Une liste déroulante flexible
+
Si vous sélectionnez l'option Ajouter de nouvelles valeurs à la volée lorsque vous créez cette liste, lorsque d'autres personnes attribuent ce type d'annotation sur un appareil, elles peuvent ajouter davantage de valeurs à la liste.



* Numéro : crée un champ dans lequel l’utilisateur attribuant l’annotation peut saisir un numéro.  Par exemple, si le type d’annotation est « Étage », l’utilisateur peut sélectionner le type de valeur « numéro » et saisir le numéro de l’étage.
* Texte : crée un champ qui autorise le texte libre.  Par exemple, vous pouvez saisir « Langue » comme type d’annotation, sélectionner « Texte » comme type de valeur et saisir une langue comme valeur.



NOTE: Après avoir défini le type et enregistré vos modifications, vous ne pouvez pas modifier le type de l'annotation.  Si vous devez modifier le type, vous devez supprimer l'annotation et en créer une nouvelle.

. Si vous sélectionnez Liste comme type d’annotation, procédez comme suit :
+
.. Sélectionnez *Ajouter de nouvelles valeurs à la volée* si vous souhaitez pouvoir ajouter davantage de valeurs à l'annotation lorsque vous êtes sur une page d'actif, ce qui crée une liste flexible.
+
Par exemple, supposons que vous êtes sur une page d’actif et que l’actif comporte l’annotation Ville avec les valeurs Détroit, Tampa et Boston.  Si vous avez sélectionné l'option *Ajouter de nouvelles valeurs à la volée*, vous pouvez ajouter des valeurs supplémentaires à la ville comme San Francisco et Chicago directement sur la page de l'actif au lieu de devoir accéder à la page Annotations pour les ajouter.  Si vous ne choisissez pas cette option, vous ne pouvez pas ajouter de nouvelles valeurs d’annotation lors de l’application de l’annotation ; cela crée une liste fixe.

.. Saisissez une valeur et une description dans les champs *Valeur* et *Description*.
.. Cliquez sur *+Ajouter+* pour ajouter des valeurs supplémentaires.
.. Cliquez sur l’icône Corbeille pour supprimer une valeur.


. Cliquez sur *Enregistrer*
+
Vos annotations apparaissent dans la liste sur la page Annotations.



.Remarque sur les annotations booléennes
Lors du filtrage sur une annotation booléenne, les valeurs suivantes peuvent vous être présentées sur lesquelles filtrer :

* *Tout* : cela renverra _tous_ les résultats, y compris les résultats définis sur « Oui », « Non » ou pas définis du tout.
* *Oui* : renvoie uniquement les résultats « Oui ». Notez que DII affiche « Oui » comme coche dans la plupart des tableaux. Les valeurs peuvent être définies sur « Vrai », « Activé », etc. DII traite toutes ces valeurs comme « Oui ».
* *Non* : renvoie uniquement les résultats « Non ». Notez que DII affiche « Non » sous la forme d’un « X » dans la plupart des tableaux. Les valeurs peuvent être définies sur « Faux », « Désactivé », etc. DII traite toutes ces valeurs comme « Non ».
* *Aucun* : renvoie uniquement les résultats pour lesquels l'annotation n'a pas été définie du tout. Également appelées valeurs « nulles ».


.Après avoir terminé
Dans l'interface utilisateur, l'annotation est immédiatement disponible pour utilisation.
