---
sidebar: sidebar 
permalink: task_dc_redhat_openshift_virtualization.html 
keywords: data collector, Red Hat OpenShift Virtualization 
summary: Configuration du collecteur de données Red Hat OpenShift Virtualization. 
---
= Collecteur de données Red Hat OpenShift Virtualization
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le collecteur DII Red Hat OpenShift Virtualization tentera de découvrir les charges de travail de calcul OSV exécutées sur un environnement OpenShift Virtualization - ce collecteur ne découvrira pas tous les pods OpenShift. Il s'agit d'un collecteur basé sur une API REST HTTPS. Il est recommandé de créer un collecteur par cluster OSV.

L'approche d'authentification pour ce collecteur est un jeton d'authentification lié à un compte de service. Pour créer à la fois le compte utilisateur et le jeton :

....
oc create sa acq-readonly-cluster-user -n default
oc adm policy add-cluster-role-to-user cluster-reader -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-user-binding
oc adm policy add-cluster-role-to-user cluster-monitoring-view -z acq-readonly-cluster-user --rolebinding-name acq-readonly-cluster-monitor-user-binding
....
Exécutez ces 3 commandes et surveillez toute erreur.

Une fois les commandes terminées :

 oc sa new-token acq-readonly-cluster-user
Cela créera un jeton lié à votre utilisateur.

Enfin, vous pouvez également demander à votre administrateur OSV d'exécuter :

 oc cluster-info
Cette commande renverra le nom d'hôte ou l'adresse IP pour la gestion. Chaque collecteur DII OSV doit être configuré pour pointer vers l'adresse IP ou le nom d'hôte pour la gestion OSV.



== Terminologie

Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour l’actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque | Disque virtuel 


| Hôte | Hôte 


| Machine virtuelle | Machine virtuelle 


| Domaine de stockage | Magasin de données 


| Unité logique | LUN 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

* Adresse IP du serveur Red Hat OpenShift Virtualization sur le port 443 via l'API REST
* Nom d'utilisateur et mot de passe en lecture seule
* RHEV Version 3.0+




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP du serveur RHEV | Adresse IP du système de stockage 


| Nom d'utilisateur | Nom d'utilisateur avec privilèges d'administrateur 


| Mot de passe pour le compte privilégié administrateur | Mot de passe 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port de communication HTTPS | Port utilisé pour la communication HTTPS avec RHOV 


| Intervalle d'interrogation de l'inventaire (min) | La valeur par défaut est de 20 minutes. 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
