---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: Configuration du collecteur de données DELL EMC Celerra. 
---
= Collecteur de données DELL EMC VNX File (anciennement Celerra Unified Storage System)
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Ce collecteur de données acquiert des informations d'inventaire à partir du système de stockage de fichiers VNX.  Pour la configuration, ce collecteur de données nécessite l'adresse IP des processeurs de stockage ainsi qu'un nom d'utilisateur et un mot de passe en lecture seule.



== Terminologie

Data Infrastructure Insights acquiert les informations d’inventaire suivantes à partir du collecteur de données de fichiers VNX.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Serveur réseau Celerra/Pool de stockage Celerra | Piscine de stockage 


| Système de fichiers | Volume interne 


| Déplaceur de données | Contrôleur 


| Système de fichiers monté sur un dispositif de transfert de données | Partage de fichiers 


| Exportations CIFS et NFS | Partager 


| Volume du disque | LUN principal 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

Vous avez besoin des éléments suivants pour configurer ce collecteur de données :

* L'adresse IP du processeur de stockage
* Nom d'utilisateur et mot de passe en lecture seule
* Port SSH 22




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP du fichier VNX | Adresse IP ou nom de domaine complet du périphérique de fichier VNX 


| Nom d'utilisateur | Nom utilisé pour se connecter au périphérique de fichier VNX 


| Mot de passe | Mot de passe utilisé pour se connecter au périphérique de fichier VNX 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (minutes) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 20 minutes. 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Erreur : Impossible de continuer pendant la mise à jour de DART | Solution possible : mettez en pause le collecteur de données et attendez que la mise à niveau de DART soit terminée avant de tenter une autre demande d’acquisition. 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
