---
sidebar: sidebar 
permalink: task_query_copy_table_values.html 
summary: 'Vous pouvez copier des valeurs d"une table vers le presse-papiers pour les utiliser dans d"autres applications.' 
keywords: query, queries, copy, values, clipboard 
---
= Copie des valeurs du tableau
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Vous pouvez copier les valeurs des tableaux dans le presse-papiers pour les utiliser dans les zones de recherche ou d'autres applications.

.À propos de cette tâche
Il existe deux méthodes que vous pouvez utiliser pour copier des valeurs de tables ou des résultats de requête dans le presse-papiers.

.Étapes
. Méthode 1 : Mettez en surbrillance le texte souhaité avec la souris, copiez-le et collez-le dans les champs de recherche ou d'autres applications.
. Méthode 2 : pour les champs à valeur unique, passez la souris sur le champ et cliquez sur l’icône du presse-papiers qui apparaît.  La valeur est copiée dans le presse-papiers pour être utilisée dans les champs de recherche ou d'autres applications.
+
Notez que seules les valeurs qui sont des liens vers des actifs peuvent être copiées à l’aide de cette méthode.  Seuls les champs qui incluent des valeurs uniques (c'est-à-dire non des listes) ont l'icône de copie.


