---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Configuration du collecteur de données Red Hat Virtualization. 
---
= Collecteur de données de virtualisation Red Hat
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise le collecteur de données Red Hat Virtualization pour collecter des données d'inventaire à partir de charges de travail Linux et Microsoft Windows virtualisées.



== Terminologie

Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour l’actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque | Disque virtuel 


| Hôte | Hôte 


| Machine virtuelle | Machine virtuelle 


| Domaine de stockage | Magasin de données 


| Unité logique | LUN 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

* Adresse IP du serveur RHEV sur le port 443 via l'API REST
* Nom d'utilisateur et mot de passe en lecture seule
* RHEV Version 3.0+




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP du serveur RHEV | Adresse IP du système de stockage 


| Nom d'utilisateur | Nom d'utilisateur avec privilèges d'administrateur 


| Mot de passe pour le compte privilégié administrateur | Mot de passe 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port de communication HTTPS | Port utilisé pour la communication HTTPS vers RHEV 


| Intervalle d'interrogation de l'inventaire (min) | La valeur par défaut est de 20 minutes. 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
