---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: Configuration du collecteur de données DELL EMC RecoverPoint. 
---
= Collecteur de données Dell EMC RecoverPoint
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le principal cas d’utilisation du collecteur de données EMC RecoverPoint est de découvrir les relations de réplication de volume à volume que l’appliance de stockage RecoverPoint facilite.  Ce collecteur découvrira également l’appliance Recoverpoint elle-même.  Veuillez noter que Dell/EMC vend une solution de sauvegarde VMware pour les machines virtuelles - « RecoverPoint pour machines virtuelles » - qui n'est pas prise en charge par ce collecteur.

Pour la configuration, le collecteur de données nécessite l'adresse IP des processeurs de stockage ainsi qu'un nom d'utilisateur et un mot de passe en lecture seule.

Le collecteur de données EMC RecoverPoint rassemble les relations de réplication de volume à volume que RecoverPoint coordonne sur d'autres baies de stockage.  Data Infrastructure Insights affiche une baie de stockage pour chaque cluster RecoverPoint et collecte des données d’inventaire pour les nœuds et les ports de stockage sur ce cluster.  Aucune donnée de pool de stockage ou de volume n'est collectée.



== Exigences

Les informations suivantes sont requises pour configurer ce collecteur de données :

* Adresse IP ou nom de domaine complet du processeur de stockage
* Nom d'utilisateur et mot de passe en lecture seule
* Accès à l'API REST via le port 443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse de RecoverPoint | Adresse IP ou nom de domaine complet du cluster RecoverPoint 


| Nom d'utilisateur | Nom d'utilisateur pour le cluster RecoverPoint 


| Mot de passe | Mot de passe utilisé pour le cluster RecoverPoint 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port TCP utilisé pour se connecter au cluster Recoverpoint 


| Intervalle d'interrogation d'inventaire (minutes) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 20 minutes. 


| Clusters exclus | Liste séparée par des virgules d'ID ou de noms de cluster à exclure lors de l'interrogation. 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
