---
sidebar: sidebar 
permalink: task_create_annotation.html 
keywords: annotations, annotation rules, manual annotations, 
summary: Comment créer une annotation. 
---
= Utilisation des annotations
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous créez des annotations et les attribuez aux ressources que vous surveillez.  Les annotations sont des notes qui fournissent des informations sur un actif, telles que l'emplacement physique, la fin de vie, le niveau de stockage ou les niveaux de service de volume.



== Définition des annotations

À l’aide d’annotations, vous pouvez ajouter des données personnalisées spécifiques à votre entreprise qui correspondent aux besoins de votre entreprise aux actifs.  Bien que Data Infrastructure Insights fournisse un ensemble d'annotations par défaut, telles que le cycle de vie de l'actif (anniversaire ou fin de vie), l'emplacement du bâtiment ou du centre de données et le niveau, vous souhaiterez peut-être afficher les données d'autres manières.

Les données des annotations personnalisées complètent les données de l'appareil déjà collectées, telles que le fabricant du commutateur, le nombre de ports et les statistiques de performances.  Les données que vous ajoutez à l’aide d’annotations ne sont pas découvertes par Data Infrastructure Insights.

.Avant de commencer
* Énumérez toute terminologie industrielle à laquelle les données environnementales doivent être associées.
* Lister la terminologie de l'entreprise à laquelle les données d'environnement doivent être associées.
* Identifiez tous les types d’annotations par défaut que vous pourriez être en mesure d’utiliser.
* Identifiez les annotations personnalisées que vous devez créer.  Vous devez créer l’annotation avant de pouvoir l’attribuer à un actif.


Utilisez les étapes suivantes pour créer une annotation.

.Étapes
. Dans le menu Data Infrastructure Insights , cliquez sur *Observabilité > Enrichir > Annotations*
. Cliquez sur *+ Annotation* pour créer une nouvelle annotation.
. Saisissez un nom, une description et un type pour la nouvelle annotation.
+
Par exemple, saisissez ce qui suit pour créer une annotation de texte qui définit l’emplacement physique d’un actif dans le centre de données 4 :

+
** Saisissez un nom pour l'annotation, par exemple « Emplacement »
** Saisissez une description de ce que décrit l'annotation, par exemple « L'emplacement physique est le centre de données 4 »
** Saisissez le « type » d'annotation, par exemple « Texte ».






== Attribution manuelle d'annotations aux ressources

L'attribution d'annotations aux ressources vous aide à trier, regrouper et générer des rapports sur les ressources de manière pertinente pour votre entreprise.  Bien que vous puissiez attribuer automatiquement des annotations à des ressources d'un type particulier à l'aide de règles d'annotation, vous pouvez attribuer des annotations à une ressource individuelle à l'aide de sa page de ressource.

.Avant de commencer
* Vous devez avoir créé l'annotation que vous souhaitez attribuer.


.Étapes
. Connectez-vous à votre environnement Data Infrastructure Insights .
. Localisez l’actif auquel vous souhaitez appliquer l’annotation.
+
** Vous pouvez localiser des actifs en effectuant une requête, en choisissant parmi un widget de tableau de bord ou en effectuant une recherche.  Lorsque vous avez localisé l’actif souhaité, cliquez sur le lien pour ouvrir la page de destination de l’actif.


. Sur la page de l'actif, dans la section Données utilisateur, cliquez sur *+ Annotation*.
. La boîte de dialogue Ajouter une annotation s'affiche.
. Sélectionnez une annotation dans la liste.
. Cliquez sur Valeur et effectuez l’une des opérations suivantes, selon le type d’annotation que vous avez sélectionné :
+
** Si le type d’annotation est liste, date ou booléen, sélectionnez une valeur dans la liste.
** Si le type d’annotation est du texte, saisissez une valeur.


. Cliquez sur *Enregistrer*.


Si vous souhaitez modifier la valeur de l'annotation après l'avoir attribuée, cliquez sur le champ d'annotation et sélectionnez une valeur différente.  Si l'annotation est de type liste pour laquelle l'option _Ajouter de nouvelles valeurs à la volée_ est sélectionnée, vous pouvez saisir une nouvelle valeur en plus de sélectionner une valeur existante.



== Attribution d'annotations à l'aide de règles d'annotation

Pour attribuer automatiquement des annotations aux ressources en fonction de critères que vous définissez, vous configurez des règles d'annotation.  Data Infrastructure Insights attribue les annotations aux ressources en fonction de ces règles.  Data Infrastructure Insights fournit également deux règles d'annotation par défaut, que vous pouvez modifier selon vos besoins ou supprimer si vous ne souhaitez pas les utiliser.



=== Création de règles d'annotation

Au lieu d'appliquer manuellement des annotations à des ressources individuelles, vous pouvez appliquer automatiquement des annotations à plusieurs ressources à l'aide de règles d'annotation.  Les annotations définies manuellement sur les pages d'actifs individuelles ont priorité sur les annotations basées sur des règles lorsque Insight évalue les règles d'annotation.

.Avant de commencer
Vous devez avoir créé une requête pour la règle d’annotation.

.À propos de cette tâche
Bien que vous puissiez modifier les types d'annotations pendant que vous créez les règles, vous devez avoir défini les types à l'avance.

.Étapes
. Cliquez sur *Gérer > Règles d'annotation*
+
La page Règles d’annotation affiche la liste des règles d’annotation existantes.

. Cliquez sur *+ Ajouter*.
. Procédez comme suit :
+
.. Dans la case *Nom*, saisissez un nom unique qui décrit la règle.
+
Ce nom apparaîtra dans la page Règles d’annotation.

.. Cliquez sur *Requête* et sélectionnez la requête utilisée pour appliquer l'annotation aux ressources.
.. Cliquez sur *Annotation* et sélectionnez l’annotation que vous souhaitez appliquer.
.. Cliquez sur *Valeur* et sélectionnez une valeur pour l’annotation.
+
Par exemple, si vous choisissez Anniversaire comme annotation, vous spécifiez une date pour la valeur.

.. Cliquez sur *Enregistrer*
.. Cliquez sur *Exécuter toutes les règles* si vous souhaitez exécuter toutes les règles immédiatement ; sinon, les règles sont exécutées à un intervalle régulier.



