---
sidebar: sidebar 
permalink: task_create_application.html 
summary: Vous définissez des applications que vous appliquez ensuite aux actifs de votre locataire selon vos besoins. 
keywords: application, create application, 
---
= Création d'applications
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Pour suivre les données associées à des applications spécifiques exécutées sur votre locataire, vous pouvez définir les applications dans Data Infrastructure Insights.

.À propos de cette tâche
Data Infrastructure Insights vous permet de suivre les données des actifs associés aux applications pour des éléments tels que l'utilisation ou les rapports de coûts.

.Étapes
. Dans le menu Data Infrastructure Insights , cliquez sur *Observabilité > Enrichir > Applications*. Sélectionner
+
La boîte de dialogue Ajouter une application s'affiche.

. Entrez un nom unique pour l'application.
. Sélectionnez une priorité pour l'application.
. Cliquez sur *Enregistrer*.


Après avoir défini une application, elle peut être affectée à des actifs.



== Affectation d'applications à des actifs

Cette procédure attribue l’application à un hôte à titre d’exemple.  Vous pouvez attribuer un hôte, une machine virtuelle, un volume ou des volumes internes à une application.

.Étapes
. Localisez l'actif auquel vous souhaitez affecter l'application :
. Cliquez sur *Requêtes > +Nouvelle requête* et recherchez Hôte.
. Cliquez sur la case à cocher à gauche de l’hôte que vous souhaitez associer à l’application.
. Cliquez sur *Actions en masse > Ajouter une application*.
. Sélectionnez l’application à laquelle vous attribuez l’actif.


Toutes les nouvelles applications que vous attribuez remplacent toutes les applications de l’actif dérivées d’un autre actif.  Par exemple, les volumes héritent des applications des hôtes et lorsque de nouvelles applications sont attribuées à un volume, la nouvelle application a la priorité sur l'application dérivée.


NOTE: Pour les environnements comportant de grandes quantités d'actifs associés, l'héritage des affectations d'application à ces actifs peut prendre plusieurs minutes.  Veuillez prévoir plus de temps pour que l’héritage se produise si vous avez de nombreux biens liés.

.Après avoir terminé
Après avoir attribué l'hôte à l'application, vous pouvez attribuer les ressources restantes à l'application.  Pour accéder à la page de destination de l'application, cliquez sur *Gérer > Application* et sélectionnez l'application que vous avez créée.
