---
sidebar: sidebar 
permalink: task_cs_delete_agent.html 
keywords: agent, Workload Security, delete agent, Cloud Secure 
summary: Suppression des agents de sécurité de charge de travail 
---
= Suppression d'un agent de sécurité de charge de travail
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Lorsque vous supprimez un agent de sécurité de charge de travail, tous les collecteurs de données associés à l'agent doivent être supprimés en premier.



== Suppression d'un agent


IMPORTANT: La suppression d'un agent supprime tous les collecteurs de données associés à l'agent. Si vous prévoyez de configurer les collecteurs de données avec un autre agent, vous devez créer une sauvegarde des configurations Data Collector avant de supprimer l'agent.

.Avant de commencer
. Assurez-vous que tous les collecteurs de données associés à l'agent sont supprimés du portail de sécurité de la charge de travail.
+
Remarque : ignorez cette étape si tous les collecteurs associés sont à l'état ARRÊTÉ.



.Procédure de suppression d'un agent :
. SSH dans le VM agent et exécutez la commande suivante. Lorsque vous y êtes invité, entrez « y » pour continuer.
+
....
sudo /opt/netapp/cloudsecure/agent/install/cloudsecure-agent-uninstall.sh
Uninstall CloudSecure Agent? [y|N]:
....
. Cliquez sur *sécurité de la charge de travail > collecteurs > agents*
+
Le système affiche la liste des agents configurés.

. Cliquez sur le menu d'options de l'agent que vous supprimez.
. Cliquez sur *Supprimer*.
+
Le système affiche la page *Supprimer l'agent*.

. Cliquez sur *Supprimer* pour confirmer la suppression.

