---
sidebar: sidebar 
permalink: task_query_copy_table_values.html 
summary: Copiez les valeurs du tableau dans le presse-papiers en utilisant la sélection de texte ou la copie en un clic pour un transfert de données efficace vers les champs de recherche et les applications externes. 
keywords: query, queries, copy, values, clipboard 
---
= Copie des valeurs du tableau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Optimisez votre flux de travail en copiant directement les valeurs des tableaux dans le presse-papiers pour les utiliser dans vos recherches ou applications externes. Choisissez entre la sélection manuelle du texte ou la copie simplifiée en un clic pour les champs à valeur unique avec des liens vers des ressources.

.À propos de cette tâche
Il existe deux méthodes que vous pouvez utiliser pour copier des valeurs de tables ou des résultats de requête dans le presse-papiers.

.Étapes
. Méthode 1 : Mettez en surbrillance le texte souhaité avec la souris, copiez-le et collez-le dans les champs de recherche ou d'autres applications.
. Méthode 2 : pour les champs à valeur unique, passez la souris sur le champ et cliquez sur l’icône du presse-papiers qui apparaît.  La valeur est copiée dans le presse-papiers pour être utilisée dans les champs de recherche ou d'autres applications.
+
Notez que seules les valeurs qui sont des liens vers des actifs peuvent être copiées à l’aide de cette méthode.  Seuls les champs qui incluent des valeurs uniques (c'est-à-dire non des listes) ont l'icône de copie.


