---
sidebar: sidebar 
permalink: task_io_density_report_no_root.html 
summary: 'Lorsque vous recherchez une densité d"E/S élevée, vous souhaitez exclure les volumes racine.' 
keywords: NetApp, root volume, high I/O, 
---
= S'assurer que les rapports de densité d'E/S décrivent uniquement les volumes de données internes
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le volume racine NetApp contient des répertoires et des fichiers de configuration pour la gestion du système de stockage.  Lorsque vous recherchez une densité d'E/S élevée, vous souhaitez exclure ces volumes racine.

Lors de la surveillance de votre environnement, il est plus important de déterminer quels volumes de données internes produisent des nombres de densité d'E/S élevés.  Afin d'identifier avec précision uniquement les volumes de données, vous devez isoler les volumes internes NetApp des requêtes que vous utilisez pour surveiller la densité des E/S.

Ce guide décrit comment identifier facilement les agrégats racine NetApp , les isoler des résultats des requêtes de volume internes et créer des règles qui excluent tous les nouveaux agrégats racine NetApp lorsqu'ils sont ajoutés au système.  Les fonctionnalités Insight suivantes sont utilisées pour garantir que vos rapports de densité d'E/S sont dérivés de volumes de données internes :

* Une requête est créée pour identifier tous les agrégats racines NetApp surveillés par Insight.
* Une annotation est attribuée à chacun des agrégats racines NetApp .
* Une règle d’annotation est créée pour appliquer l’annotation aux nouveaux agrégats racines NetApp .


Les étapes de ce guide peuvent également être appliquées aux systèmes de stockage d’autres fournisseurs.  Vous devrez identifier les volumes qui contiennent des répertoires et des fichiers de configuration pour la gestion du système de stockage et utiliser des étapes similaires pour exclure ces volumes.



== Création d'une requête pour identifier les agrégats racines NetApp

Les requêtes fournissent une recherche à un niveau granulaire, en fonction de critères sélectionnés par l'utilisateur.  L’utilisation d’une requête vous permet de rechercher des volumes internes sur votre locataire qui contiennent l’agrégat racine NetApp .

.Étapes
. Créez une requête pour identifier les agrégats racines NetApp sur votre locataire : cliquez sur *Requêtes > Nouvelle requête > Sélectionner le type de ressource* (?)
. Cliquez sur *pool de stockage*
. Entrez le nom de l'agrégat racine
+
Cet exemple utilise « aggr0 » pour le nom.  Lors de la création d'un agrégat, seules les exigences suivantes concernant le nom doivent être respectées :

+
.. Il doit commencer soit par une lettre, soit par un trait de soulignement (_).
.. Il ne peut contenir que des lettres, des chiffres et des traits de soulignement.
.. Il peut contenir 250 caractères ou moins.  Dans la plupart des cas, l'agrégat est nommé aggr0, aggr_0 ou quelque chose de similaire.  Il peut être nécessaire d’effectuer un processus itératif pour identifier tous les agrégats racines NetApp sur votre locataire.


. Cliquez sur *Enregistrer* et entrez un nom pour la nouvelle requête.
+
Comme mentionné précédemment, il peut s’agir d’un processus itératif et nécessiter plusieurs requêtes pour identifier tous les agrégats racines NetApp .





== Créez une annotation pour les volumes racines renvoyés par vos requêtes

Les annotations sont des notes spécialisées que vous attribuez à vos ressources, vous permettant de filtrer les ressources par leurs annotations.  L'annotation que vous créez sera utilisée pour identifier les agrégats racines NetApp sur votre locataire et garantir qu'ils ne sont pas inclus dans un rapport spécifique.

.Avant de commencer
Vous devez avoir identifié tous les agrégats racines que vous souhaitez exclure du rapport « Densité d'E/S élevée ».

.Étapes
. Dans le menu Data Infrastructure Insights , cliquez sur *Gérer > Annotations*
. Cliquez sur *Ajouter*
+
.. Entrez le nom de l'annotation : *RootAggr*
.. Saisissez une description de l'annotation : *Supprimer l'agrégat racine du rapport « Densité d'E/S élevée »*
.. Entrez le type d'annotation : *Booléen*


. Cliquez sur *Enregistrer*




== Créez une règle d'annotation pour automatiser l'exclusion d'agrégats spécifiques de votre rapport de densité d'E/S

Au lieu d'appliquer manuellement des annotations à des ressources individuelles, vous pouvez appliquer automatiquement des annotations à plusieurs ressources à l'aide de règles d'annotation.  Les règles d'annotation sont basées sur les requêtes que vous créez et lorsqu'elles sont exécutées sur le système, elles ajoutent de nouveaux actifs aux ensembles d'actifs existants.  Lorsque ces ensembles d’actifs sont exclus d’un rapport, les nouveaux actifs sont également automatiquement exclus.

.Avant de commencer
Vous devez avoir créé et enregistré une requête qui identifie les agrégats racines NetApp que vous avez identifiés sur votre locataire.

.Étapes
. Dans la barre d’outils Data Infrastructure Insights , cliquez sur *Gérer > Règles d’annotation*.
. Cliquez sur *Ajouter*. La boîte de dialogue Ajouter une règle s'affiche.
+
.. Dans la zone Nom, saisissez un nom unique qui décrit la règle : *"RootAggrExclude"*
.. Cliquez sur Requête et sélectionnez la requête qu'Insight doit utiliser pour appliquer la règle d'annotation à : *"Aggregate0"*
.. Cliquez sur Annotation et sélectionnez : *« Exclure l'agrégation racine »*
.. Cliquez sur *Valeur* et entrez *Vrai*



