---
sidebar: sidebar 
permalink: task_identify_inactive_devices.html 
keywords: inactive, device, remove, removing, identify, identifying 
summary: 'L"identification des périphériques inactifs vous permet de choisir de les supprimer ou de les attribuer à un rôle actif.' 
---
= Identification des périphériques inactifs
:hardbreaks:
:allow-uri-read: 


[role="lead"]
L'identification des ressources dont vous disposez et de qui les utilise est essentielle pour « dimensionner correctement » et libérer l'infrastructure inutilisée. Vous pouvez facilement réaffecter ou désaffecter les ressources sous-utilisées et éviter ainsi les achats inutiles.

Procédez comme suit pour identifier les ressources inactives.

.Étapes
* Naviguez jusqu'à *observabilité > Explorer -> +Nouvelle requête métrique*.
* Sélectionnez _Storage_ dans la liste déroulante.
* Cliquez sur l'engrenage et ajoutez _isActive_ comme colonne.
+
Les lignes affichant une vérification sont actives. "X" indique les périphériques inactifs.



Pour supprimer des périphériques inactifs, sélectionnez simplement les périphériques à supprimer et, dans la liste déroulante *actions groupées*, sélectionnez _Supprimer les périphériques inactifs_.
