---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: Configuration du collecteur de données IBM SAN Volume Controller. 
---
= Configuration du collecteur de données IBM SAN Volume Controller
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le collecteur de données IBM SAN Volume Controller (SVC) collecte les données d'inventaire et de performances à l'aide de SSH, prenant en charge une variété de périphériques exécutant le système d'exploitation SVC.

La liste des appareils pris en charge comprend des modèles tels que le SVC, le v7000, le v5000 et le v3700.  Consultez la matrice de support de Data Infrastructure Insights pour connaître les modèles et les versions de micrologiciels pris en charge.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données IBM SVC.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Conduire | Disque 


| Cluster | Stockage 


| Nœud | Nœud de stockage 


| Groupe Mdisk | Piscine de stockage 


| Disque virtuel | Volume 


| Disque M | LUN et chemins d'accès backend 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



=== Exigences en matière d'inventaire

* Adresse IP de chaque cluster SVC
* Port 22 disponible
* Nom d'utilisateur et mot de passe en lecture seule




=== Exigences de performance

* Console SVC, obligatoire pour tout cluster SVC et requise pour le package de base de découverte SVC.
* Les informations d'identification nécessiteront un niveau d'accès administratif uniquement pour copier les fichiers de performances des nœuds de cluster vers le nœud de configuration.
* Activez la collecte de données en vous connectant au cluster SVC via SSH et en exécutant : _svctask startstats -interval 1_
+
Remarque : vous pouvez également activer la collecte de données à l’aide de l’interface utilisateur de gestion SVC.





== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresses IP de cluster | Adresses IP ou noms de domaine complets du stockage SVC 


| Nom d'utilisateur d'inventaire | Nom d'utilisateur pour l'interface de ligne de commande SVC 


| Mot de passe d'inventaire | Mot de passe pour l'interface de ligne de commande SVC 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 40 minutes. 


| Intervalle d'interrogation des performances (sec) | Intervalle entre les sondages de performance. La valeur par défaut est de 300 secondes. 


| Pour nettoyer les fichiers de statistiques vidés | Cochez cette case pour nettoyer les fichiers de statistiques vidés 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Erreur : « La commande ne peut pas être lancée car elle n’a pas été exécutée sur le nœud de configuration. » | La commande doit être exécutée sur le nœud de configuration. 
|===
Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Erreur : « La commande ne peut pas être lancée car elle n’a pas été exécutée sur le nœud de configuration. » | La commande doit être exécutée sur le nœud de configuration. 
|===
Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
