---
sidebar: sidebar 
permalink: task_cs_getting_started.html 
keywords: collectors, data collectors, configure, introduction, browsers, Cloud Secure 
summary: 'Déployez des agents de sécurité des charges de travail et des collecteurs de données pour surveiller l"activité des utilisateurs et détecter les menaces de sécurité.' 
---
= Premiers pas avec la sécurité des charges de travail
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Workload Security vous aide à surveiller l'activité des utilisateurs et à détecter les menaces de sécurité potentielles dans votre environnement de stockage.  Avant de pouvoir commencer la surveillance, vous devez configurer les agents, les collecteurs de données et les services d'annuaire afin d'établir les bases d'une surveillance de sécurité complète.

Le système Workload Security utilise un agent pour collecter les données d'accès des systèmes de stockage et les informations utilisateur des serveurs des services d'annuaire.

Vous devez configurer les éléments suivants avant de pouvoir commencer à collecter des données :

[cols="2*"]
|===


| Tâche | Informations connexes 


| Configurer un agent  a| 
link:concept_cs_agent_requirements.html["Exigences relatives aux agents"]

link:task_cs_add_agent.html["Ajouter un agent"]



| Configurer un connecteur d'annuaire utilisateur | link:task_config_user_dir_connect.html["Ajouter un connecteur d'annuaire utilisateur"] 


| Configurer les collecteurs de données | Cliquez sur *Sécurité de la charge de travail > Collecteurs*. Cliquez sur le collecteur de données que vous souhaitez configurer. Consultez la section « Référence du fournisseur de collecteurs de données » de la documentation pour obtenir des informations sur les collecteurs. 


| Créer des comptes utilisateurs | link:concept_user_roles.html["Gérer les comptes utilisateurs"] 
|===
Workload Security peut également s'intégrer à d'autres outils.  Par exemple,link:http://docs.netapp.com/us-en/cloudinsights/CloudInsights_CloudSecure_Splunk_integration_guide.pdf["voir ce guide"] sur l'intégration avec Splunk.
