---
sidebar: sidebar 
permalink: task_dc_ibm_cs.html 
keywords: data collector, IBM CS, CS Series 
summary: Configuration du collecteur de données IBM CS 
---
= Collecteur de données IBM CS
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise ce collecteur de données pour détecter les données d'inventaire et de performance des systèmes de stockage IBM CS.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes à partir du collecteur de données IBM CS. Pour chaque type de ressource acquis par Data Infrastructure Insights, la terminologie la plus courante est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme informations exploitables sur l'infrastructure de données 


| Pool de stockage | Pool de stockage 


| Conteneur | Volume interne 


| Conteneur | Partage de fichiers 


| Partage NFS | Partagez 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

* L'adresse IP des services de données externes pour le cluster
* Nom d'utilisateur et mot de passe administrateur
* Orifice 9440




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP externe prismes | L'adresse IP des services de données externes pour le cluster 


| Nom d'utilisateur | Nom d'utilisateur du compte Admin 


| Mot de passe | Mot de passe du compte admin 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port TCP utilisé pour la connexion à la baie IBM CS. La valeur par défaut est 9440. 


| Intervalle d'interrogation des stocks (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est 60 minutes. 


| Intervalle(s) d'interrogation de performance | Intervalle entre les sondages de performances. La valeur par défaut est 300 secondes. 
|===


== Dépannage

Vous trouverez des informations supplémentaires sur ce Data Collector sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
