---
sidebar: sidebar 
permalink: task_dc_huawei_oceanstor.html 
keywords: data collector, Huawei, OceanStor, Dorado 
summary: 'Configuration du collecteur de données Huawei OceanStor (REST/HTTPS).' 
---
= Collecteur de données Huawei OceanStor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise le collecteur de données Huawei OceanStor (REST/HTTPS) pour découvrir l'inventaire et les performances du stockage Huawei OceanStor et OceanStor Dorado.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire et de performances suivantes auprès de Huawei OceanStor.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Piscine de stockage | Piscine de stockage 


| Système de fichiers | Volume interne 


| Contrôleur | Nœud de stockage 


| Port FC (cartographié) | Carte des volumes 


| Initiateur FC hôte (mappé) | Masque de volume 


| Partage NFS/CIFS | Partager 


| Cible de liaison iSCSI | Nœud cible iSCSI 


| Initiateur de lien iSCSI | Nœud initiateur iSCSI 


| Disque | Disque 


| LUN | Volume 
|===


== Exigences

Les exigences suivantes sont requises pour configurer ce collecteur de données :

* Adresse IP de l'appareil
* Informations d'identification pour accéder au gestionnaire de périphériques OceanStor
* Le port 8088 doit être disponible




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP de l'hôte OceanStor | Adresse IP ou nom de domaine complet du gestionnaire de périphériques OceanStor 


| Nom d'utilisateur | Nom utilisé pour se connecter au gestionnaire de périphériques OceanStor 


| Mot de passe | Mot de passe utilisé pour se connecter au gestionnaire de périphériques OceanStor 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port TCP utilisé pour se connecter à OceanStor Device Manager.  La valeur par défaut est 8088. 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 60 minutes. 


| Intervalle d'interrogation des performances (sec). | La valeur par défaut est de 300 secondes. 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
