---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: 'Suivi des données à l"aide d"annotations.' 
---
= Définition des annotations
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous personnalisez des informations de l'infrastructure de données pour effectuer le suivi des données en fonction des besoins de votre entreprise, vous pouvez définir des notes spécialisées, appelées annotations, et les affecter à vos ressources.

Vous pouvez attribuer des annotations à des ressources avec des informations telles que la fin de vie des ressources, le data Center, l'emplacement de construction, le Tier de stockage ou le niveau de service du volume.

L'utilisation d'annotations pour vous aider à contrôler votre environnement comprend les tâches de haut niveau suivantes :

* Création ou modification de définitions pour tous les types d'annotation.
* Affichage des pages ASSET et association de chaque ressource à une ou plusieurs annotations.
+
Par exemple, si un bien est loué et que le bail expire dans un délai de deux mois, vous pouvez appliquer une annotation de fin de vie à l'actif. Cela permet d'éviter que d'autres personnes n'utilisent cette ressource pendant une période prolongée.

* Création de règles pour appliquer automatiquement des annotations à plusieurs ressources du même type.
* Filtrer les ressources par leurs annotations.




== Types d'annotation par défaut

Data Infrastructure Insights propose certains types d'annotations par défaut. Ces annotations peuvent être utilisées pour filtrer ou regrouper des données.

Vous pouvez associer des ressources à des types d'annotation par défaut tels que :

* Le cycle de vie des actifs, comme l'anniversaire, le coucher du soleil ou la fin de vie
* Informations de localisation sur un appareil, comme un centre de données, un bâtiment ou un sol
* Classification des actifs, par exemple par qualité (niveaux), par périphériques connectés (niveau du commutateur) ou par niveau de service
* État, comme les données fortement sollicitées (utilisation élevée)


Le tableau suivant répertorie les types d'annotations fournies par Data Infrastructure Insights.

[cols="30,53, 16"]
|===


| Types d'annotation | Description | Type 


| Alias | Nom convivial pour une ressource | Texte 


| Calculer le groupe de ressources | Affectation de groupe utilisée par le collecteur de données systèmes de fichiers hôte et VM | Liste 


| Data Center | Emplacement physique | Liste 


| Chaud | Dispositifs en utilisation intensive sur une base régulière ou au seuil de capacité | Booléen 


| Remarque | Commentaires associés à une ressource | Testez 


| Niveau de service | Un ensemble de niveaux de service pris en charge que vous pouvez attribuer aux ressources. Le fournit une liste d'options ordonnée pour les volumes internes, qtree et volumes. Modifiez les niveaux de service pour définir des règles de performances adaptées à différents niveaux. | Liste 


| Coucher de soleil | Seuil défini après lequel aucune nouvelle attribution ne peut être effectuée à ce périphérique. Utile pour les migrations planifiées et autres modifications réseau en attente. | Date 


| Niveau du commutateur | Options prédéfinies pour la configuration des catégories de commutateurs. Généralement, ces désignations restent pour la durée de vie du périphérique, bien que vous puissiez les modifier. Disponible uniquement pour les commutateurs. | Liste 


| Niveau | Peut être utilisé pour définir différents niveaux de service au sein de votre environnement. Les niveaux peuvent définir le type de niveau, comme la vitesse nécessaire (par exemple, Gold ou Silver). Cette fonctionnalité est disponible uniquement sur les volumes internes, les qtrees, les baies de stockage, les pools de stockage et les volumes. | Liste 


| Gravité de la violation | Classer (par exemple, majeur) d'une violation (par exemple, ports hôtes manquants ou redondance manquante), dans une hiérarchie de la plus haute à la plus faible importance. | Liste 
|===

NOTE: Alias, Centre de données, Chaud, Niveau de service, Coucher de soleil, Niveau de commutateur, Niveau et Gravité de la violation sont des annotations au niveau du système, que vous ne pouvez pas supprimer ou renommer ; vous ne pouvez modifier que leurs valeurs attribuées.



== Création d'annotations personnalisées

Ces annotations vous permettent d'ajouter des données personnalisées spécifiques à l'entreprise qui correspondent aux ressources de votre entreprise. Même si les informations sur l'infrastructure de données proposent un ensemble d'annotations par défaut, vous pouvez souhaiter afficher les données de différentes manières. Les données contenues dans des annotations personnalisées complètent les données déjà collectées, telles que le fabricant du stockage, le nombre de volumes et les statistiques de performance. Les données que vous ajoutez à l'aide d'annotations ne sont pas découvertes par Data Infrastructure Insights.

.Étapes
. Dans le menu informations sur l'infrastructure de données, cliquez sur *gérer > Annotations*.
+
La page Annotations affiche la liste des annotations.

. Cliquez sur *+Ajouter*
. Saisissez un *Nom* et *Description* de l'annotation.
+
Ces champs peuvent comporter jusqu'à 255 caractères.

. Cliquez sur *Type*, puis sélectionnez l'une des options suivantes qui représente le type de données autorisé dans cette annotation :


.Types d'annotation
* Booléen : Crée une liste déroulante avec les options « oui » et « non ». Par exemple, l'annotation « Rattaché directement » est booléenne.
* Date : cela crée un champ qui contient une date.  Par exemple, si l’annotation est une date, sélectionnez cette option.
* Liste : crée l’un des éléments suivants :
+
** Une liste déroulante fixe
+
Lorsque d’autres attribuent ce type d’annotation sur un appareil, ils ne peuvent pas ajouter plus de valeurs à la liste.

** Une liste déroulante flexible
+
Si vous sélectionnez l'option Ajouter de nouvelles valeurs à la volée lorsque vous créez cette liste, lorsque d'autres personnes attribuent ce type d'annotation sur un appareil, elles peuvent ajouter davantage de valeurs à la liste.



* Nombre : crée un champ dans lequel l'utilisateur qui affecte l'annotation peut entrer un nombre. Par exemple, si le type d'annotation est « sol », l'utilisateur peut sélectionner le type de valeur « nombre » et saisir le numéro d'étage.
* Texte : crée un champ permettant le texte libre. Par exemple, vous pouvez saisir "langue" comme type d'annotation, sélectionner "texte" comme type de valeur et entrer une langue comme valeur.



NOTE: Après avoir défini le type et enregistré vos modifications, vous ne pouvez pas modifier le type de l'annotation. Si vous devez modifier le type, vous devez supprimer l'annotation et en créer une nouvelle.

. Si vous sélectionnez liste comme type d'annotation, procédez comme suit :
+
.. Sélectionnez *Ajouter de nouvelles valeurs à la volée* si vous souhaitez pouvoir ajouter des valeurs supplémentaires à l'annotation sur une page de ressources, ce qui crée une liste flexible.
+
Par exemple, supposons que vous vous trouvez sur une page d'actifs et que l'actif comporte l'annotation City avec les valeurs Detroit, Tampa et Boston. Si vous avez sélectionné l'option *Ajouter de nouvelles valeurs à la volée*, vous pouvez ajouter des valeurs supplémentaires à la ville comme San Francisco et Chicago directement sur la page de la ressource au lieu de devoir aller à la page Annotations pour les ajouter. Si vous ne choisissez pas cette option, vous ne pouvez pas ajouter de nouvelles valeurs d'annotation lors de l'application de l'annotation. Cela crée une liste fixe.

.. Entrez une valeur et une description dans les champs *valeur* et *Description*.
.. Cliquez sur *+Ajouter+* pour ajouter des valeurs supplémentaires.
.. Cliquez sur l'icône Corbeille pour supprimer une valeur.


. Cliquez sur *Enregistrer*
+
Vos annotations apparaissent dans la liste de la page Annotations.



.Remarque sur les annotations booléennes
Lors du filtrage sur une annotation booléenne, les valeurs suivantes peuvent vous être présentées sur lesquelles filtrer :

* *Tout* : cela renverra _tous_ les résultats, y compris les résultats définis sur « Oui », « Non » ou pas définis du tout.
* *Oui* : renvoie uniquement les résultats « Oui ».  Notez que DII affiche « Oui » comme coche dans la plupart des tableaux.  Les valeurs peuvent être définies sur « Vrai », « Activé », etc. DII traite toutes ces valeurs comme « Oui ».
* *Non* : renvoie uniquement les résultats « Non ».  Notez que DII affiche « Non » sous la forme d’un « X » dans la plupart des tableaux.  Les valeurs peuvent être définies sur « Faux », « Désactivé », etc. DII traite toutes ces valeurs comme « Non ».
* *Aucun* : renvoie uniquement les résultats pour lesquels l'annotation n'a pas été définie du tout.  Également appelées valeurs « nulles ».


.Une fois que vous avez terminé
L'annotation est immédiatement disponible dans l'interface utilisateur.
