---
sidebar: sidebar 
permalink: task_dc_rubrik_cdm.html 
keywords: data collector, Rubrik, 
summary: Configuration du collecteur de données Rubrik CDM. 
---
= Collecteur de données Rubrik CDM
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise le collecteur de données Rubrik pour acquérir des données d'inventaire et de performances à partir des appliances de stockage Rubrik.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données Rubrik.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Cluster | Stockage, réserve de stockage 


| Nœud | Nœud de stockage 


| Disque | Disque 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour cette source de données.



== Exigences

Les éléments suivants sont requis pour configurer ce collecteur de données :

* L'unité d'acquisition Data Infrastructure Insights initiera les connexions au port TCP 443 vers le cluster Rubrik.  Un collecteur par cluster.
* Adresse IP du cluster Rubrik.
* Nom d'utilisateur et mot de passe du cluster.
* Adresse IP ou nom d'hôte du cluster Rubrik.
* Pour l’authentification de base, un nom d’utilisateur et un mot de passe pour le cluster.  Si vous préférez utiliser l'authentification basée sur le compte de service, vous avez besoin d'un compte de service, d'un secret et d'un ID d'organisation
* Exigence de port : HTTPS 443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| propriété intellectuelle | Adresse IP du cluster Rubrik 


| Nom d'utilisateur / Compte de service | Nom d'utilisateur pour le cluster 


| Mot de passe / Secret | Mot de passe pour le cluster 


| ID d'organisation pour le compte de service | Il doit s'agir de la chaîne complète comme « Organisation:::nnnnnn-nnnn..... ». 
|===


== Configuration avancée

[cols="2*"]
|===
| Intervalle d'interrogation de l'inventaire (min) | La valeur par défaut est 60 


| Intervalle d'interrogation des performances (sec) | La valeur par défaut est 300 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| J'ai reçu un message indiquant que plusieurs stockages ont été créés. | Vérifiez que le cluster est correctement configuré et que le collecteur pointe vers un seul cluster. 


| Le sondage échoue avec 400 [Bad Request]...ManagedId non valide.... | Vous avez renseigné le champ ID d'organisation avec une valeur, mais le cluster Rubrik ne considère PAS qu'il s'agit d'un ID d'organisation valide, malgré le message d'erreur de Rubrik le désignant comme un « ManagedId ». 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
