---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: Configuration du collecteur de données ECS. 
---
= Configuration du collecteur de données EMC ECS
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Ce collecteur de données acquiert les données d'inventaire et de performances des systèmes de stockage EMC ECS.  Pour la configuration, le collecteur de données nécessite une adresse IP ou un nom d'hôte du cluster ECS ainsi qu'un nom d'utilisateur et un mot de passe.


NOTE: Dell EMC ECS est mesuré à un taux différent entre les To bruts et les unités gérées.  Chaque 40 To de capacité ECS non formatée est facturé 1link:concept_subscribing_to_cloud_insights.html#pricing["Unité gérée (UG)"] .



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données ECS.  Pour chaque type d’actif acquis, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Cluster | Stockage 


| Locataire | Piscine de stockage 


| Seau | Volume interne 


| Disque | Disque 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

* Une adresse IP ou un nom d'hôte du cluster ECS
* Un nom d'utilisateur et un mot de passe pour le système ECS
* Port 4443 (HTTPS).  Nécessite une connectivité sortante au port TCP 4443 sur le système ECS.




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Hôte ECS | Adresse IP ou nom de domaine complet du système ECS 


| Port hôte ECS | Port utilisé pour la communication avec l'hôte ECS 


| Identifiant utilisateur ECS | Identifiant utilisateur pour ECS 


| Mot de passe | Mot de passe utilisé pour ECS 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | La valeur par défaut est de 360 minutes. 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Erreur : l’authentification de l’utilisateur a échoué. | Assurez-vous que vos informations d'identification pour cet appareil sont correctes. 
|===


=== Performances

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Erreur : les données collectées ne sont pas suffisantes. | * Vérifiez l'horodatage de la collecte dans le fichier journal et modifiez l'intervalle d'interrogation en conséquence * Attendez plus longtemps 


| Erreur : l’intervalle d’interrogation des performances est trop grand. | Vérifiez l'horodatage de la collecte dans le fichier journal ${logfile} et modifiez l'intervalle d'interrogation en conséquence 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
