---
sidebar: sidebar 
permalink: task_dc_na_7mode.html 
keywords: data collector, 7-mode, NetApp 
summary: Configuration du collecteur de données NetApp en mode 7. 
---
= NetApp Data ONTAP fonctionnant dans un collecteur de données en mode 7
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Pour les systèmes de stockage utilisant le logiciel Data ONTAP fonctionnant en mode 7, vous utilisez le collecteur de données en mode 7, qui utilise l'interface de ligne de commande pour obtenir des données de capacité et de performances.



== Terminologie

Data Infrastructure Insights acquiert les informations d’inventaire suivantes à partir du collecteur de données NetApp en mode 7.  Pour chaque type d’actif acquis, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :


NOTE: Ce collecteur de données estlink:task_getting_started_with_cloud_insights.html#useful-definitions["obsolète"] .

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque | Disque 


| Groupe de raid | Groupe de disques 


| Déposant | Stockage 


| Déposant | Nœud de stockage 


| Agrégat | Piscine de stockage 


| LUN | Volume 


| Volume | Volume interne 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

Vous avez besoin des éléments suivants pour configurer et utiliser ce collecteur de données :

* Adresses IP du contrôleur de stockage FAS et du partenaire.
* Port 443
* Un nom d'utilisateur et un mot de passe de niveau administrateur personnalisés pour le contrôleur et le contrôleur partenaire avec les capacités de rôle suivantes pour 7-Mode :
+
** "api-*" : utilisez ceci pour permettre à OnCommand Insight d'exécuter toutes les commandes API de stockage NetApp .
** "login-http-admin" : utilisez ceci pour permettre à OnCommand Insight de se connecter au stockage NetApp via HTTP.
** "security-api-vfiler" : utilisez ceci pour permettre à OnCommand Insight d'exécuter des commandes d'API de stockage NetApp pour récupérer les informations de l'unité vFiler.
** « cli-options » : utilisez ceci pour lire les options du système de stockage.
** « cli-lun » : accédez à ces commandes pour gérer les LUN.  Affiche l'état (chemin LUN, taille, état en ligne/hors ligne et état partagé) du LUN ou de la classe de LUN donné.
** "cli-df" : utilisez ceci pour afficher l'espace disque libre.
** "cli-ifconfig" : utilisez ceci pour afficher les interfaces et les adresses IP.






== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse du système de stockage | Adresse IP ou nom de domaine complet pour le système de stockage NetApp 


| Nom d'utilisateur | Nom d'utilisateur pour le système de stockage NetApp 


| Mot de passe | Mot de passe pour le système de stockage NetApp 


| Adresse du partenaire HA du cluster | Adresse IP ou nom de domaine complet pour le partenaire HA 


| Nom d'utilisateur du partenaire HA dans le cluster | Nom d'utilisateur du partenaire HA 


| Mot de passe du fichier partenaire HA dans le cluster | Mot de passe pour le partenaire HA 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 20 minutes. 


| Type de connexion | HTTPS ou HTTP, affiche également le port par défaut 


| Remplacer le port de connexion | Si vide, utilisez le port par défaut dans le champ Type de connexion, sinon entrez le port de connexion à utiliser 


| Intervalle d'interrogation des performances (sec) | Intervalle entre les sondages de performance. La valeur par défaut est de 300 secondes. 
|===


== Connexion des systèmes de stockage

Au lieu d'utiliser l'utilisateur administratif par défaut pour ce collecteur de données, vous pouvez configurer un utilisateur avec des droits administratifs directement sur les systèmes de stockage NetApp afin que ce collecteur de données puisse acquérir des données à partir des systèmes de stockage NetApp .

La connexion aux systèmes de stockage NetApp nécessite que l'utilisateur, spécifié lors de l'acquisition du pfiler principal (sur lequel existe le système de stockage), remplisse les conditions suivantes :

* L'utilisateur doit être sur vfiler0 (root filer/pfiler).
+
Les systèmes de stockage sont acquis lors de l'acquisition du pfiler principal.

* Les commandes suivantes définissent les capacités du rôle utilisateur :
+
** "api-*" : utilisez ceci pour permettre à Data Infrastructure Insights d'exécuter toutes les commandes API de stockage NetApp .
+
Cette commande est nécessaire pour utiliser le ZAPI.

** "login-http-admin" : utilisez ceci pour permettre à Data Infrastructure Insights de se connecter au stockage NetApp via HTTP.  Cette commande est nécessaire pour utiliser le ZAPI.
** "security-api-vfiler" : utilisez ceci pour permettre à Data Infrastructure Insights d'exécuter des commandes d'API de stockage NetApp pour récupérer les informations de l'unité vFiler.
** "cli-options" : pour la commande « options » et utilisé pour l'IP du partenaire et les licences activées.
** « cli-lun » : accédez à cette commande pour gérer les LUN.  Affiche l'état (chemin LUN, taille, état en ligne/hors ligne et état partagé) du LUN ou de la classe de LUN donné.
** "cli-df" : pour les commandes "df -s", "df -r", "df -A -r" et utilisé pour afficher l'espace libre.
** "cli-ifconfig" : pour la commande « ifconfig -a » et utilisé pour obtenir l'adresse IP du fichier.
** "cli-rdfile" : pour la commande "rdfile /etc/netgroup" et utilisé pour obtenir des groupes réseau.
** "cli-date" : pour la commande « date » et utilisé pour obtenir la date complète pour obtenir des copies instantanées.
** "cli-snap" : pour la commande « snap list » et utilisé pour obtenir des copies de snapshots.




Si les autorisations cli-date ou cli-snap ne sont pas fournies, l'acquisition peut se terminer, mais les copies Snapshot ne sont pas signalées.

Pour acquérir une source de données 7-Mode avec succès et ne générer aucun avertissement sur le système de stockage, vous devez utiliser l'une des chaînes de commande suivantes pour définir vos rôles d'utilisateur.  La deuxième chaîne répertoriée ici est une version simplifiée de la première :

* login-http-admin,api-*,security-api-vfile,cli-rdfile,cli-options,cli-df,cli-lun,cli-ifconfig,cli-date,cli-snap,_
* login-http-admin,api-* ,sécurité-api-vfile,cli-




== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Recevez une réponse HTTP 401 ou un code d'erreur ZAPI 13003 et ZAPI renvoie « Privilèges insuffisants » ou « non autorisé pour cette commande » | Vérifiez le nom d’utilisateur et le mot de passe, ainsi que les privilèges/autorisations de l’utilisateur. 


| Erreur « Échec de l'exécution de la commande » | Vérifiez si l'utilisateur dispose de l'autorisation suivante sur l'appareil : • api-* • cli-date • cli-df • cli-ifconfig • cli-lun • cli-operations • cli-rdfile • cli-snap • login-http-admin • security-api-vfiler Vérifiez également si la version ONTAP est prise en charge par Data Infrastructure Insights et vérifiez si les informations d'identification utilisées correspondent aux informations d'identification de l'appareil. 


| La version du cluster est < 8.1 | La version minimale prise en charge du cluster est 8.1.  Effectuez une mise à niveau vers la version minimale prise en charge. 


| ZAPI renvoie « le rôle du cluster n'est pas cluster_mgmt LIF » | AU doit communiquer avec l'IP de gestion du cluster.  Vérifiez l'IP et changez-la si nécessaire 


| Erreur : « Les filtres en mode 7 ne sont pas pris en charge » | Cela peut se produire si vous utilisez ce collecteur de données pour découvrir le filtre en mode 7.  Modifiez l'IP pour qu'elle pointe vers le fichier cdot à la place. 


| La commande ZAPI échoue après une nouvelle tentative | AU a un problème de communication avec le cluster.  Vérifiez le réseau, le numéro de port et l'adresse IP.  L'utilisateur doit également essayer d'exécuter une commande à partir de la ligne de commande à partir de la machine AU. 


| AU n'a pas réussi à se connecter à ZAPI | Vérifiez la connectivité IP/port et affirmez la configuration ZAPI. 


| AU n'a pas réussi à se connecter à ZAPI via HTTP | Vérifiez si le port ZAPI accepte le texte en clair.  Si AU tente d'envoyer du texte en clair à un socket SSL, la communication échoue. 


| La communication échoue avec SSLException | AU tente d'envoyer SSL à un port en texte clair sur un fichier.  Vérifiez si le port ZAPI accepte SSL ou utilisez un autre port. 


| Erreurs de connexion supplémentaires : la réponse ZAPI contient le code d'erreur 13001, « la base de données n'est pas ouverte ». Le code d'erreur ZAPI est 60 et la réponse contient « l'API ne s'est pas terminée à temps ». La réponse ZAPI contient « initialize_session() a renvoyé un environnement NULL ». Le code d'erreur ZAPI est 14007 et la réponse contient « le nœud n'est pas sain ». | Vérifiez le réseau, le numéro de port et l'adresse IP.  L'utilisateur doit également essayer d'exécuter une commande à partir de la ligne de commande à partir de la machine AU. 


| Erreur de délai d'attente du socket avec ZAPI | Vérifiez la connectivité du fichier et/ou augmentez le délai d'expiration. 


| Erreur « Les clusters en mode C ne sont pas pris en charge par la source de données en mode 7 » | Vérifiez l'IP et changez l'IP en un cluster en mode 7. 


| Erreur « Échec de la connexion à vFiler » | Vérifiez que les capacités d'acquisition d'utilisateur incluent au minimum les éléments suivants : api-* security-api-vfiler login-http-admin Confirmez que le filer exécute au minimum la version ONTAPI 1.7. 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
