---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: Collecteur de données IBM TotalStorage DS4000 
---
= Collecteur de données IBM TotalStorage DS4000
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Ce collecteur de données acquiert des informations d'inventaire et de performances à partir du système de stockage IBM DS4000.  Il existe deux configurations possibles (firmware 6.x et firmware 7.x+), et elles ont toutes deux les mêmes valeurs.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données IBM DS4000.  Pour chaque type d’actif acquis, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque | Disque 


| Groupe de volumes | Groupe de disques 


| Baie de stockage | Stockage 


| Contrôleur | Nœud de stockage 


| Groupe de volumes | Piscine de stockage 


| Volume | Volume 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

* Adresse IP de chaque baie DS5 ou FAStT
* Validation d'accès en pingant l'adresse IP des deux contrôleurs de la baie
* Exigences du port : 2463




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Liste séparée par des virgules des adresses IP des contrôleurs SANtricity de la baie | Adresses IP et/ou noms de domaine complets pour les contrôleurs de réseau 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | La valeur par défaut est de 30 minutes 


| Intervalle d'interrogation des performances jusqu'à 3 600 secondes | La valeur par défaut est de 300 secondes 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
