---
sidebar: sidebar 
permalink: task_dc_emc_vnx_unified.html 
keywords: data collector, VNX, EMC, Dell 
summary: Configuration du collecteur de données VNX. 
---
= Configuration du collecteur de données unifié Dell EMC VNX
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Pour la configuration, le collecteur de données Dell EMC VNX Unified (SSH) nécessite l'adresse IP de la station pilote ainsi qu'un nom d'utilisateur et un mot de passe en lecture seule.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes à partir de ce collecteur de données. Pour chaque type de ressource acquis par Data Infrastructure Insights, la terminologie la plus courante est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme informations exploitables sur l'infrastructure de données 


| Disque | Disque 


| Dossier de disques | Groupe de disques 


| Système de fichiers | Volume interne 


| Stockage | Stockage 


| Le processeur de stockage | Nœud de stockage 


| Pool de stockage, groupe RAID | Pool de stockage 


| LUN | Volumétrie 


| Data Mover | Contrôleur 


| Système de fichiers monté sur un mécanisme de déplacement des données | Partage de fichiers 


| Exports CIFS et NFS | Partagez 


| Volume de disque | LUN interne 
|===


== De formation

Vous devez disposer des éléments suivants pour configurer le collecteur de données VNX (SSH) :

* Adresse IP et informations d'identification du VNX vers la station pilote Celerra.
* Nom d'utilisateur et mot de passe en lecture seule.
* Le collecteur de données peut exécuter des commandes NaviCLI/NaviSecCLI contre la baie backend en utilisant les têtes NAS du système d'exploitation DART




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP du VNX | Adresse IP ou nom de domaine complet de la station de contrôle VNX 


| Nom d'utilisateur | Nom d'utilisateur de la station de contrôle VNX 


| Mot de passe | Mot de passe de la station pilote VNX 
|===


== Transpiration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation des stocks (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est 40 minutes. 


| Intervalle d'interrogation des performances (s). | Intervalle entre les sondages de performances. La valeur par défaut est 300 secondes. 
|===


== Dépannage

Vous trouverez des informations supplémentaires sur ce Data Collector sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
