---
sidebar: sidebar 
permalink: task_dc_huawei_oceanstor.html 
keywords: data collector, Huawei, OceanStor, Dorado 
summary: 'Configuration du collecteur de données Huawei OceanStor (REST/HTTPS)' 
---
= Collecteur de données Huawei OceanStor
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise le collecteur de données Huawei OceanStor (REST/HTTPS) pour détecter l'inventaire et les performances des systèmes de stockage Huawei OceanStor et OceanStor Dorado.



== Terminologie

Data Infrastructure Insights acquiert les informations suivantes sur l'inventaire et les performances à partir de Huawei OceanStor. Pour chaque type de ressource acquis par Data Infrastructure Insights, la terminologie la plus courante est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme informations exploitables sur l'infrastructure de données 


| Pool de stockage | Pool de stockage 


| Système de fichiers | Volume interne 


| Contrôleur | Nœud de stockage 


| Port FC (mappé) | Carte de volume 


| Initiateur FC hôte (mappé) | Masque de volume 


| Partage NFS/CIFS | Partagez 


| Cible de liaison iSCSI | Nœud cible iSCSI 


| Initiateur de liaison iSCSI | Nœud initiateur iSCSI 


| Disque | Disque 


| LUN | Volumétrie 
|===


== De formation

Les conditions suivantes sont requises pour configurer ce collecteur de données :

* Adresse IP du périphérique
* Informations d'identification permettant d'accéder au gestionnaire de périphériques OceanStor
* Le port 8088 doit être disponible




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP de l'hôte OceanStor | Adresse IP ou nom de domaine complet du OceanStor Device Manager 


| Nom d'utilisateur | Nom utilisé pour se connecter à OceanStor Device Manager 


| Mot de passe | Mot de passe utilisé pour se connecter à OceanStor Device Manager 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port TCP utilisé pour la connexion à OceanStor Device Manager. La valeur par défaut est 8088. 


| Intervalle d'interrogation des stocks (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est 60 minutes. 


| Intervalle d'interrogation des performances (s). | La valeur par défaut est 300 secondes. 
|===


== Dépannage

Vous trouverez des informations supplémentaires sur ce Data Collector sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
