---
sidebar: sidebar 
permalink: task_dc_emc_xio.html 
keywords: data collector, XtremeIO, EMC 
summary: Configuration du collecteur de données XtremeIO. 
---
= Collecteur de données Dell EMC XtremeIO
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le collecteur de données EMC XtremIO acquiert les données d'inventaire et de performances du système de stockage EMC XtremIO.



== Exigences

Pour configurer le collecteur de données EMC XtremIO (HTTP), vous devez disposer de :

* L'adresse de l'hôte du serveur de gestion XtremIO (XMS)
* Un compte avec des privilèges d'administrateur
* Accès au port 443 (HTTPS)




== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données EMC XtremIO.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez cette source de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque (SSD) | Disque 


| Cluster | Stockage 


| Contrôleur | Nœud de stockage 


| Volume | Volume 


| Carte LUN | Carte des volumes 


| Initiateur FC cible | Masque de volume 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour cette source de données.



== Exigences

* L'adresse IP de l'hôte du serveur de gestion XtremIO (XMS)
* Nom d'utilisateur et mot de passe administrateur pour XtremIO




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Hôte XMS | Adresse IP ou nom de domaine complet du serveur de gestion XtremIO 


| Nom d'utilisateur | Nom d'utilisateur pour le serveur de gestion XtremIO 


| Mot de passe | Mot de passe pour le serveur de gestion XtremIO 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port TCP utilisé pour se connecter au serveur de gestion XTremIO.  La valeur par défaut est 443. 


| Intervalle d'interrogation de l'inventaire (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 60 minutes. 


| Intervalle d'interrogation des performances (sec) | Intervalle entre les sondages de performance. La valeur par défaut est de 300 secondes. 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
