---
sidebar: sidebar 
permalink: task_query_assign_multiple_applications.html 
summary: Utilisez une requête pour attribuer plusieurs applications ou annotations à des objets ou pour en supprimer plusieurs. 
keywords: query, queries, application, annotation, multiple 
---
= Attribution ou suppression de plusieurs applications à des ressources ou à des applications multiples
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Vous pouvez affecter plusieurs link:task_create_application.html["en termes de latence"]applications à des ressources ou en supprimer en utilisant une requête au lieu de devoir les affecter ou les supprimer manuellement.


NOTE: Vous pouvez utiliser ces étapes pour ajouter ou supprimer de link:task_defining_annotations.html["annotations"]la même manière.

.Avant de commencer
Vous devez avoir déjà créé une requête qui trouve toutes les ressources à modifier.

.Étapes
. Cliquez sur *Explorer* et sélectionnez *requêtes métriques*.
+
La page requêtes s'affiche.

. Cliquez sur le nom de la requête qui trouve les ressources.
+
La liste des actifs associés à la requête s'affiche.

. Sélectionnez les ressources souhaitées dans la liste ou cliquez sur la case supérieure pour tout sélectionner.
+
La liste déroulante actions groupées s'affiche.

. Pour ajouter une application aux ressources sélectionnées, cliquez sur actions groupées et sélectionnez *Ajouter une application*.
. Sélectionnez une ou plusieurs applications.
+
Vous pouvez sélectionner plusieurs applications pour les hôtes, les volumes internes, les qtrees et les machines virtuelles, mais vous ne pouvez sélectionner qu'une seule application pour un volume ou un partage.

. Cliquez sur *Enregistrer*.
. Pour supprimer une application affectée aux actifs, cliquez sur actions groupées et sélectionnez *Supprimer l'application*.
. Sélectionnez l'application ou les applications que vous souhaitez supprimer.
. Cliquez sur *Supprimer*.


Toutes les nouvelles applications que vous attribuez remplacent toutes les applications de la ressource dérivées d'une autre ressource. Par exemple, les volumes héritent des applications des hôtes. Lorsque de nouvelles applications sont attribuées à un volume, la nouvelle application est prioritaire sur l'application dérivée.

Après avoir cliqué sur _Save_ sur un ajout en bloc ou sur _Remove_ sur une action de suppression en bloc, Data Infrastructure Insights vous informe que l'action prendra un certain temps. Vous pouvez ignorer ce message ; l'action se poursuit en arrière-plan.


NOTE: Pour les environnements disposant d'un grand nombre de ressources associées, l'héritage des affectations d'applications peut prendre plusieurs minutes. Veuillez laisser plus de temps à l'héritage si vous disposez de nombreux biens connexes.
