---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: Configuration du collecteur de données ECS. 
---
= Configuration du collecteur de données EMC ECS
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Ce collecteur de données acquiert les données d'inventaire et de performance des systèmes de stockage EMC ECS. Pour la configuration, le collecteur de données nécessite une adresse IP ou un nom d'hôte du cluster ECS ainsi qu'un nom d'utilisateur et un mot de passe.


NOTE: Dell EMC ECS est mesuré à un taux de To brut différent vers l'unité gérée. Tous les 40 To de capacité ECS non formatée sont facturés comme 1 link:concept_subscribing_to_cloud_insights.html#pricing["Unité gérée (UM)"].



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes à partir du collecteur de données ECS. Pour chaque type d'actif acquis, la terminologie la plus utilisée pour ce bien est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme informations exploitables sur l'infrastructure de données 


| Cluster | Stockage 


| Locataire | Pool de stockage 


| Godet | Volume interne 


| Disque | Disque 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

* Une adresse IP ou un nom d'hôte du cluster ECS
* Un nom d'utilisateur et un mot de passe pour le système ECS
* Port 4443 (HTTPS). Nécessite une connectivité sortante au port TCP 4443 sur le système ECS.




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Hôte ECS | Adresse IP ou nom de domaine complet du système ECS 


| Port hôte ECS | Port utilisé pour la communication avec l'hôte ECS 


| ID utilisateur ECS | ID utilisateur pour ECS 


| Mot de passe | Mot de passe utilisé pour ECS 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation des stocks (min) | La valeur par défaut est 360 minutes. 
|===


== Dépannage

Certaines choses à essayer si vous rencontrez des problèmes avec ce collecteur de données :



==== Inventaire

[cols="2*"]
|===
| Problème : | Essayer : 


| Erreur : l'authentification de l'utilisateur a échoué. | Assurez-vous que vos informations d'identification pour ce périphérique sont correctes. 
|===


==== Performances

[cols="2*"]
|===
| Problème : | Essayer : 


| Erreur : données collectées insuffisantes. | • Vérifiez l'horodatage de collecte dans le fichier journal et modifiez l'intervalle de vote en conséquence • attendez plus longtemps 


| Erreur : l'intervalle d'interrogation des performances est trop important. | Vérifiez l'horodatage de collecte dans le fichier journal ${logfile} et modifiez l'intervalle d'interrogation en conséquence 
|===
Des informations supplémentaires sont disponibles sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
