---
sidebar: sidebar 
permalink: task_dc_pure_flasharray.html 
keywords: data collector, Pure Storage, pure 
summary: Configuration du collecteur de données Pure Storage. 
---
= Collecteur de données Pure Storage FlashArray
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise le collecteur de données Pure Storage FlashArray pour collecter des données d'inventaire et de performances.



== Terminologie

Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour l’actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque (SSD) | Disque 


| Tableau | Stockage 


| Contrôleur | Nœud de stockage 


| Volume | Volume 


| Carte LUN | Carte des volumes 


| Initiateur, cible | Masque de volume 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

* Adresse IP du système de stockage
* Nom d'utilisateur et mot de passe pour le compte Administrateur du système de stockage Pure.
* Exigence de port : HTTP/HTTPS 80/443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP de l'hôte FlashArray | Adresse IP du système de stockage 


| Nom d'utilisateur | Nom d'utilisateur avec privilèges d'administrateur 


| Mot de passe pour le compte privilégié administrateur | Mot de passe 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Type de connexion | Choisissez HTTP ou HTTPS.  Affiche également le port par défaut. 


| Remplacer le port TCP | Si vide, utilisez le port par défaut dans le champ Type de connexion, sinon entrez le port de connexion à utiliser 


| Intervalle d'interrogation de l'inventaire (min) | La valeur par défaut est de 60 minutes 


| Intervalle d'interrogation des performances (sec) | La valeur par défaut est 300 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| « Identifiants de connexion non valides » avec les messages d'erreur « La politique ne le permet pas » ou « Vous n'êtes pas autorisé » | Valider le compte utilisateur et le mot de passe Pure via l'interface http Pure 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
