---
sidebar: sidebar 
permalink: task_dc_emc_unisphere_rest.html 
keywords: data collector, Unisphere, EMC 
summary: Configuration du collecteur de données Dell EMC Unisphere REST. 
---
= Configuration du collecteur de données REST Dell EMC Unisphere
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Ce collecteur de données acquiert les données d'inventaire et de performances des systèmes de gestion Dell EMC Unisphere pour PowerMax / Vmax 3.

Veuillez noter que Dell/EMC n'a pas introduit de statistiques par volume avant Unisphere 10.0 - ce collecteur de données prend en charge la version 9.2.0+, mais ne pourra pas collecter de statistiques de volume car elles n'existent pas.

Une instance Unisphere pour Vmax/PowerMax peut gérer une ou plusieurs baies de stockage Symmetrix Vmax 3 ou supérieures. Ce collecteur tentera par défaut de découvrir toutes celles qui sont « locales » pour cette instance Unisphere.  Si une instance Unisphere voit des tableaux « distants » (c'est-à-dire ceux connectés via la réplication SRDF), ils seront ignorés et pour les découvrir, vous devez créer un collecteur Unisphere supplémentaire dans Data Infrastructure Insights pointé vers l'instance Unisphere de ce site qui les voit comme locaux.

Pour la configuration, le collecteur de données nécessite une adresse IP/FQDN du serveur Unisphere, une connectivité TCP au port 8443, ainsi qu'un nom d'utilisateur et un mot de passe.



== Exigences

* Une adresse IP/nom de domaine complet du serveur Unisphere
* Nom d'utilisateur et mot de passe
* Port 8443.




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP du serveur Unisphere | Adresse IP ou nom de domaine complet du serveur Unisphere 


| Port Unisphere | La valeur par défaut est 8443 


| Nom d'utilisateur | Nom d'utilisateur pour le serveur Unisphere 


| Mot de passe | Mot de passe utilisé pour le serveur Unisphere 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | La valeur par défaut est de 40 minutes. 


| Intervalle d'interrogation des performances (sec) | Intervalle entre les sondages de performance. 


| Choisissez « Exclure » ou « Inclure » pour spécifier une liste | Spécifier s'il faut inclure ou exclure les machines virtuelles 


| Liste des périphériques de filtrage d'inventaire | Liste des machines virtuelles à filtrer (séparées par des virgules ou par des points-virgules si une virgule est utilisée dans la valeur) pour le filtrage 


| Intervalle de sondage des performances d'Unisphere (sec) | La valeur par défaut est de 300 secondes 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Erreur : l’authentification de l’utilisateur a échoué. | Assurez-vous que vos informations d'identification pour cet appareil sont correctes. 


| Inventaire Statut récent : Données inattendues récupérées - La baie a signalé 0 volume | Indique généralement un problème d'autorisation (et non d'authentification).  Assurez-vous que vos informations d'identification sont correctes et que le nom d'utilisateur a le pouvoir de répertorier tous les volumes et de voir leurs attributs. 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
