---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: Configurer le collecteur de données NetApp StorageGRID 
keywords: data collector, queries, create, storagegrid 
---
= Collecteur de données NetApp StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le collecteur de données NetApp StorageGRID prend en charge la collecte d'inventaire et de performances à partir des configurations StorageGRID .

[NOTE]
====
Pour fournir une mesure cohérente des droits DII sur tous les systèmes StorageGRID , quelle que soit la topologie et la configuration matérielles sous-jacentes, Data Infrastructure Insights utilise la capacité totale disponible (storagegrid_storage_utilization_total_space_bytes), au lieu de la capacité RAW basée sur la disposition du disque physique.

Pour les clients utilisant le modèle de licence basé sur la capacité, StorageGRID est mesuré comme un stockage « objet ».

Pour les clients utilisant le modèle de licence hérité (MU), StorageGRID est mesuré comme stockage secondaire, à un taux de 40 Tio pour 1 MU.

====


== Terminologie

Data Infrastructure Insights acquiert les informations d’inventaire suivantes auprès du collecteur NetApp StorageGRID .  Pour chaque type d’actif acquis, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| StorageGRID | Stockage 


| Nœud | Nœud 


| Locataire | Piscine de stockage 


| Seau | Volume interne 
|===


== Exigences

Voici les exigences pour la configuration de cette source de données :

* Adresse IP de l'hôte StorageGRID
* Un nom d'utilisateur et un mot de passe pour un utilisateur auquel les rôles Requête de métrique et Accès au locataire ont été attribués
* Port 443 (ou 8443 si configuré)




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP de l'hôte StorageGRID | Adresse IP virtuelle de gestion de l'appliance StorageGRID 


| Nom d'utilisateur | Nom utilisé pour se connecter à l'appliance StorageGRID 


| Mot de passe | Mot de passe utilisé pour se connecter à l'appliance StorageGRID 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | La valeur par défaut est de 60 minutes 


| Intervalle d'interrogation des performances (sec) | La valeur par défaut est de 900 secondes 
|===


== Authentification unique (SSO)

Lelink:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"] les versions du micrologiciel ont des versions d'API correspondantes ; l'API 3.0 et les versions plus récentes prennent en charge la connexion par authentification unique (SSO).

|===


| Version du micrologiciel | Version API | Prise en charge de l'authentification unique (SSO) 


| 11,1 | 2 | Non 


| 11,2 | 3,0 | Oui 


| 11,5 | 3,3 | Oui 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
