---
sidebar: sidebar 
permalink: task_dc_lenovo.html 
keywords: data collector,Lenovo, HX Series 
summary: Configuration du collecteur de données Lenovo. 
---
= Collecteur de données Lenovo
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise le collecteur de données Lenovo pour découvrir les données d'inventaire et de performances des systèmes de stockage Lenovo HX.

Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

* Adresse IP externe de Prism
* Nom d'utilisateur et mot de passe de l'administrateur
* Exigence de port TCP : 9440




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP externe de Prism | L'adresse IP des services de données externes pour le cluster 


| Nom d'utilisateur | Nom d'utilisateur pour le compte administrateur 


| Mot de passe | Mot de passe pour le compte administrateur 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port TCP utilisé pour se connecter au tableau.  La valeur par défaut est 9440. 


| Intervalle d'interrogation de l'inventaire (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 60 minutes. 


| Intervalle d'interrogation des performances (sec) | Intervalle entre les sondages de performance. La valeur par défaut est de 300 secondes. 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
