---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: Collecteur de données Amazon FSx for NetApp ONTAP 
---
= Collecteur de données Amazon FSx for NetApp ONTAP
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Ce collecteur de données acquiert des données d'inventaire et de performances à partir d' Amazon FSx for NetApp ONTAP.  Ce collecteur de données sera mis à disposition progressivement dans toutes les régions de service Data Infrastructure Insights .  Contactez votre commercial si vous ne voyez pas l’icône de ce collecteur dans votre environnement Data Infrastructure Insights .


NOTE: Ce collecteur Data Infrastructure Insights nécessite un utilisateur ONTAP avec un rôle _Filesystem-Scoped_.  Veuillez consulter l'AWSlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/roles-and-users.html["Rôles et règles"] documentation sur les options disponibles.  À l’heure actuelle, AWS ne prend en charge qu’un seul type de rôle d’utilisateur avec l’étendue du système de fichiers, à savoir _fsxadmin_.  Il s’agit du rôle approprié à utiliser pour le collecteur Data Infrastructure Insights .  L'utilisateur doit également avoir ces trois applications qui lui sont attribuées : http, ontapi, ssh.



== Terminologie

Data Infrastructure Insights acquiert les données d'inventaire et de performances du collecteur de données FSx- NetApp .  Pour chaque type d’actif acquis, la terminologie la plus courante utilisée pour l’actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Cluster | Stockage 


| LUN | Volume 


| Volume | Volume interne 
|===


== Terminologie FSx- NetApp

Les conditions suivantes s'appliquent aux objets ou références que vous pourriez trouver sur les pages de destination des ressources de stockage FSx- NetApp .  Bon nombre de ces termes s’appliquent également à d’autres collecteurs de données.



=== Stockage

* Modèle – Une liste délimitée par des virgules des noms de modèles uniques et discrets au sein de ce cluster.
* Fournisseur – AWS
* Numéro de série – Le numéro de série de la matrice.
* IP – il s’agira généralement de l’adresse IP ou du nom d’hôte tel que configuré dans la source de données.
* Capacité brute – somme de base 2 de tout le stockage SSD attribué au système de fichiers FSx.
* Latence – une représentation de ce que subissent les charges de travail de l'hôte, à la fois en lecture et en écriture.  Idéalement, Data Infrastructure Insights s’approvisionne directement en valeur, mais ce n’est souvent pas le cas.  Au lieu que le tableau propose cela, Data Infrastructure Insights effectue généralement un calcul pondéré par les IOP dérivé des statistiques des volumes internes individuels.
* Débit – agrégé à partir de volumes internes.  Gestion – cela peut contenir un lien hypertexte vers l’interface de gestion de l’appareil.  Créé par programmation par la source de données Data Infrastructure Insights dans le cadre du rapport d'inventaire.




=== Piscine de stockage

* Stockage – sur quelle baie de stockage ce pool réside.  Obligatoire.
* Type – une valeur descriptive issue d’une liste énumérée de possibilités.  Le plus souvent, il s’agira de « Agrégat » ou de « Groupe RAID ».
* Capacité – les valeurs ici sont la capacité logique utilisée, la capacité utilisable et la capacité logique totale, ainsi que le pourcentage utilisé sur ces valeurs.
* IOPS – la somme des IOPS de tous les volumes alloués sur ce pool de stockage.
* Débit – le débit total de tous les volumes alloués sur ce pool de stockage.




== Exigences

Les exigences suivantes sont requises pour configurer et utiliser ce collecteur de données :

* Vous devez avoir accès à un compte avec le rôle « fsxadmin », avec trois applications qui lui sont attribuées : ssh, ontapi, http
* Les détails du compte incluent le nom d'utilisateur et le mot de passe.
* Exigences du port : 443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| IP de gestion NetApp | Adresse IP ou nom de domaine complet du cluster NetApp 


| Nom d'utilisateur | Nom d'utilisateur pour le cluster NetApp 


| Mot de passe | Mot de passe pour le cluster NetApp 
|===


== Mesures avancées

Ce collecteur de données collecte les mesures avancées suivantes à partir du stockage FSx pour NetApp ONTAP :

* politique f
* nfsv3
* nfsv3:nœud
* nfsv4
* nfsv4_1
* nfsv4_1 : nœud
* nfsv4:nœud
* groupe_de_politiques
* qtree
* volume
* volume_de_charge_de_travail


Notez que les commandes CLI et API FSx récupèrent certaines valeurs de capacité que Data Infrastructure Insights ZAPI ne collecte pas. Par conséquent, certaines valeurs de capacité (telles que celles des pools de stockage) peuvent être différentes dans Data Infrastructure Insights de ce qu'elles sont sur FSx lui-même.



== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Recevez une réponse HTTP 401 ou un code d'erreur ZAPI 13003 et ZAPI renvoie « Privilèges insuffisants » ou « non autorisé pour cette commande » | Vérifiez le nom d’utilisateur et le mot de passe, ainsi que les privilèges/autorisations de l’utilisateur. 


| ZAPI renvoie « le rôle du cluster n'est pas cluster_mgmt LIF » | AU doit communiquer avec l'IP de gestion du cluster.  Vérifiez l'IP et changez-la si nécessaire 


| La commande ZAPI échoue après une nouvelle tentative | AU a un problème de communication avec le cluster.  Vérifiez le réseau, le numéro de port et l'adresse IP.  L'utilisateur doit également essayer d'exécuter une commande à partir de la ligne de commande à partir de la machine AU. 


| AU n'a pas réussi à se connecter à ZAPI via HTTP | Vérifiez si le port ZAPI accepte le texte en clair.  Si AU tente d'envoyer du texte en clair à un socket SSL, la communication échoue. 


| La communication échoue avec SSLException | AU tente d'envoyer SSL à un port en texte clair sur un fichier.  Vérifiez si le port ZAPI accepte SSL ou utilisez un autre port. 


| Erreurs de connexion supplémentaires : la réponse ZAPI contient le code d'erreur 13001, « la base de données n'est pas ouverte ». Le code d'erreur ZAPI est 60 et la réponse contient « l'API ne s'est pas terminée à temps ». La réponse ZAPI contient « initialize_session() a renvoyé un environnement NULL ». Le code d'erreur ZAPI est 14007 et la réponse contient « le nœud n'est pas sain ». | Vérifiez le réseau, le numéro de port et l'adresse IP.  L'utilisateur doit également essayer d'exécuter une commande à partir de la ligne de commande à partir de la machine AU. 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
