---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Configuration du collecteur de données Red Hat Virtualization. 
---
= Collecteur de données Red Hat Virtualization
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Data Infrastructure Insights utilise le collecteur de données Red Hat Virtualization pour collecter les données d'inventaire des charges de travail Linux et Microsoft Windows virtualisées.



== Terminologie

Pour chaque type de ressource acquise par Data Infrastructure Insights, la terminologie la plus courante est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme informations exploitables sur l'infrastructure de données 


| Disque | Disque virtuel 


| Hôte | Hôte 


| Ordinateur virtuel | Ordinateur virtuel 


| Domaine de stockage | Datastore 


| Unité logique | LUN 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

* Adresse IP du serveur RHEV sur le port 443 via l'API REST
* Nom d'utilisateur et mot de passe en lecture seule
* RHEV version 3.0+




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP du serveur RHEV | Adresse IP du système de stockage 


| Nom d'utilisateur | Nom d'utilisateur avec privilèges d'administrateur 


| Mot de passe du compte admin privilégié | Mot de passe 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port de communication HTTPS | Port utilisé pour la communication HTTPS vers RHEV 


| Intervalle d'interrogation des stocks (min) | La valeur par défaut est 20 minutes. 
|===


== Dépannage

Vous trouverez des informations supplémentaires sur ce Data Collector sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
