---
sidebar: sidebar 
permalink: task_dc_oracle_zfs.html 
keywords: data collector, Oracle, ZFS, storage applicance 
summary: Configuration du collecteur de données Oracle ZFS. 
---
= Collecteur de données Oracle ZFS Storage Appliance
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise le collecteur de données Oracle ZFS Storage Appliance pour collecter des données d'inventaire et de performances.



== Terminologie

Data Infrastructure Insights acquiert des informations d'inventaire avec le collecteur de données Oracle ZFS.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque (SSD) | Disque 


| Cluster | Stockage 


| Contrôleur | Nœud de stockage 


| LUN | Volume 


| Carte LUN | Carte des volumes 


| Initiateur, cible | Masque de volume 


| Partager | Volume interne 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour cette source de données.



== Exigences

* Noms d'hôte pour le contrôleur ZFS-1 et le contrôleur ZFS-2
* Nom d'utilisateur et mot de passe de l'administrateur
* Exigence de port : 215 HTTP/HTTPS




== Mesures de performance requises

Les appliances Oracle ZFS offrent aux administrateurs de stockage une grande flexibilité pour capturer les statistiques de performances.  Data Infrastructure Insights s'attend à ce que chaque contrôleur d'une paire à haute disponibilité soit configuré pour capturer les métriques suivantes :

* smb2.ops[partager]
* nfs3.ops[partager]
* nfs4.ops[partager]
* nfs4-1.ops[partager]


Si le contrôleur ne parvient pas à capturer tout ou partie de ces éléments, Data Infrastructure Insights risque de ne pas avoir, ou de sous-déclarer, la charge de travail sur les « volumes internes ».



== Configuration

[cols="2*"]
|===
| Champ | Description 


| Nom d'hôte du contrôleur ZFS-1 | Nom d'hôte pour le contrôleur de stockage 1 


| Nom d'hôte du contrôleur ZFS-2 | Nom d'hôte pour le contrôleur de stockage 2 


| Nom d'utilisateur | Nom d'utilisateur pour le compte d'utilisateur administrateur du système de stockage 


| Mot de passe | Mot de passe pour le compte utilisateur administrateur 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Type de connexion | HTTPS ou HTTP, affiche également le port par défaut 


| Remplacer le port de connexion | Si vide, utilisez le port par défaut dans le champ Type de connexion, sinon entrez le port de connexion à utiliser 


| Intervalle d'interrogation de l'inventaire | La valeur par défaut est de 60 secondes 


| Intervalle d'interrogation des performances (sec) | La valeur par défaut est 300. 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2a, 2a"]
|===
| Problème: | Essayez ceci: 


 a| 
« Informations de connexion non valides »
 a| 
valider le compte utilisateur et le mot de passe Zfs



 a| 
« La requête a échoué avec le statut 404 \https://.....:215/api/access/v1 »
 a| 
Votre tableau ZFS est peut-être trop ancien pour bénéficier de la prise en charge de l'API REST.  AK 2013.1.3.0 a été la première version du système d'exploitation ZFS compatible avec l'API REST, et tous les appareils ZFS ne peuvent pas être mis à niveau vers cette version.



 a| 
« Erreur de configuration » avec le message d'erreur « Le service REST est désactivé »
 a| 
Vérifiez que le service REST est activé sur cet appareil.



 a| 
« Erreur de configuration » avec le message d'erreur « Utilisateur non autorisé pour la commande »
 a| 
Cette erreur est probablement due au fait que certains rôles (par exemple, « advanced_analytics ») ne sont pas inclus pour l'utilisateur configuré.

L’application de la portée Analytics pour l’utilisateur avec un rôle en lecture seule peut supprimer l’erreur. Suivez ces étapes :

. Sur le système ZFs, depuis l'écran Configuration -> Utilisateurs, déplacez votre souris sur le rôle et double-cliquez pour autoriser la modification
. Sélectionnez « Analyse » dans le menu déroulant Portée.  Une liste des propriétés possibles apparaît.
. Cliquez sur la case à cocher la plus haute et elle sélectionnera les trois propriétés.
. Cliquez sur le bouton Ajouter sur le côté droit.
. Cliquez sur le bouton Appliquer en haut à droite de la fenêtre contextuelle.  La fenêtre contextuelle se fermera.


|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
