---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: Vous créez des règles d’annotation pour appliquer automatiquement des annotations à plusieurs ressources. 
keywords: annotate, annotation, rules 
---
= Création de règles d'annotation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser des règles d'annotation pour appliquer automatiquement des annotations à plusieurs ressources en fonction de critères que vous définissez.  Data Infrastructure Insights attribue les annotations aux ressources en fonction de ces règles.  Les annotations définies manuellement sur les pages d'actifs individuelles ont priorité sur les annotations basées sur des règles lorsque Cloud Insight évalue les règles d'annotation.

.Avant de commencer
Vous devez avoir créé une requête pour la règle d’annotation.

.Étapes
. Dans le menu Data Infrastructure Insights, cliquez sur *Gérer > Règles d'annotation*.
. Cliquez sur *+ Règle* pour ajouter une nouvelle règle d'annotation.
+
La boîte de dialogue Ajouter une règle s'affiche.

. Procédez comme suit :
+
.. Dans la case *Nom*, saisissez un nom unique qui décrit la règle.
+
Le nom apparaît dans la page Règles d’annotation.

.. Cliquez sur *Requête* et sélectionnez la requête que Data Infrastructure Insights utilise pour identifier les ressources auxquelles l'annotation s'applique.
.. Cliquez sur *Annotation* et sélectionnez l’annotation que vous souhaitez appliquer.
.. Cliquez sur *Valeur* et sélectionnez une valeur pour l’annotation.
+
Par exemple, si vous choisissez Anniversaire comme annotation, vous spécifiez une date pour la valeur.

.. Cliquez sur *Enregistrer*
.. Cliquez sur *Exécuter toutes les règles* si vous souhaitez exécuter toutes les règles immédiatement ; sinon, les règles sont exécutées à un intervalle régulier.
+

NOTE: Dans un environnement Data Infrastructure Insights de grande taille, vous remarquerez peut-être que l’exécution des règles d’annotation semble prendre un certain temps.  Cela est dû au fait que l'indexeur s'exécute en premier et doit se terminer avant d'exécuter les règles.  L'indexeur est ce qui donne à Data Infrastructure Insights la possibilité de rechercher ou de filtrer des objets et des compteurs nouveaux ou mis à jour dans vos données.  Le moteur de règles attend que l'indexeur termine sa mise à jour avant d'appliquer les règles.







== Modification des règles d'annotation

Vous pouvez modifier une règle d'annotation pour changer le nom de la règle, son annotation, la valeur de l'annotation ou la requête associée à la règle.

.Étapes
. Dans le menu Data Infrastructure Insights , cliquez sur *Gérer > Règles d'annotation*.
+
La page Règles d’annotation affiche la liste des règles d’annotation existantes.

. Localisez la règle d’annotation que vous souhaitez modifier.
+
Vous pouvez filtrer les règles d'annotation en saisissant une valeur dans la zone de filtre ou en cliquant sur un numéro de page pour parcourir les règles d'annotation par page.

. Cliquez sur l’icône de menu de la règle que vous souhaitez modifier.
. Cliquez sur *Modifier*
+
La boîte de dialogue Modifier la règle s'affiche.

. Modifiez le nom, l’annotation, la valeur ou la requête de la règle d’annotation.




== Modification de l'ordre des règles

Les règles d'annotation sont traitées du haut de la liste des règles vers le bas.  Pour modifier l’ordre dans lequel une règle est traitée, procédez comme suit :

.Étapes
. Cliquez sur l’icône de menu de la règle que vous souhaitez déplacer.
. Cliquez sur *Déplacer vers le haut* ou *Déplacer vers le bas* selon vos besoins jusqu'à ce que la règle apparaisse à l'emplacement souhaité.


Notez que lors de l'exécution de plusieurs règles qui mettent à jour la même annotation sur un actif, la première règle (exécutée de haut en bas) applique l'annotation et met à jour l'actif, puis la deuxième règle s'applique mais ne modifie aucune annotation déjà définie par la règle précédente.



== Suppression des règles d'annotation

Vous souhaiterez peut-être supprimer les règles d’annotation qui ne sont plus utilisées.

.Étapes
. Dans le menu Data Infrastructure Insights , cliquez sur *Gérer > Règles d'annotation*.
+
La page Règles d’annotation affiche la liste des règles d’annotation existantes.

. Localisez la règle d’annotation que vous souhaitez supprimer.
+
Vous pouvez filtrer les règles d'annotation en saisissant une valeur dans la zone de filtre ou en cliquant sur un numéro de page pour parcourir les règles d'annotation par page.

. Cliquez sur l’icône de menu de la règle que vous souhaitez supprimer.
. Cliquez sur *Supprimer*
+
Un message de confirmation s'affiche, vous demandant si vous souhaitez supprimer la règle.

. Cliquez sur *OK*

