---
sidebar: sidebar 
permalink: task_dc_aws_s3.html 
keywords: data collector, S3, Storage 
summary: 'Configuration d"AWS S3 en tant que collecteur de données de stockage.' 
---
= Configuration d'AWS S3 en tant que collecteur de données de stockage
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Les informations d'infrastructure de données utilisent AWS S3 en tant que collecteur de données de stockage pour acquérir des données d'inventaire et de performance à partir d'instances AWS S3.



== De formation

Pour collecter des données à partir d'AWS S3 en tant que périphériques de stockage, vous devez disposer des informations suivantes :

* Vous devez disposer de l'une des options suivantes :
+
** Le rôle *IAM* pour votre compte cloud AWS, si vous utilisez l'authentification par rôle IAM. Le rôle IAM s'applique uniquement si votre unité d'acquisition est installée sur une instance AWS.
** L'ID *IAM Access Key* et la clé d'accès secrète pour votre compte de cloud AWS, si vous utilisez l'authentification IAM Access Key.


* Vous devez disposer du privilège « organisation de liste »
* Port 443 HTTPS
* Il est possible de signalement des instances AWS S3 en tant que machine virtuelle ou (moins naturellement) d'un hôte. Les volumes EBS peuvent être signalés comme des virtualDisk utilisés par la machine virtuelle, ainsi qu'un datastore fournissant la capacité pour la virtuelleDisk.


Les clés d'accès comprennent un ID de clé d'accès (par exemple, AKIAIOSFONDN7EXAMPLE) et une clé d'accès secrète (par exemple, wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY). Vous utilisez des clés d'accès pour signer les demandes de programmation que vous créez à AWS si vous utilisez les opérations de kits de développement logiciel et D'API REST AWS ou Query. Ces clés sont fournies avec votre contrat Amazon.



== Configuration

Entrez les données dans les champs du collecteur de données conformément au tableau ci-dessous :

[cols="2*"]
|===
| Champ | Description 


| Région AWS | Choisissez la région AWS 


| Rôle IAM | À utiliser uniquement lorsqu'il est acquis sur un au dans AWS. Voir ci-dessous pour plus d'informations sur <<iam-role,Rôle IAM>>. 


| ID de clé d'accès IAM AWS | Entrez l'ID de clé d'accès IAM AWS. Obligatoire si vous n'utilisez pas le rôle IAM. 


| Clé d'accès secrète AWS IAM | Entrez la clé d'accès secrète IAM AWS. Obligatoire si vous n'utilisez pas le rôle IAM. 


| J'ai compris les factures AWS pour les demandes d'API | Vérifiez que vous savez qu'AWS vous facture pour les requêtes d'API formulées par l'interrogation Data Infrastructure Insights. 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Rôle inter-comptes | Rôle d'accès aux ressources de différents comptes AWS. 


| Intervalle d'interrogation des stocks (min) | La valeur par défaut est 60 


| Choisissez exclure ou inclure pour appliquer le filtrage des VM par balises | Indiquez s'il faut inclure ou exclure des VM par des étiquettes lors de la collecte de données. Si l'option "inclure" est sélectionnée, le champ clé d'étiquette ne peut pas être vide. 


| Intervalle d'interrogation des performances (s) | La valeur par défaut est 1800 
|===


== Clé d'accès IAM

Les clés d'accès sont des identifiants à long terme pour un utilisateur IAM ou l'utilisateur root du compte AWS. Les clés d'accès sont utilisées pour signer des demandes de programmation vers l'interface de ligne de commande AWS ou l'API AWS (directement ou à l'aide du kit de développement logiciel AWS).

Les clés d'accès sont constituées de deux parties : un ID de clé d'accès et une clé d'accès secrète. Lorsque vous utilisez l'authentification _IAM Access Key_ (par opposition à l'authentification _IAM role_), vous devez utiliser à la fois l'ID de clé d'accès et la clé d'accès secrète pour l'authentification des requêtes. Pour plus d'informations, consultez la documentation Amazon sur link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["Touches d'accès"].



== Rôle IAM

Lorsque vous utilisez l'authentification _IAM role_ (par opposition à l'authentification IAM Access Key), vous devez vous assurer que le rôle que vous créez ou spécifiez dispose des autorisations appropriées nécessaires pour accéder à vos ressources.

Par exemple, si vous créez un rôle IAM nommé _InstanceS3ReadOnly_, vous devez configurer la règle pour accorder l'autorisation d'accès à la liste en lecture seule S3 à toutes les ressources S3 pour ce rôle IAM. En outre, vous devez accorder l'accès STS (Security Token Service) pour que ce rôle soit autorisé à assumer des comptes croisés de rôles.

Une fois que vous avez créé un rôle IAM, vous pouvez le rattacher à une nouvelle instance S3 ou à toute instance S3 existante.

Une fois le rôle IAM _InstanceS3ReadOnly_ à une instance S3, vous pouvez récupérer les informations d'identification temporaires via les métadonnées de l'instance par le nom de rôle IAM et les utiliser pour accéder aux ressources AWS par toute application exécutée sur cette instance S3.

Pour plus d'informations, reportez-vous au document Amazon sur link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html["Rôles IAM"].

Remarque : le rôle IAM ne peut être utilisé que lorsque l'unité d'acquisition est exécutée dans une instance AWS.



== Mappage des balises Amazon avec les annotations Data Infrastructure Insights

Le collecteur de données AWS S3 en tant que stockage inclut une option qui vous permet de remplir les annotations Data Infrastructure Insights avec des balises configurées sur S3. Les annotations doivent être nommées exactement comme les balises AWS. Data Infrastructure Insights remplit toujours les annotations de type texte portant le même nom et fera une « meilleure tentative » pour remplir les annotations d'autres types (nombre, booléen, etc.). Si votre annotation est de type différent et que le collecteur de données ne parvient pas à la remplir, il peut être nécessaire de supprimer l'annotation et de la recréer en tant que type de texte.

AWS est sensible à la casse, tandis que Data Infrastructure Insights n'est pas sensible à la casse. Par conséquent, si vous créez une annotation nommée « PROPRIÉTAIRE » dans Data Infrastructure Insights et des balises nommées « PROPRIÉTAIRE », « propriétaire » et « propriétaire » dans S3, toutes les variations S3 de « propriétaire » seront mappées sur l'annotation « PROPRIÉTAIRE » DE Cloud Insight.



== Collecte depuis les comptes enfants AWS

Data Infrastructure Insights prend en charge la collecte de comptes enfants pour AWS dans un collecteur de données AWS unique. La configuration de cette collection est effectuée dans l'environnement AWS :

* Vous devez configurer chaque compte enfant pour qu'il dispose d'un rôle AWS qui permet à l'ID de compte principal d'accéder aux informations S3 à partir du compte enfants.
* Chaque compte enfant doit avoir le nom du rôle configuré comme la même chaîne.
* Entrez cette chaîne de nom de rôle dans la section Data Infrastructure Insights AWS Data Collector *Advanced Configuration*, dans le champ *Cross account role*.
* Le compte sur lequel le collecteur est installé doit disposer de _déléguer l'accès administrateur_ Privileges. Pour link:https://docs.aws.amazon.com/accounts/latest/reference/using-orgs-delegated-admin.html["Documentation AWS"]plus d'informations, reportez-vous à la section.


Meilleure pratique : il est fortement recommandé d'attribuer la politique AWS prédéfinie _Amazon S3ReadOnlyAccess_ au compte principal S3. En outre, l'utilisateur configuré dans la source de données doit avoir au moins la stratégie prédéfinie _AWOrganiztionsReadOnlyAccess_, afin d'interroger AWS.

Pour plus d'informations sur la configuration de votre environnement afin que des informations sur l'infrastructure de données puissent être collectées à partir de comptes enfants AWS, consultez les documents suivants :

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["Tutoriel : déléguer l'accès aux comptes AWS à l'aide des rôles IAM"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["Configuration AWS : accès à un utilisateur IAM dans un autre compte AWS dont vous disposez"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["Création d'un rôle pour déléguer des autorisations à un utilisateur IAM"]



== Dépannage

Vous trouverez des informations supplémentaires sur ce Data Collector sur la link:concept_requesting_support.html["Assistance"] page ou dans le link:reference_data_collector_support_matrix.html["Matrice de prise en charge du Data Collector"].
