---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Configuration du collecteur de données Red Hat Virtualization. 
---
= Collecteur de données de virtualisation Red Hat
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le collecteur de données DII pour Red Hat Virtualization prend également en charge le projet open source oVirt, et Oracle Linux Virtualization Manager. Ce collecteur de données communique via une API REST avec l’interface HTTPS du poste de gestion.



== Terminologie

Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour l’actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque | Disque virtuel 


| Hôte | Hôte 


| Machine virtuelle | Machine virtuelle 


| Domaine de stockage | Magasin de données 


| Unité logique | LUN 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

* Adresse IP/nom d'hôte du serveur RHV/oVirt/OLVM sur le port 443 via l'API REST
* Nom d'utilisateur et mot de passe en lecture seule
* RHV Version 3.0+/Ovirt 4.0+/OLVM 4.0+




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP du serveur RHV/Ovirt/OLVM | Adresse IP de la station de gestion 


| Nom d'utilisateur | Nom d'utilisateur 


| Mot de passe | Mot de passe 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port de communication HTTPS | Port utilisé pour la communication HTTPS vers RHEV 


| Intervalle d'interrogation de l'inventaire (min) | La valeur par défaut est de 20 minutes. 


| Performances de la machine virtuelle | Activer la collecte des performances 


| Intervalle d'interrogation des performances (sec) | La valeur par défaut est 900 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
