---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: Configuration du collecteur de données IBM Cleversafe. 
---
= Collecteur de données IBM Cleversafe
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise ce collecteur de données pour découvrir les données d'inventaire et de performances des systèmes de stockage IBM Cleversafe.


NOTE: IBM Cleversafe est mesuré à un taux différent entre les To bruts et les unités gérées.  Chaque 40 To de capacité IBM Cleversafe non formatée est facturé 1link:concept_subscribing_to_cloud_insights.html#pricing["Unité gérée (UG)"] .



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données IBM Cleversafe.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Piscine de stockage | Piscine de stockage 


| Récipient | Volume interne 


| Récipient | Partage de fichiers 


| Partage NFS | Partager 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

* L'adresse IP des services de données externes pour le cluster
* Nom d'utilisateur et mot de passe de l'administrateur
* Port 9440




== Configuration

[cols="2*"]
|===
| Champ | Description 


| IP du gestionnaire ou nom d'hôte | Adresse IP ou nom d'hôte du nœud de gestion 


| Nom d'utilisateur | Nom d'utilisateur pour le compte utilisateur avec le rôle de superutilisateur ou d'administrateur système 


| Mot de passe | Mot de passe pour le compte utilisateur avec le rôle de super utilisateur ou d'administrateur système 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation de l'inventaire (min) | Intervalle entre les sondages d'inventaire. 


| Délai d'expiration de la connexion HTTP (sec) | Délai d'expiration HTTP en secondes. 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
