---
sidebar: sidebar 
permalink: task_research_failed_collector.html 
keywords: data collector, changes, failures 
summary: Erreurs du collecteur de données 
---
= Recherche sur un collecteur de données en échec
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Si un collecteur de données présente un message d'échec et un impact élevé ou moyen, vous devez rechercher ce problème à l'aide de la page de résumé du collecteur de données avec ses informations liées.

Utilisez les étapes suivantes pour déterminer la cause des collecteurs de données défaillants.  Les messages d'échec du collecteur de données s'affichent dans le menu *Admin* et sur la page *Collecteurs de données installés*.

.Étapes
. Cliquez sur *Admin* > *Collecteurs de données* > *Collecteurs de données installés*.
. Cliquez sur le nom lié du collecteur de données défaillant pour ouvrir la page Résumé.
. Sur la page Résumé, consultez la zone Commentaires pour lire les notes qui pourraient avoir été laissées par un autre ingénieur qui pourrait également enquêter sur cette panne.
. Notez tous les messages de performance.
. Déplacez le pointeur de votre souris sur les segments du graphique de la chronologie des événements pour afficher des informations supplémentaires.
. Sélectionnez un message d'erreur pour un périphérique et affichez-le sous la chronologie des événements, puis cliquez sur l'icône Détails de l'erreur qui s'affiche à droite du message.
+
Les détails de l'erreur incluent le texte du message d'erreur, les causes les plus probables, les informations utilisées et les suggestions de ce qui peut être essayé pour corriger le problème.

. Dans la zone Appareils signalés par ce collecteur de données, vous pouvez filtrer la liste pour afficher uniquement les appareils qui vous intéressent, et vous pouvez cliquer sur le lien *Nom* d'un appareil pour afficher la page d'actif de cet appareil.
. Lorsque vous revenez à la page de résumé du collecteur de données, vérifiez la zone *Afficher les modifications récentes* au bas de la page pour voir si des modifications récentes auraient pu causer le problème.

