---
sidebar: sidebar 
permalink: task_dc_hds_nas.html 
keywords: data collector, HDS HNAS, HDS NAS 
summary: 'Configuration du collecteur de données HDS NAS (HNAS).' 
---
= Configuration du collecteur de données Hitachi Vantara NAS
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le collecteur de données Hitachi Vantara NAS est un collecteur de données d'inventaire et de configuration qui prend en charge la découverte de clusters NAS HDS.  Data Infrastructure Insights prend en charge la découverte des partages NFS et CIFS, des systèmes de fichiers (volumes internes) et des étendues (pools de stockage).



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données HNAS.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Étage | Groupe de disques 


| Cluster | Stockage 


| Nœud | Nœud de stockage 


| Portée | Piscine de stockage 


| Lecteur système | Lun arrière-plan 


| Système de fichiers | Volume interne 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

* Adresse IP de l'appareil
* Port 22, protocole SSH
* Nom d'utilisateur et mot de passe - niveau de privilège : Superviseur
* Remarque : ce collecteur de données est basé sur SSH. L'AU qui l'héberge doit donc pouvoir lancer des sessions SSH sur TCP 22 sur le HNAS lui-même ou sur l'unité de gestion des systèmes (SMU) à laquelle le cluster est connecté.




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Hôte HNAS | Adresse IP ou nom de domaine complet de l'hôte de gestion HNAS 


| Nom d'utilisateur | Nom d'utilisateur pour HNAS CLI 


| Mot de passe | Mot de passe utilisé pour HNAS CLI 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 30 minutes. 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| « Erreur de connexion » avec les messages d'erreur « Erreur de configuration du canal shell » ou « Erreur d'ouverture du canal shell » | Probablement causé par des problèmes de connectivité réseau ou par une mauvaise configuration de SSH.  Confirmer la connexion avec un autre client SSH 


| « Délai d'expiration » ou « Erreur lors de la récupération des données » avec les messages d'erreur « Commande : XXX a expiré. » | * Essayez la commande avec un autre client SSH * Augmentez le délai d'expiration 


| « Erreur de connexion » ou « Informations de connexion non valides » avec les messages d'erreur « Impossible de communiquer avec l'appareil : » | * Vérifier l'adresse IP * Vérifier le nom d'utilisateur et le mot de passe * Confirmer la connexion avec un autre client SSH 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
