---
sidebar: sidebar 
permalink: task_dc_emc_datadomain.html 
keywords: data collector, Data Domain, EMC, DELL 
summary: Configuration du collecteur de données DELL EMC Data Domain. 
---
= Collecteur de données DELL EMC Data Domain
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Ce collecteur de données collecte des informations d'inventaire et de performances à partir des systèmes de stockage de déduplication DELL EMC Data Domain.  Pour configurer ce collecteur de données, vous devez suivre des instructions de configuration et des recommandations d'utilisation spécifiques.



== Terminologie

Data Infrastructure Insights acquiert les informations d’inventaire suivantes auprès du collecteur de données Data Domain.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque | Disque 


| Tableau | Stockage 


| Port FC | Port 


| Système de fichiers | Volume interne 


| Quota | Quota 


| Partage NFS et CIFS | Partage de fichiers 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

Vous avez besoin des informations suivantes pour configurer ce collecteur de données :

* Adresse IP du périphérique Data Domain
* Nom d'utilisateur et mot de passe en lecture seule pour le stockage Data Domain
* Port SSH 22




== Configuration

[cols="2*"]
|===
| Champ | Description 


| adresse IP | L'adresse IP ou le nom de domaine complet de la baie de stockage Data Domain 


| Nom d'utilisateur | Le nom d'utilisateur pour la baie de stockage Data Domain 


| Mot de passe | Le mot de passe de la baie de stockage Data Domain 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire.  La valeur par défaut est 20. 


| Port SSH | Port de service SSH 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
