---
sidebar: sidebar 
permalink: task_cs_getting_started.html 
keywords: collectors, data collectors, configure, introduction, browsers , Cloud Secure 
summary: Quelques étapes simples vous permettront de commencer à utiliser Workload Security 
---
= Premiers pas avec la sécurité des charges de travail
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Certaines tâches de configuration doivent être effectuées avant de pouvoir commencer à utiliser Workload Security pour surveiller l'activité des utilisateurs.

Le système Workload Security utilise un agent pour collecter les données d'accès des systèmes de stockage et les informations utilisateur des serveurs des services d'annuaire.

Vous devez configurer les éléments suivants avant de pouvoir commencer à collecter des données :

[cols="2*"]
|===


| Tâche | Informations connexes 


| Configurer un agent  a| 
link:concept_cs_agent_requirements.html["Exigences relatives aux agents"]

link:task_cs_add_agent.html["Ajouter un agent"]

link:https://netapp.hubs.vidyard.com/watch/Lce7EaGg7NZfvCUw4Jwy5P?["*Vidéo* : Déploiement de l'agent"]



| Configurer un connecteur d'annuaire utilisateur | link:task_config_user_dir_connect.html["Ajouter un connecteur d'annuaire utilisateur"] link:https://netapp.hubs.vidyard.com/watch/NEmbmYrFjCHvPps7QMy8me?["*Vidéo* : Connexion à Active Directory"] 


| Configurer les collecteurs de données | Cliquez sur *Sécurité de la charge de travail > Collecteurs*. Cliquez sur le collecteur de données que vous souhaitez configurer.  Consultez la section Référence du fournisseur du collecteur de données de la documentation.link:https://netapp.hubs.vidyard.com/watch/YSQrcYA7DKXbj1UGeLYnSF?["*Vidéo* : Connexion ONTAP SVM"] 


| Créer des comptes utilisateurs | link:concept_user_roles.html["Gérer les comptes utilisateurs"] 


| Dépannage | link:https://netapp.hubs.vidyard.com/watch/Fs8N2w9wBtsFGrhRH9X85U?["*Vidéo* : Dépannage"] 
|===
Workload Security peut également s'intégrer à d'autres outils.  Par exemple,link:http://docs.netapp.com/us-en/cloudinsights/CloudInsights_CloudSecure_Splunk_integration_guide.pdf["voir ce guide"] sur l'intégration avec Splunk.
