---
sidebar: sidebar 
permalink: task_dc_ibm_cs.html 
keywords: data collector, IBM CS, CS Series 
summary: Configuration du collecteur de données IBM CS. 
---
= Collecteur de données IBM CS
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise ce collecteur de données pour découvrir les données d'inventaire et de performances des systèmes de stockage IBM CS.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données IBM CS.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Piscine de stockage | Piscine de stockage 


| Récipient | Volume interne 


| Récipient | Partage de fichiers 


| Partage NFS | Partager 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

* L'adresse IP des services de données externes pour le cluster
* Nom d'utilisateur et mot de passe de l'administrateur
* Port 9440




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP externe de Prism | L'adresse IP des services de données externes pour le cluster 


| Nom d'utilisateur | Nom d'utilisateur pour le compte administrateur 


| Mot de passe | Mot de passe pour le compte administrateur 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port TCP utilisé pour se connecter au tableau IBM CS.  La valeur par défaut est 9440. 


| Intervalle d'interrogation de l'inventaire (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 60 minutes. 


| Intervalle d'interrogation des performances (sec) | Intervalle entre les sondages de performance. La valeur par défaut est de 300 secondes. 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
