---
sidebar: sidebar 
permalink: task_dc_emc_vnx_unified.html 
keywords: data collector, VNX, EMC, Dell 
summary: Configuration du collecteur de données VNX. 
---
= Configuration du collecteur de données unifié Dell EMC VNX
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Pour la configuration, le collecteur de données Dell EMC VNX Unified (SSH) nécessite l'adresse IP de la station de contrôle ainsi qu'un nom d'utilisateur et un mot de passe en lecture seule.



== Terminologie

Data Infrastructure Insights acquiert les informations d’inventaire suivantes auprès de ce collecteur de données.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque | Disque 


| Dossier de disque | Groupe de disques 


| Système de fichiers | Volume interne 


| Stockage | Stockage 


| Processeur de stockage | Nœud de stockage 


| Pool de stockage, groupe RAID | Piscine de stockage 


| LUN | Volume 


| Déplaceur de données | Contrôleur 


| Système de fichiers monté sur un dispositif de transfert de données | Partage de fichiers 


| Exportations CIFS et NFS | Partager 


| Volume du disque | LUN principal 
|===


== Exigences

Vous avez besoin des éléments suivants pour configurer le collecteur de données VNX (SSH) :

* Adresse IP VNX et informations d'identification pour la station de contrôle Celerra.
* Nom d'utilisateur et mot de passe en lecture seule.
* Le collecteur de données est capable d'exécuter des commandes NaviCLI/NaviSecCLI sur le tableau principal en utilisant les têtes NAS DART OS




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP VNX | Adresse IP ou nom de domaine complet de la station de contrôle VNX 


| Nom d'utilisateur | Nom d'utilisateur pour la station de contrôle VNX 


| Mot de passe | Mot de passe pour la station de contrôle VNX 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 40 minutes. 


| Intervalle d'interrogation des performances (sec). | Intervalle entre les sondages de performance. La valeur par défaut est de 300 secondes. 
|===


== Dépannage

Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
