---
sidebar: sidebar 
permalink: task_dc_emc_vnx_block.html 
keywords: data collector, EMC, clariion, VNX block 
summary: 'Configuration du stockage en blocs DELL EMC VNX (anciennement CLARiiON).' 
---
= Collecteur de données Dell EMC VNX Block Storage (NaviCLI)
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise le collecteur de données Dell EMC VNX Block Storage (NaviSec) (anciennement CLARiiON) pour acquérir des données d'inventaire et de performances.



== Terminologie

Data Infrastructure Insights acquiert les informations d'inventaire suivantes à partir du collecteur de données EMC VNX Block Storage.  Pour chaque type d’actif acquis par Data Infrastructure Insights, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque | Disque 


| Stockage | Stockage 


| Processeur de stockage | Nœud de stockage 


| Ce pool, groupe RAID | Piscine de stockage 


| LUN | Volume 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour cette source de données.



== Exigences

Les exigences suivantes doivent être respectées pour pouvoir collecter des données :

* Une adresse IP de chaque processeur de stockage en bloc VNX
* Nom d'utilisateur et mot de passe Navisphere en lecture seule pour les baies de stockage en blocs VNX
* NaviSecCli doit être installé sur l'AU Data Infrastructure Insights
* Validation d'accès : exécutez NaviSecCLI à partir de l'AU Data Infrastructure Insights sur chaque tableau à l'aide du nom d'utilisateur et du mot de passe.
* Exigences portuaires : 80, 443
* La version de NaviSecCLI doit correspondre au code FLARE le plus récent sur votre baie
* Pour des performances optimales, la journalisation des statistiques doit être activée.




== Syntaxe de l'interface de ligne de commande NaviSphere

naviseccli.exe -h <adresse IP> -user <utilisateur> -password <mot de passe> -scope <portée, utiliser 0 pour la portée globale> -port <utiliser 443 par défaut> commande



== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP du stockage en bloc VNX | Adresse IP ou nom de domaine complet du stockage en blocs VNX 


| Nom d'utilisateur | Nom utilisé pour se connecter au périphérique de stockage en blocs VNX. 


| Mot de passe | Mot de passe utilisé pour se connecter au périphérique de stockage en blocs VNX. 


| Chemin CLI vers naviseccli.exe | Chemin complet vers le dossier contenant l'exécutable _naviseccli.exe_ 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire.  La valeur par défaut est 40 minutes. 


| Portée | La portée du client sécurisé.  La valeur par défaut est Global. 


| Intervalle d'interrogation des performances (sec) | Intervalle entre les sondages de performance. La valeur par défaut est de 300 secondes. 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2a, 2a"]
|===
| Problème: | Essayez ceci: 


 a| 
Erreur:

* L'agent ne fonctionne pas
* Impossible de trouver naviseccli
* Impossible d'exécuter une commande

 a| 
* Confirmez que NaviSphere CLI est installé sur l'unité d'acquisition Cloud Insight
* Vous n'avez pas sélectionné l'option « Utiliser un client sécurisé » dans l'assistant de configuration du collecteur de données et vous n'avez pas installé de version non sécurisée de Naviphere CLI.
* Confirmez que le répertoire d'installation de NaviSphere CLI est correct dans la configuration du collecteur de données
* Confirmez que l'adresse IP du stockage en bloc VNX est correcte dans la configuration du collecteur de données :
* De l'unité d'acquisition Data Infrastructure Insights :
+
** Ouvrir un CMD.
** Changez le répertoire vers le répertoire d'installation configuré
** Essayez d'établir une connexion avec le périphérique de stockage en bloc VNX en tapant « navicli -h {ip} getagent » (remplacez {ip} par l'IP réelle)






 a| 
Erreur : 4.29 emc235848 emc241018 getall Échec de l'analyse des informations d'alias d'hôte
 a| 
Cela est probablement dû à un problème de corruption FLARE 29 de la base de données de l'initiateur hôte sur la baie elle-même.  Voir les articles de la base de connaissances EMC : emc235848, emc241018.  Vous pouvez également vérifier https://now.netapp.com/Knowledgebase/solutionarea.asp?id=kb58128[]



 a| 
Erreur : impossible de récupérer les méta LUN.  Erreur lors de l'exécution de java -jar navicli.jar
 a| 
* Modifier la configuration du collecteur de données pour utiliser le client sécurisé (recommandé)
* Installez navicli.jar dans le chemin CLI vers navicli.exe OU naviseccli.exe
* Remarque : navicli.jar est obsolète à partir de la version 6.26 d'EMC Navisphere
* Le fichier navicli.jar peut être disponible sur \ http://powerlink.emc.com




 a| 
Erreur : les pools de stockage ne signalent pas les disques sur le processeur de service à l'adresse IP configurée
 a| 
Configurer le collecteur de données avec les deux adresses IP du processeur de service, séparées par une virgule



 a| 
Erreur : erreur de non-concordance de révision
 a| 
* Cela est généralement dû à la mise à jour du micrologiciel sur le périphérique de stockage en blocs VNX, mais pas à la mise à jour de l'installation de NaviCLI.exe.  Cela peut également être dû au fait d'avoir différents appareils avec des firmwares différents, mais une seule CLI installée (avec une version de firmware différente).
* Vérifiez que l’appareil et l’hôte exécutent tous deux des versions identiques du logiciel :
+
** À partir de l'unité d'acquisition Data Infrastructure Insights , ouvrez une fenêtre de ligne de commande
** Changez le répertoire vers le répertoire d'installation configuré
** Établissez une connexion avec l'appareil CLARiiON en tapant « navicli -h <ip> getagent »
** Recherchez le numéro de version sur les premières lignes.  Exemple : « Agent Rev : 6.16.2 (0.1) »
** Recherchez et comparez la version sur la première ligne.  Exemple : « Navisphere CLI Révision 6.07.00.04.07 »






 a| 
Erreur : Configuration non prise en charge – Aucun port Fibre Channel
 a| 
L'appareil n'est configuré avec aucun port Fibre Channel.  Actuellement, seules les configurations FC sont prises en charge.  Vérifiez que cette version/ce micrologiciel est pris en charge.

|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
