---
sidebar: sidebar 
permalink: task_config_telegraf_kubernetes.html 
keywords: telegraf 
summary: Collecteur de données pour Kubernetes 
---
= Collecteur de données : Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights utilise ce collecteur de données pour collecter les métriques Kubernetes Pod, Node et Container.



== Installation

Pour les instructions d'installation de Kubernetes, veuillez consulter lelink:task_config_telegraf_agent_k8s.html["Opérateur de surveillance Kubernetes"] page.



== À propos de Kube-state-metrics

L'opérateur de surveillance Kubernetes installe automatiquement kube-state-metrics ; aucune interaction de l'utilisateur n'est nécessaire.



=== Compteurs Kube-state-metrics

L'opérateur de surveillance NetApp Kubernetes extrait les compteurs kube-state-metrics répertoriés ci-dessous.  Vous trouverez plus de détails sur chaque compteur à l'adresse suivante : https://github.com/kubernetes/kube-state-metrics/tree/main/docs#exposed-metrics[] .

. Métriques DaemonSet
. Mesures de déploiement
. Métriques de l'espace de noms
. Métriques des nœuds
. Mesures de volume persistantes
. Mesures de réclamation de volume persistant
. Mesures du pod
. Métriques de ReplicaSet
. Mesures de service
. Métriques StatefulSet
. Mesures de l'autoscaler horizontal des pods
. Mesures des tâches cron
. Indicateurs d'emploi
. Mesures des quotas de ressources

