---
sidebar: sidebar 
permalink: task_dc_cohesity_smartfiles.html 
keywords: data collector, cohesity 
summary: Configuration du collecteur de données Cohesity SmartFiles. 
---
= Collecteur de données Cohesity SmartFiles
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Ce collecteur basé sur l'API REST acquerra un cluster Cohesity, découvrira les « vues » (en tant que volumes internes Data Infrastructure Insights ), les différents nœuds, ainsi que collectera des mesures de performances.



== Configuration

[cols="2*"]
|===
| Champ | Description 


| IP du cluster Cohesity | Adresse IP du cluster Cohesity 


| Nom d'utilisateur | Nom d'utilisateur pour le cluster Cohesity 


| Mot de passe | Mot de passe utilisé pour le cluster Cohesity 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port utilisé pour la communication TCP avec le cluster Cohesity 


| Intervalle d'interrogation d'inventaire (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est de 60 minutes. 


| Intervalle de sondage des performances (min) | Intervalle entre les sondages de performance. La valeur par défaut est de 900 secondes. 
|===


== Dépannage

Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
