---
sidebar: sidebar 
permalink: task_dc_emc_vplex.html 
keywords: data collector, VPLEX, EMC 
summary: Configuration du collecteur de données VPLEX. 
---
= Configuration du collecteur de données EMC VPLEX
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Ce collecteur de données acquiert les données d'inventaire et de performances des systèmes de stockage EMC VPLEX.  Pour la configuration, le collecteur de données nécessite une adresse IP du serveur VPLEX et un compte de domaine de niveau administratif.


NOTE: La collecte des performances de Data Infrastructure Insights à partir des clusters Vplex nécessite que le service d'archivage des performances soit opérationnel, afin de renseigner les fichiers .CSV et les journaux que Data Infrastructure Insights récupère via des copies de fichiers basées sur SCP.  NetApp a observé que de nombreuses mises à jour de la station de gestion/mise à niveau du micrologiciel Vplex rendront cette fonctionnalité non opérationnelle.  Les clients qui prévoient de telles mises à niveau peuvent souhaiter demander de manière proactive à Dell/EMC si leur mise à niveau prévue laissera cette fonctionnalité inutilisable et, si oui, comment peuvent-ils la réactiver pour minimiser les écarts de visibilité des performances ?  Le code de performance Vplex de Cloud Insight évaluera à chaque interrogation si tous les fichiers attendus existent et s'ils sont correctement mis à jour ; s'ils sont manquants ou obsolètes, Data Infrastructure Insights enregistrera les échecs de collecte des performances.



== Terminologie

Data Infrastructure Insightst acquiert les informations d'inventaire suivantes auprès du collecteur de données VPLEX.  Pour chaque type d’actif acquis, la terminologie la plus courante utilisée pour cet actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Cluster | Stockage 


| Moteur | Nœud de stockage 


| Appareil, étendue du système | Pool de stockage principal 


| Volume virtuel | Volume 


| Port frontal, port dorsal | Port 


| Dispositif distribué | Synchronisation du stockage 


| Vue de stockage | Carte de volume, masque de volume 


| Volume de stockage | LUN principal 


| ITL | Chemin d'accès au backend 
|===
Remarque : il s’agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

* Une adresse IP de la console de gestion VPLEX
* Compte de domaine de niveau administratif pour le serveur VPLEX
* Port 443 (HTTPS).  Nécessite une connectivité sortante au port TCP 443 sur la station de gestion VPLEX.
* Pour des performances optimales, nom d'utilisateur et mot de passe en lecture seule pour l'accès ssh/scp.
* Pour les performances, le port 22 est requis.




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP de la console de gestion VPLEX | Adresse IP ou nom de domaine complet de la console de gestion VPLEX 


| Nom d'utilisateur | Nom d'utilisateur pour VPLEX CLI 


| Mot de passe | Mot de passe utilisé pour VPLEX CLI 


| Adresse IP distante de performance | Adresse IP distante des performances de la console de gestion VPLEX 


| Nom d'utilisateur à distance des performances | Nom d'utilisateur distant de la console de gestion VPLEX 


| Mot de passe à distance de performance | Mot de passe distant des performances de la console de gestion VPLEX 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port de communication | Port utilisé pour VPLEX CLI.  La valeur par défaut est 443. 


| Intervalle d'interrogation d'inventaire (min) | La valeur par défaut est de 20 minutes. 


| Nombre de tentatives de connexion | La valeur par défaut est 3. 


| Intervalle d'interrogation des performances (sec) | Intervalle entre les sondages de performance. La valeur par défaut est de 600 secondes. 


| Nombre de tentatives | La valeur par défaut est 2. 
|===


== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Erreur : l’authentification de l’utilisateur a échoué. | Assurez-vous que vos informations d'identification pour cet appareil sont correctes. 
|===


=== Performances

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Erreur : les performances VPLEX pour la version inférieure à 5.3 ne sont pas prises en charge. | Mettre à niveau VPLEX vers la version 5.3 ou supérieure 


| Erreur : les données collectées ne sont pas suffisantes. | • Vérifiez l'horodatage de la collecte dans le fichier journal et modifiez l'intervalle d'interrogation en conséquence • Attendez plus longtemps 


| Erreur : les fichiers journaux perpétuels ne sont pas mis à jour. | Veuillez contacter le support EMC pour activer la mise à jour des fichiers journaux perpétuels 


| Erreur : l’intervalle d’interrogation des performances est trop grand. | Vérifiez l'horodatage de la collecte dans le fichier journal ${logfile} et modifiez l'intervalle d'interrogation en conséquence 


| Erreur : l'adresse IP distante des performances de la console de gestion VPLEX n'est pas configurée. | Modifiez la source de données pour définir l'adresse IP distante des performances de la console de gestion VPLEX. 


| Erreur : aucune donnée de performance n'a été signalée par le directeur | • Vérifiez que les moniteurs de performances du système fonctionnent correctement. • Veuillez contacter le support EMC pour activer la mise à jour des fichiers journaux du moniteur de performances du système. 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
