---
sidebar: sidebar 
permalink: task_modify_delete_query.html 
summary: 'Modifiez les requêtes existantes en changeant les critères et les colonnes, avec des options d"enregistrement flexibles pour mettre à jour, renommer ou créer de nouvelles versions, ainsi que des options pour supprimer les requêtes lorsqu"elles ne sont plus nécessaires.' 
keywords: query, queries, modify, edit, delete, remove 
---
= Modifier ou supprimer une requête
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Gérez efficacement vos requêtes en modifiant les critères de recherche, en ajoutant ou en supprimant des colonnes et en choisissant parmi des options d'enregistrement flexibles. Mettez à jour les requêtes existantes, créez de nouvelles versions ou supprimez les requêtes qui ne sont plus nécessaires afin de maintenir votre bibliothèque de requêtes organisée et à jour.



[[modifying-a-query]]
== Modifier une requête

.Étapes
. Cliquez sur *Explorer* et sélectionnez *Toutes les requêtes de métriques*.
+
La page Requêtes s'affiche.

. Cliquez sur le nom de la requête
. Pour ajouter un critère à la requête, cliquez sur l’icône Colonnes et sélectionnez une métrique ou un attribut dans la liste.


Une fois que vous avez effectué toutes les modifications nécessaires, effectuez l’une des opérations suivantes :

* Cliquez sur le bouton *Enregistrer* pour enregistrer la requête avec le nom utilisé initialement.
* Cliquez sur le menu déroulant à côté du bouton *Enregistrer* et sélectionnez *Enregistrer sous* pour enregistrer la requête sous un autre nom.  Cela n’écrase pas la requête d’origine.
* Cliquez sur le menu déroulant à côté du bouton *Enregistrer* et sélectionnez *Renommer* pour modifier le nom de la requête que vous aviez utilisé initialement.  Cela écrase la requête d'origine.
* Cliquez sur le menu déroulant à côté du bouton *Enregistrer* et sélectionnez *Annuler les modifications* pour rétablir la requête aux dernières modifications enregistrées.




[[deleting-a-query]]
== Suppression d'une requête

Pour supprimer une requête, cliquez sur *Requêtes* et sélectionnez *Afficher toutes les requêtes*, puis effectuez l'une des opérations suivantes :

. Cliquez sur le menu « trois points » à droite de la requête et cliquez sur *Supprimer*.
. Cliquez sur le nom de la requête et sélectionnez *Supprimer* dans le menu déroulant *Enregistrer*.

