---
sidebar: sidebar 
permalink: task_dc_vmware.html 
keywords: data collector, VMware, 
summary: Configuration du collecteur de données VMware. 
---
= Configuration du collecteur de données VMware VSphere
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Le collecteur de données pour VMware vSphere collecte les informations de performances et de configuration des invités VM et des hôtes ESXi et requiert des privilèges en lecture seule sur tous les objets de vSphere.  Depuis août 2024, le collecteur vSphere récupère également des messages de journal provenant d'environnements vSphere et certaines mesures spécifiques à VMware.  Veuillez noter que Data Infrastructure Insights ne peut récupérer les informations des journaux VMware qu'à partir d'environnements vSphere 8.0.1 ou supérieurs.  De même, les mesures spécifiques au fournisseur ne sont prises en charge que pour les environnements vSphere 7+.  Par conséquent, vous souhaiterez peut-être désactiver la case à cocher des journaux et/ou des mesures spécifiques au fournisseur sur un collecteur donné s'il pointe vers une instance vSphere plus ancienne.



== Terminologie

Data Infrastructure Insights acquiert les informations d’inventaire suivantes auprès du collecteur de données VMware vSphere.  Pour chaque type d’actif acquis, la terminologie la plus courante utilisée pour l’actif est indiquée.  Lorsque vous consultez ou dépannez ce collecteur de données, gardez à l'esprit la terminologie suivante :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Data Infrastructure Insights 


| Disque virtuel | Disque 


| Hôte | Hôte 


| Machine virtuelle | Machine virtuelle 


| Magasin de données | Magasin de données 


| LUN | Volume 


| Port Fibre Channel | Port 
|===
Il s'agit uniquement de mappages de terminologie courants et ils peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences

Les informations suivantes sont requises pour configurer ce collecteur de données :

* Adresse IP du serveur Virtual Center
* Nom d'utilisateur et mot de passe en lecture seule dans Virtual Center
* Nous exigeons des privilèges de lecture seule sur tous les objets dans Virtual Center.
* Accès au SDK sur le serveur Virtual Center – normalement déjà configuré.
* Exigences de port : http-80 https-443
* Valider l'accès :
+
** Connectez-vous au client Virtual Center en utilisant le nom d'utilisateur et le mot de passe ci-dessus
** Vérifier que le SDK est activé : telnet <vc_ip> 443






== Installation et connexion

[cols="2*"]
|===
| Champ | Description 


| Nom | Nom unique pour le collecteur de données 


| Unité d'acquisition | Nom de l'unité d'acquisition 
|===


== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP du centre virtuel | Adresse IP du centre virtuel 


| Nom d'utilisateur | Nom d'utilisateur utilisé pour accéder au centre virtuel 


| Mot de passe | Mot de passe utilisé pour accéder au centre virtuel 
|===


== Configuration avancée

Dans l'écran de configuration avancée, cochez la case *Performances VM* pour collecter les données de performances.  La collecte d'inventaire est activée par défaut.  Les champs suivants peuvent être configurés :

[cols="2*"]
|===


| Champ | Description 


| Intervalle d'interrogation de l'inventaire (min) | La valeur par défaut est 20 


| Filtrer les machines virtuelles | Sélectionnez CLUSTER, DATACENTER ou ESX HOST 


| Choisissez « Exclure » ou « Inclure » pour spécifier une liste | Créer une liste de filtres (CLUSTER, DATACENTER et/ou ESX_HOST) 


| Nombre de tentatives | La valeur par défaut est 3 


| Port de communication | La valeur par défaut est 443 


| Filtrer la liste des appareils... | Cette liste doit être composée de correspondances de chaînes exactes. Si vous avez l'intention de filtrer par ESX_HOST, vous devez créer une liste délimitée par des virgules des « noms » exacts de vos hôtes ESX tels que rapportés dans Data Infrastructure Insights et vSphere.  Ces « noms » peuvent être des adresses IP, des noms d’hôtes simples ou des noms de domaine complets (FQDN) ; cela est déterminé par la façon dont ces hôtes ont été nommés lors de leur ajout initial à vSphere.  Lors du filtrage par CLUSTER, utilisez les noms de cluster de style Data Infrastructure Insights tels que rapportés par CI sur les hyperviseurs - Data Infrastructure Insights ajoute au nom du cluster vSphere le nom du centre de données vSphere et une barre oblique - « DC1/clusterA » est le nom du cluster que Data Infrastructure Insights signalerait sur un hyperviseur dans clusterA au sein du centre de données DC1. 


| Intervalle d'interrogation des performances (sec) | La valeur par défaut est 300 
|===


== Mappage des balises VMware aux annotations Data Infrastructure Insights

Le collecteur de données VMware vous permet de renseigner les annotations Data Infrastructure Insights avec des balises configurées sur VMware.  Le nom de l'annotation DII doit être identique au nom de la *catégorie* VMware ; la balise est ensuite appliquée comme valeur d'annotation d'une annotation DII du même nom que la catégorie.  Data Infrastructure Insights renseignera toujours les annotations de type texte portant le même nom et fera de son mieux pour renseigner les annotations d'autres types (nombre, booléen, etc.).  Si votre annotation est d'un type différent et que le collecteur de données ne parvient pas à la renseigner, il peut être nécessaire de supprimer l'annotation et de la recréer en tant que type de texte.

Notez que les balises VMware peuvent être sensibles à la casse, tandis que les balises Data Infrastructure Insights ne le sont pas.  Ainsi, si vous créez une annotation nommée « OWNER » dans Data Infrastructure Insights et des balises nommées « OWNER », « Owner » et « owner » dans VMware, toutes ces variantes de « owner » seront mappées à l'annotation « OWNER » de Cloud Insight.

Gardez à l’esprit les points suivants :

* Data Infrastructure Insights publie actuellement automatiquement uniquement les informations de support pour les appareils NetApp .
* Étant donné que ces informations d’assistance sont conservées sous forme d’annotation, vous pouvez les interroger ou les utiliser dans des tableaux de bord.
* Si un utilisateur écrase ou vide la valeur d'annotation, la valeur est à nouveau remplie automatiquement lorsque Data Infrastructure Insights met à jour les annotations, ce qu'il fait une fois par jour.




== Dépannage

Quelques éléments à essayer si vous rencontrez des problèmes avec ce collecteur de données :



=== Inventaire

[cols="2*"]
|===
| Problème: | Essayez ceci: 


| Erreur : la liste d'inclusion pour filtrer les machines virtuelles ne peut pas être vide | Si l'option Inclure la liste est sélectionnée, veuillez répertorier les noms de centre de données, de cluster ou d'hôte valides pour filtrer les machines virtuelles. 


| Erreur : échec de l'instanciation d'une connexion à VirtualCenter à l'adresse IP | Solutions possibles : * Vérifier les informations d’identification et l’adresse IP saisies.  * Essayez de communiquer avec Virtual Center à l’aide de VMware Infrastructure Client.  * Essayez de communiquer avec Virtual Center à l'aide du navigateur d'objets gérés (par exemple MOB). 


| Erreur : VirtualCenter sur IP possède un certificat non conforme requis par JVM | Solutions possibles : * Recommandé : régénérez le certificat pour Virtual Center en utilisant une clé RSA plus forte (par exemple 1 024 bits).  * Non recommandé : modifiez la configuration java.security de la JVM pour exploiter la contrainte jdk.certpath.disabledAlgorithms afin d'autoriser la clé RSA 512 bits. Voir link:http://www.oracle.com/technetwork/java/javase/7u40-relnotes-2004172.html["Notes de publication de la mise à jour 40 du JDK 7"] . 


| Je vois le message : « Le package VMware Logs n'est pas pris en charge sur VMware avant la version 8.0.1 » | La collecte de journaux n'est pas prise en charge sur les versions de VMware antérieures à 8.0.1.  Mettez à niveau votre infrastructure VI Center vers la version 8.0.1 ou une version ultérieure si vous souhaitez utiliser la fonctionnalité Collections de journaux dans Data Infrastructure Insights.  Pour plus d'informations, voir cecilink:https://kb.netapp.com/Cloud/ncds/nds/dii/dii_kbs/Data_Infrastructure_Insights_Brocade_data_source_fails_performance_collection_with_a_timeout_due_to_default_SNMP_configuration["Article de la base de connaissances"] . 
|===
Des informations complémentaires peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
