---
sidebar: sidebar 
permalink: task_dc_ms_anf.html 
keywords: data collector, azure, Netapp files, anf 
summary: Configuration du collecteur de données Azure NetApp Files . 
---
= Configuration du collecteur de données Azure NetApp Files
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights utilise le collecteur de données Azure NetApp Files pour acquérir des données d’inventaire et de performances.



== Exigences

Vous avez besoin des informations suivantes pour configurer ce collecteur de données.

* Exigence de port : 443 HTTPS
* IP REST de gestion Azure (management.azure.com)
* ID client du principal du service Azure (compte d'utilisateur)
* Clé d'authentification du principal du service Azure (mot de passe utilisateur)
* Vous devez configurer un compte Azure pour la découverte de Data Infrastructure Insights .
+
Une fois le compte correctement configuré et l’application enregistrée dans Azure, vous disposerez des informations d’identification requises pour découvrir l’instance Azure avec Data Infrastructure Insights.  Le lien suivant décrit comment configurer le compte pour la découverte :



https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]



== Configuration

Saisissez les données dans les champs du collecteur de données conformément au tableau ci-dessous :

[cols="2*"]
|===
| Champ | Description 


| ID client du principal du service Azure | ID de connexion à Azure 


| ID de locataire Azure | ID de locataire Azure 


| Clé d'authentification du principal du service Azure | Clé d'authentification de connexion 


| Je comprends que Microsoft me facture les demandes d'API | Cochez cette case pour vérifier que vous avez bien compris que Microsoft vous facture les demandes d’API effectuées par le sondage Insight. 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation d'inventaire (min) | La valeur par défaut est 60 
|===


== Dépannage

* Les informations d’identification utilisées par votre collecteur de données ANF doivent avoir accès à tous les abonnements Azure contenant des volumes ANF.
* Si l’accès du lecteur entraîne l’échec de la collecte des performances, essayez d’accorder l’accès du contributeur au niveau du groupe de ressources.


Des informations complémentaires sur ce collecteur de données peuvent être trouvées à partir dulink:concept_requesting_support.html["Support"] page ou dans lelink:reference_data_collector_support_matrix.html["Matrice de support du collecteur de données"] .
