---
sidebar: sidebar 
permalink: task_view_queries.html 
summary: Affichage des requêtes créées 
keywords: query, queries, viewing 
---
= Consultation des requêtes
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Vous pouvez afficher vos requêtes pour surveiller vos actifs et modifier la manière dont vos requêtes affichent les données liées à vos actifs.

.Étapes
. Connectez-vous à votre locataire Data Infrastructure Insights .
. Cliquez sur *Requêtes* et sélectionnez *Afficher toutes les requêtes*.  Vous pouvez modifier la façon dont les requêtes s'affichent en effectuant l'une des opérations suivantes :
. Vous pouvez saisir du texte dans la zone de filtre pour rechercher et afficher des requêtes spécifiques.
. Vous pouvez modifier l'ordre de tri des colonnes dans le tableau des requêtes en ordre croissant (flèche vers le haut) ou décroissant (flèche vers le bas) en cliquant sur la flèche dans l'en-tête de la colonne.
. Pour redimensionner une colonne, passez la souris sur l'en-tête de la colonne jusqu'à ce qu'une barre bleue apparaisse.  Placez la souris sur la barre et faites-la glisser vers la droite ou vers la gauche.
. Pour déplacer une colonne, cliquez sur l'en-tête de la colonne et faites-le glisser vers la droite ou vers la gauche.


Lorsque vous faites défiler les résultats de la requête, sachez que les résultats peuvent changer à mesure que Data Infrastructure Insights interroge automatiquement vos collecteurs de données.  Cela peut entraîner l'absence de certains éléments ou l'affichage de certains éléments dans le désordre, selon la façon dont ils sont triés.
